// Generated by CIRCT firtool-1.140.0
module FuseMax2DPE(
  input         clock,
                reset,
                io_cmd_en,
  input  [3:0]  io_cmd_op,
  input  [2:0]  io_cmd_aSel,
  input  [3:0]  io_cmd_aIdx,
  input  [2:0]  io_cmd_bSel,
  input  [3:0]  io_cmd_bIdx,
  input  [2:0]  io_cmd_cSel,
  input  [3:0]  io_cmd_cIdx,
                io_cmd_dstIdx,
  input         io_cmd_writeDst,
                io_cmd_southFromFu,
  input  [7:0]  io_in_w_bits,
                io_in_n_bits,
  input  [15:0] io_in_scalar_bits,
  output [7:0]  io_out_e_bits,
                io_out_s_bits
);

  wire [8:0]        _io_out_s_resizer_io_out;
  wire              _fuOut_cmp_agtb;
  wire [15:0]       _sharedMacOut_mac_z;
  reg  [7:0]        pipeReg_bits;
  reg  [7:0]        northReg_bits;
  reg  [15:0]       rf_0_bits;
  reg  [15:0]       rf_1_bits;
  reg  [15:0]       rf_2_bits;
  reg  [15:0]       rf_3_bits;
  reg  [15:0]       rf_4_bits;
  reg  [15:0]       rf_5_bits;
  reg  [15:0]       rf_6_bits;
  reg  [15:0]       rf_7_bits;
  reg  [15:0]       rf_8_bits;
  reg  [15:0]       rf_9_bits;
  wire [15:0][15:0] _GEN =
    {{rf_0_bits},
     {rf_0_bits},
     {rf_0_bits},
     {rf_0_bits},
     {rf_0_bits},
     {rf_0_bits},
     {rf_9_bits},
     {rf_8_bits},
     {rf_7_bits},
     {rf_6_bits},
     {rf_5_bits},
     {rf_4_bits},
     {rf_3_bits},
     {rf_2_bits},
     {rf_1_bits},
     {rf_0_bits}};
  wire [7:0][15:0]  _GEN_0 =
    {{16'h0},
     {16'h0},
     {16'h0},
     {_GEN[io_cmd_aIdx]},
     {io_in_scalar_bits},
     {{northReg_bits, 8'h0}},
     {{pipeReg_bits, 8'h0}},
     {16'h0}};
  wire [7:0][15:0]  _GEN_1 =
    {{16'h0},
     {16'h0},
     {16'h0},
     {_GEN[io_cmd_bIdx]},
     {io_in_scalar_bits},
     {{northReg_bits, 8'h0}},
     {{pipeReg_bits, 8'h0}},
     {16'h0}};
  wire [7:0][15:0]  _GEN_2 =
    {{16'h0},
     {16'h0},
     {16'h0},
     {_GEN[io_cmd_cIdx]},
     {io_in_scalar_bits},
     {{northReg_bits, 8'h0}},
     {{pipeReg_bits, 8'h0}},
     {16'h0}};
  wire              _GEN_3 = io_cmd_op == 4'h2;
  wire              _GEN_4 = io_cmd_op == 4'h3;
  wire              _GEN_5 = io_cmd_op == 4'h4;
  wire              _GEN_6 = io_cmd_op == 4'h5;
  wire              _GEN_7 = _GEN_5 | _GEN_6;
  wire              _GEN_8 = _GEN_3 | _GEN_4 | _GEN_7;
  wire              _GEN_9 = io_cmd_op == 4'h0;
  wire              _GEN_10 = io_cmd_op == 4'h1;
  wire              _GEN_11 = io_cmd_op == 4'h6;
  wire [15:0]       fuOut_bits =
    _GEN_9
      ? 16'h0
      : _GEN_10
          ? _GEN_0[io_cmd_aSel]
          : _GEN_8
              ? _sharedMacOut_mac_z
              : _GEN_11
                  ? (_fuOut_cmp_agtb ? _GEN_1[io_cmd_bSel] : _GEN_0[io_cmd_aSel])
                  : 16'h0;
  wire              io_out_s_self_rec_rawIn_isZeroExpIn = fuOut_bits[14:10] == 5'h0;
  wire [3:0]        io_out_s_self_rec_rawIn_normDist =
    fuOut_bits[9]
      ? 4'h0
      : fuOut_bits[8]
          ? 4'h1
          : fuOut_bits[7]
              ? 4'h2
              : fuOut_bits[6]
                  ? 4'h3
                  : fuOut_bits[5]
                      ? 4'h4
                      : fuOut_bits[4]
                          ? 4'h5
                          : fuOut_bits[3]
                              ? 4'h6
                              : fuOut_bits[2] ? 4'h7 : {3'h4, ~(fuOut_bits[1])};
  wire [24:0]       _io_out_s_self_rec_rawIn_subnormFract_T =
    {15'h0, fuOut_bits[9:0]} << io_out_s_self_rec_rawIn_normDist;
  wire [5:0]        _io_out_s_self_rec_rawIn_adjustedExp_T_4 =
    (io_out_s_self_rec_rawIn_isZeroExpIn
       ? {2'h3, ~io_out_s_self_rec_rawIn_normDist}
       : {1'h0, fuOut_bits[14:10]})
    + {4'h4, io_out_s_self_rec_rawIn_isZeroExpIn ? 2'h2 : 2'h1};
  wire [2:0]        _io_out_s_self_rec_T_1 =
    io_out_s_self_rec_rawIn_isZeroExpIn & ~(|(fuOut_bits[9:0]))
      ? 3'h0
      : _io_out_s_self_rec_rawIn_adjustedExp_T_4[5:3];
  wire              io_out_s_result_bits_rawIn_isInf =
    (&(_io_out_s_resizer_io_out[7:6])) & ~(_io_out_s_resizer_io_out[5]);
  wire              io_out_s_result_bits_isSubnormal =
    $signed({1'h0, _io_out_s_resizer_io_out[7:2]}) < 7'sh12;
  wire [2:0]        _io_out_s_result_bits_denormFract_T_1 =
    {1'h0, |(_io_out_s_resizer_io_out[7:5]), _io_out_s_resizer_io_out[1]} >> 1'h1
    - _io_out_s_resizer_io_out[2];
  always @(posedge clock) begin
    if (reset) begin
      pipeReg_bits <= 8'h0;
      northReg_bits <= 8'h0;
      rf_0_bits <= 16'h0;
      rf_1_bits <= 16'h0;
      rf_2_bits <= 16'h0;
      rf_3_bits <= 16'h0;
      rf_4_bits <= 16'h0;
      rf_5_bits <= 16'h0;
      rf_6_bits <= 16'h0;
      rf_7_bits <= 16'h0;
      rf_8_bits <= 16'h0;
      rf_9_bits <= 16'h0;
    end
    else begin
      automatic logic _GEN_12 = io_cmd_en & io_cmd_writeDst;
      pipeReg_bits <= io_in_w_bits;
      northReg_bits <= io_in_n_bits;
      if (_GEN_12 & io_cmd_dstIdx == 4'h0) begin
        if (_GEN_9)
          rf_0_bits <= 16'h0;
        else if (_GEN_10)
          rf_0_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_0_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_0_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_0_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_0_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h1) begin
        if (_GEN_9)
          rf_1_bits <= 16'h0;
        else if (_GEN_10)
          rf_1_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_1_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_1_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_1_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_1_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h2) begin
        if (_GEN_9)
          rf_2_bits <= 16'h0;
        else if (_GEN_10)
          rf_2_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_2_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_2_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_2_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_2_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h3) begin
        if (_GEN_9)
          rf_3_bits <= 16'h0;
        else if (_GEN_10)
          rf_3_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_3_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_3_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_3_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_3_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h4) begin
        if (_GEN_9)
          rf_4_bits <= 16'h0;
        else if (_GEN_10)
          rf_4_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_4_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_4_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_4_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_4_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h5) begin
        if (_GEN_9)
          rf_5_bits <= 16'h0;
        else if (_GEN_10)
          rf_5_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_5_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_5_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_5_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_5_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h6) begin
        if (_GEN_9)
          rf_6_bits <= 16'h0;
        else if (_GEN_10)
          rf_6_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_6_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_6_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_6_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_6_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h7) begin
        if (_GEN_9)
          rf_7_bits <= 16'h0;
        else if (_GEN_10)
          rf_7_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_7_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_7_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_7_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_7_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h8) begin
        if (_GEN_9)
          rf_8_bits <= 16'h0;
        else if (_GEN_10)
          rf_8_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_8_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_8_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_8_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_8_bits <= 16'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h9) begin
        if (_GEN_9)
          rf_9_bits <= 16'h0;
        else if (_GEN_10)
          rf_9_bits <= _GEN_0[io_cmd_aSel];
        else if (_GEN_8)
          rf_9_bits <= _sharedMacOut_mac_z;
        else if (_GEN_11) begin
          if (_fuOut_cmp_agtb)
            rf_9_bits <= _GEN_1[io_cmd_bSel];
          else
            rf_9_bits <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_9_bits <= 16'h0;
      end
    end
  end // always @(posedge)
  DW_fp_mac #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) sharedMacOut_mac (
    .a
      (_GEN_3 ? 16'h3C00 : _GEN_4 ? 16'hBC00 : _GEN_7 ? _GEN_0[io_cmd_aSel] : 16'h0),
    .b      (_GEN_8 ? _GEN_1[io_cmd_bSel] : 16'h3C00),
    .c
      (_GEN_3 | _GEN_4
         ? _GEN_0[io_cmd_aSel]
         : _GEN_5 | ~_GEN_6 ? 16'h0 : _GEN_2[io_cmd_cSel]),
    .rnd    (3'h0),
    .z      (_sharedMacOut_mac_z),
    .status (/* unused */)
  );
  DW_fp_cmp #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) fuOut_cmp (
    .a         (_GEN_1[io_cmd_bSel]),
    .b         (_GEN_0[io_cmd_aSel]),
    .zctr      (1'h0),
    .aeqb      (/* unused */),
    .altb      (/* unused */),
    .agtb      (_fuOut_cmp_agtb),
    .unordered (/* unused */),
    .z0        (/* unused */),
    .z1        (/* unused */),
    .status0   (/* unused */),
    .status1   (/* unused */)
  );
  RecFNToRecFN io_out_s_resizer (
    .io_in
      ({fuOut_bits[15],
        _io_out_s_self_rec_T_1[2:1],
        _io_out_s_self_rec_T_1[0] | (&(_io_out_s_self_rec_rawIn_adjustedExp_T_4[5:4]))
          & (|(fuOut_bits[9:0])),
        _io_out_s_self_rec_rawIn_adjustedExp_T_4[2:0],
        io_out_s_self_rec_rawIn_isZeroExpIn
          ? {_io_out_s_self_rec_rawIn_subnormFract_T[8:0], 1'h0}
          : fuOut_bits[9:0]}),
    .io_out (_io_out_s_resizer_io_out)
  );
  assign io_out_e_bits = pipeReg_bits;
  assign io_out_s_bits =
    io_cmd_en & io_cmd_southFromFu
      ? {_io_out_s_resizer_io_out[8],
         (io_out_s_result_bits_isSubnormal ? 5'h0 : _io_out_s_resizer_io_out[6:2] + 5'hF)
           | {5{(&(_io_out_s_resizer_io_out[7:6])) & _io_out_s_resizer_io_out[5]
                  | io_out_s_result_bits_rawIn_isInf}},
         io_out_s_result_bits_isSubnormal
           ? _io_out_s_result_bits_denormFract_T_1[1:0]
           : io_out_s_result_bits_rawIn_isInf ? 2'h0 : _io_out_s_resizer_io_out[1:0]}
      : northReg_bits;
endmodule

