// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [15:0] io_west_0_data,
  input  [1:0]  io_west_1_op,
  input  [15:0] io_west_1_data,
  input  [1:0]  io_west_2_op,
  input  [15:0] io_west_2_data,
  input  [1:0]  io_west_3_op,
  input  [15:0] io_west_3_data,
  input  [31:0] io_north_0,
                io_north_1,
                io_north_2,
                io_north_3,
  output [31:0] io_southRaw_0,
                io_southRaw_1,
                io_southRaw_2,
                io_southRaw_3
);

  wire [15:0] _pes_2_3_io_eastOut;
  wire [15:0] _pes_1_3_io_eastOut;
  wire [15:0] _pes_0_3_io_eastOut;
  wire [31:0] _pes_3_2_io_southOut;
  wire [15:0] _pes_2_2_io_eastOut;
  wire [31:0] _pes_2_2_io_southOut;
  wire [15:0] _pes_1_2_io_eastOut;
  wire [31:0] _pes_1_2_io_southOut;
  wire [15:0] _pes_0_2_io_eastOut;
  wire [31:0] _pes_0_2_io_southOut;
  wire [31:0] _pes_3_1_io_southOut;
  wire [15:0] _pes_2_1_io_eastOut;
  wire [31:0] _pes_2_1_io_southOut;
  wire [15:0] _pes_1_1_io_eastOut;
  wire [31:0] _pes_1_1_io_southOut;
  wire [15:0] _pes_0_1_io_eastOut;
  wire [31:0] _pes_0_1_io_southOut;
  wire [31:0] _pes_3_io_southOut;
  wire [15:0] _pes_2_io_eastOut;
  wire [31:0] _pes_2_io_southOut;
  wire [15:0] _pes_1_io_eastOut;
  wire [31:0] _pes_1_io_southOut;
  wire [15:0] _pes_0_io_eastOut;
  wire [31:0] _pes_0_io_southOut;
  PE pes_0 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (io_west_0_data),
    .io_northIn  (io_north_0),
    .io_eastOut  (_pes_0_io_eastOut),
    .io_southOut (_pes_0_io_southOut)
  );
  PE pes_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_0_io_eastOut),
    .io_northIn  (io_north_1),
    .io_eastOut  (_pes_1_io_eastOut),
    .io_southOut (_pes_1_io_southOut)
  );
  PE pes_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_1_io_eastOut),
    .io_northIn  (io_north_2),
    .io_eastOut  (_pes_2_io_eastOut),
    .io_southOut (_pes_2_io_southOut)
  );
  PE pes_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_2_io_eastOut),
    .io_northIn  (io_north_3),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_3_io_southOut)
  );
  PE pes_0_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (io_west_1_data),
    .io_northIn  (_pes_0_io_southOut),
    .io_eastOut  (_pes_0_1_io_eastOut),
    .io_southOut (_pes_0_1_io_southOut)
  );
  PE pes_1_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_0_1_io_eastOut),
    .io_northIn  (_pes_1_io_southOut),
    .io_eastOut  (_pes_1_1_io_eastOut),
    .io_southOut (_pes_1_1_io_southOut)
  );
  PE pes_2_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_1_1_io_eastOut),
    .io_northIn  (_pes_2_io_southOut),
    .io_eastOut  (_pes_2_1_io_eastOut),
    .io_southOut (_pes_2_1_io_southOut)
  );
  PE pes_3_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_2_1_io_eastOut),
    .io_northIn  (_pes_3_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_3_1_io_southOut)
  );
  PE pes_0_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (io_west_2_data),
    .io_northIn  (_pes_0_1_io_southOut),
    .io_eastOut  (_pes_0_2_io_eastOut),
    .io_southOut (_pes_0_2_io_southOut)
  );
  PE pes_1_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_0_2_io_eastOut),
    .io_northIn  (_pes_1_1_io_southOut),
    .io_eastOut  (_pes_1_2_io_eastOut),
    .io_southOut (_pes_1_2_io_southOut)
  );
  PE pes_2_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_1_2_io_eastOut),
    .io_northIn  (_pes_2_1_io_southOut),
    .io_eastOut  (_pes_2_2_io_eastOut),
    .io_southOut (_pes_2_2_io_southOut)
  );
  PE pes_3_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_2_2_io_eastOut),
    .io_northIn  (_pes_3_1_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_3_2_io_southOut)
  );
  PE pes_0_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (io_west_3_data),
    .io_northIn  (_pes_0_2_io_southOut),
    .io_eastOut  (_pes_0_3_io_eastOut),
    .io_southOut (io_southRaw_0)
  );
  PE pes_1_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_0_3_io_eastOut),
    .io_northIn  (_pes_1_2_io_southOut),
    .io_eastOut  (_pes_1_3_io_eastOut),
    .io_southOut (io_southRaw_1)
  );
  PE pes_2_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_1_3_io_eastOut),
    .io_northIn  (_pes_2_2_io_southOut),
    .io_eastOut  (_pes_2_3_io_eastOut),
    .io_southOut (io_southRaw_2)
  );
  PE pes_3_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_2_3_io_eastOut),
    .io_northIn  (_pes_3_2_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (io_southRaw_3)
  );
endmodule

