// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [15:0] io_west_0_data,
  input  [1:0]  io_west_1_op,
  input  [15:0] io_west_1_data,
  input  [1:0]  io_west_2_op,
  input  [15:0] io_west_2_data,
  input  [1:0]  io_west_3_op,
  input  [15:0] io_west_3_data,
  input  [1:0]  io_west_4_op,
  input  [15:0] io_west_4_data,
  input  [1:0]  io_west_5_op,
  input  [15:0] io_west_5_data,
  input  [1:0]  io_west_6_op,
  input  [15:0] io_west_6_data,
  input  [1:0]  io_west_7_op,
  input  [15:0] io_west_7_data,
  input  [31:0] io_north_0,
                io_north_1,
                io_north_2,
                io_north_3,
                io_north_4,
                io_north_5,
                io_north_6,
                io_north_7,
  output [31:0] io_southRaw_0,
                io_southRaw_1,
                io_southRaw_2,
                io_southRaw_3,
                io_southRaw_4,
                io_southRaw_5,
                io_southRaw_6,
                io_southRaw_7
);

  wire [15:0] _pes_6_7_io_eastOut;
  wire [15:0] _pes_5_7_io_eastOut;
  wire [15:0] _pes_4_7_io_eastOut;
  wire [15:0] _pes_3_7_io_eastOut;
  wire [15:0] _pes_2_7_io_eastOut;
  wire [15:0] _pes_1_7_io_eastOut;
  wire [15:0] _pes_0_7_io_eastOut;
  wire [31:0] _pes_7_6_io_southOut;
  wire [15:0] _pes_6_6_io_eastOut;
  wire [31:0] _pes_6_6_io_southOut;
  wire [15:0] _pes_5_6_io_eastOut;
  wire [31:0] _pes_5_6_io_southOut;
  wire [15:0] _pes_4_6_io_eastOut;
  wire [31:0] _pes_4_6_io_southOut;
  wire [15:0] _pes_3_6_io_eastOut;
  wire [31:0] _pes_3_6_io_southOut;
  wire [15:0] _pes_2_6_io_eastOut;
  wire [31:0] _pes_2_6_io_southOut;
  wire [15:0] _pes_1_6_io_eastOut;
  wire [31:0] _pes_1_6_io_southOut;
  wire [15:0] _pes_0_6_io_eastOut;
  wire [31:0] _pes_0_6_io_southOut;
  wire [31:0] _pes_7_5_io_southOut;
  wire [15:0] _pes_6_5_io_eastOut;
  wire [31:0] _pes_6_5_io_southOut;
  wire [15:0] _pes_5_5_io_eastOut;
  wire [31:0] _pes_5_5_io_southOut;
  wire [15:0] _pes_4_5_io_eastOut;
  wire [31:0] _pes_4_5_io_southOut;
  wire [15:0] _pes_3_5_io_eastOut;
  wire [31:0] _pes_3_5_io_southOut;
  wire [15:0] _pes_2_5_io_eastOut;
  wire [31:0] _pes_2_5_io_southOut;
  wire [15:0] _pes_1_5_io_eastOut;
  wire [31:0] _pes_1_5_io_southOut;
  wire [15:0] _pes_0_5_io_eastOut;
  wire [31:0] _pes_0_5_io_southOut;
  wire [31:0] _pes_7_4_io_southOut;
  wire [15:0] _pes_6_4_io_eastOut;
  wire [31:0] _pes_6_4_io_southOut;
  wire [15:0] _pes_5_4_io_eastOut;
  wire [31:0] _pes_5_4_io_southOut;
  wire [15:0] _pes_4_4_io_eastOut;
  wire [31:0] _pes_4_4_io_southOut;
  wire [15:0] _pes_3_4_io_eastOut;
  wire [31:0] _pes_3_4_io_southOut;
  wire [15:0] _pes_2_4_io_eastOut;
  wire [31:0] _pes_2_4_io_southOut;
  wire [15:0] _pes_1_4_io_eastOut;
  wire [31:0] _pes_1_4_io_southOut;
  wire [15:0] _pes_0_4_io_eastOut;
  wire [31:0] _pes_0_4_io_southOut;
  wire [31:0] _pes_7_3_io_southOut;
  wire [15:0] _pes_6_3_io_eastOut;
  wire [31:0] _pes_6_3_io_southOut;
  wire [15:0] _pes_5_3_io_eastOut;
  wire [31:0] _pes_5_3_io_southOut;
  wire [15:0] _pes_4_3_io_eastOut;
  wire [31:0] _pes_4_3_io_southOut;
  wire [15:0] _pes_3_3_io_eastOut;
  wire [31:0] _pes_3_3_io_southOut;
  wire [15:0] _pes_2_3_io_eastOut;
  wire [31:0] _pes_2_3_io_southOut;
  wire [15:0] _pes_1_3_io_eastOut;
  wire [31:0] _pes_1_3_io_southOut;
  wire [15:0] _pes_0_3_io_eastOut;
  wire [31:0] _pes_0_3_io_southOut;
  wire [31:0] _pes_7_2_io_southOut;
  wire [15:0] _pes_6_2_io_eastOut;
  wire [31:0] _pes_6_2_io_southOut;
  wire [15:0] _pes_5_2_io_eastOut;
  wire [31:0] _pes_5_2_io_southOut;
  wire [15:0] _pes_4_2_io_eastOut;
  wire [31:0] _pes_4_2_io_southOut;
  wire [15:0] _pes_3_2_io_eastOut;
  wire [31:0] _pes_3_2_io_southOut;
  wire [15:0] _pes_2_2_io_eastOut;
  wire [31:0] _pes_2_2_io_southOut;
  wire [15:0] _pes_1_2_io_eastOut;
  wire [31:0] _pes_1_2_io_southOut;
  wire [15:0] _pes_0_2_io_eastOut;
  wire [31:0] _pes_0_2_io_southOut;
  wire [31:0] _pes_7_1_io_southOut;
  wire [15:0] _pes_6_1_io_eastOut;
  wire [31:0] _pes_6_1_io_southOut;
  wire [15:0] _pes_5_1_io_eastOut;
  wire [31:0] _pes_5_1_io_southOut;
  wire [15:0] _pes_4_1_io_eastOut;
  wire [31:0] _pes_4_1_io_southOut;
  wire [15:0] _pes_3_1_io_eastOut;
  wire [31:0] _pes_3_1_io_southOut;
  wire [15:0] _pes_2_1_io_eastOut;
  wire [31:0] _pes_2_1_io_southOut;
  wire [15:0] _pes_1_1_io_eastOut;
  wire [31:0] _pes_1_1_io_southOut;
  wire [15:0] _pes_0_1_io_eastOut;
  wire [31:0] _pes_0_1_io_southOut;
  wire [31:0] _pes_7_io_southOut;
  wire [15:0] _pes_6_io_eastOut;
  wire [31:0] _pes_6_io_southOut;
  wire [15:0] _pes_5_io_eastOut;
  wire [31:0] _pes_5_io_southOut;
  wire [15:0] _pes_4_io_eastOut;
  wire [31:0] _pes_4_io_southOut;
  wire [15:0] _pes_3_io_eastOut;
  wire [31:0] _pes_3_io_southOut;
  wire [15:0] _pes_2_io_eastOut;
  wire [31:0] _pes_2_io_southOut;
  wire [15:0] _pes_1_io_eastOut;
  wire [31:0] _pes_1_io_southOut;
  wire [15:0] _pes_0_io_eastOut;
  wire [31:0] _pes_0_io_southOut;
  PE pes_0 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (io_west_0_data),
    .io_northIn  (io_north_0),
    .io_eastOut  (_pes_0_io_eastOut),
    .io_southOut (_pes_0_io_southOut)
  );
  PE pes_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_0_io_eastOut),
    .io_northIn  (io_north_1),
    .io_eastOut  (_pes_1_io_eastOut),
    .io_southOut (_pes_1_io_southOut)
  );
  PE pes_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_1_io_eastOut),
    .io_northIn  (io_north_2),
    .io_eastOut  (_pes_2_io_eastOut),
    .io_southOut (_pes_2_io_southOut)
  );
  PE pes_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_2_io_eastOut),
    .io_northIn  (io_north_3),
    .io_eastOut  (_pes_3_io_eastOut),
    .io_southOut (_pes_3_io_southOut)
  );
  PE pes_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_3_io_eastOut),
    .io_northIn  (io_north_4),
    .io_eastOut  (_pes_4_io_eastOut),
    .io_southOut (_pes_4_io_southOut)
  );
  PE pes_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_4_io_eastOut),
    .io_northIn  (io_north_5),
    .io_eastOut  (_pes_5_io_eastOut),
    .io_southOut (_pes_5_io_southOut)
  );
  PE pes_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_5_io_eastOut),
    .io_northIn  (io_north_6),
    .io_eastOut  (_pes_6_io_eastOut),
    .io_southOut (_pes_6_io_southOut)
  );
  PE pes_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_0_op),
    .io_westIn   (_pes_6_io_eastOut),
    .io_northIn  (io_north_7),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_7_io_southOut)
  );
  PE pes_0_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (io_west_1_data),
    .io_northIn  (_pes_0_io_southOut),
    .io_eastOut  (_pes_0_1_io_eastOut),
    .io_southOut (_pes_0_1_io_southOut)
  );
  PE pes_1_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_0_1_io_eastOut),
    .io_northIn  (_pes_1_io_southOut),
    .io_eastOut  (_pes_1_1_io_eastOut),
    .io_southOut (_pes_1_1_io_southOut)
  );
  PE pes_2_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_1_1_io_eastOut),
    .io_northIn  (_pes_2_io_southOut),
    .io_eastOut  (_pes_2_1_io_eastOut),
    .io_southOut (_pes_2_1_io_southOut)
  );
  PE pes_3_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_2_1_io_eastOut),
    .io_northIn  (_pes_3_io_southOut),
    .io_eastOut  (_pes_3_1_io_eastOut),
    .io_southOut (_pes_3_1_io_southOut)
  );
  PE pes_4_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_3_1_io_eastOut),
    .io_northIn  (_pes_4_io_southOut),
    .io_eastOut  (_pes_4_1_io_eastOut),
    .io_southOut (_pes_4_1_io_southOut)
  );
  PE pes_5_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_4_1_io_eastOut),
    .io_northIn  (_pes_5_io_southOut),
    .io_eastOut  (_pes_5_1_io_eastOut),
    .io_southOut (_pes_5_1_io_southOut)
  );
  PE pes_6_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_5_1_io_eastOut),
    .io_northIn  (_pes_6_io_southOut),
    .io_eastOut  (_pes_6_1_io_eastOut),
    .io_southOut (_pes_6_1_io_southOut)
  );
  PE pes_7_1 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_1_op),
    .io_westIn   (_pes_6_1_io_eastOut),
    .io_northIn  (_pes_7_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_7_1_io_southOut)
  );
  PE pes_0_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (io_west_2_data),
    .io_northIn  (_pes_0_1_io_southOut),
    .io_eastOut  (_pes_0_2_io_eastOut),
    .io_southOut (_pes_0_2_io_southOut)
  );
  PE pes_1_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_0_2_io_eastOut),
    .io_northIn  (_pes_1_1_io_southOut),
    .io_eastOut  (_pes_1_2_io_eastOut),
    .io_southOut (_pes_1_2_io_southOut)
  );
  PE pes_2_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_1_2_io_eastOut),
    .io_northIn  (_pes_2_1_io_southOut),
    .io_eastOut  (_pes_2_2_io_eastOut),
    .io_southOut (_pes_2_2_io_southOut)
  );
  PE pes_3_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_2_2_io_eastOut),
    .io_northIn  (_pes_3_1_io_southOut),
    .io_eastOut  (_pes_3_2_io_eastOut),
    .io_southOut (_pes_3_2_io_southOut)
  );
  PE pes_4_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_3_2_io_eastOut),
    .io_northIn  (_pes_4_1_io_southOut),
    .io_eastOut  (_pes_4_2_io_eastOut),
    .io_southOut (_pes_4_2_io_southOut)
  );
  PE pes_5_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_4_2_io_eastOut),
    .io_northIn  (_pes_5_1_io_southOut),
    .io_eastOut  (_pes_5_2_io_eastOut),
    .io_southOut (_pes_5_2_io_southOut)
  );
  PE pes_6_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_5_2_io_eastOut),
    .io_northIn  (_pes_6_1_io_southOut),
    .io_eastOut  (_pes_6_2_io_eastOut),
    .io_southOut (_pes_6_2_io_southOut)
  );
  PE pes_7_2 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_2_op),
    .io_westIn   (_pes_6_2_io_eastOut),
    .io_northIn  (_pes_7_1_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_7_2_io_southOut)
  );
  PE pes_0_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (io_west_3_data),
    .io_northIn  (_pes_0_2_io_southOut),
    .io_eastOut  (_pes_0_3_io_eastOut),
    .io_southOut (_pes_0_3_io_southOut)
  );
  PE pes_1_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_0_3_io_eastOut),
    .io_northIn  (_pes_1_2_io_southOut),
    .io_eastOut  (_pes_1_3_io_eastOut),
    .io_southOut (_pes_1_3_io_southOut)
  );
  PE pes_2_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_1_3_io_eastOut),
    .io_northIn  (_pes_2_2_io_southOut),
    .io_eastOut  (_pes_2_3_io_eastOut),
    .io_southOut (_pes_2_3_io_southOut)
  );
  PE pes_3_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_2_3_io_eastOut),
    .io_northIn  (_pes_3_2_io_southOut),
    .io_eastOut  (_pes_3_3_io_eastOut),
    .io_southOut (_pes_3_3_io_southOut)
  );
  PE pes_4_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_3_3_io_eastOut),
    .io_northIn  (_pes_4_2_io_southOut),
    .io_eastOut  (_pes_4_3_io_eastOut),
    .io_southOut (_pes_4_3_io_southOut)
  );
  PE pes_5_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_4_3_io_eastOut),
    .io_northIn  (_pes_5_2_io_southOut),
    .io_eastOut  (_pes_5_3_io_eastOut),
    .io_southOut (_pes_5_3_io_southOut)
  );
  PE pes_6_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_5_3_io_eastOut),
    .io_northIn  (_pes_6_2_io_southOut),
    .io_eastOut  (_pes_6_3_io_eastOut),
    .io_southOut (_pes_6_3_io_southOut)
  );
  PE pes_7_3 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_3_op),
    .io_westIn   (_pes_6_3_io_eastOut),
    .io_northIn  (_pes_7_2_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_7_3_io_southOut)
  );
  PE pes_0_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (io_west_4_data),
    .io_northIn  (_pes_0_3_io_southOut),
    .io_eastOut  (_pes_0_4_io_eastOut),
    .io_southOut (_pes_0_4_io_southOut)
  );
  PE pes_1_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (_pes_0_4_io_eastOut),
    .io_northIn  (_pes_1_3_io_southOut),
    .io_eastOut  (_pes_1_4_io_eastOut),
    .io_southOut (_pes_1_4_io_southOut)
  );
  PE pes_2_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (_pes_1_4_io_eastOut),
    .io_northIn  (_pes_2_3_io_southOut),
    .io_eastOut  (_pes_2_4_io_eastOut),
    .io_southOut (_pes_2_4_io_southOut)
  );
  PE pes_3_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (_pes_2_4_io_eastOut),
    .io_northIn  (_pes_3_3_io_southOut),
    .io_eastOut  (_pes_3_4_io_eastOut),
    .io_southOut (_pes_3_4_io_southOut)
  );
  PE pes_4_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (_pes_3_4_io_eastOut),
    .io_northIn  (_pes_4_3_io_southOut),
    .io_eastOut  (_pes_4_4_io_eastOut),
    .io_southOut (_pes_4_4_io_southOut)
  );
  PE pes_5_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (_pes_4_4_io_eastOut),
    .io_northIn  (_pes_5_3_io_southOut),
    .io_eastOut  (_pes_5_4_io_eastOut),
    .io_southOut (_pes_5_4_io_southOut)
  );
  PE pes_6_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (_pes_5_4_io_eastOut),
    .io_northIn  (_pes_6_3_io_southOut),
    .io_eastOut  (_pes_6_4_io_eastOut),
    .io_southOut (_pes_6_4_io_southOut)
  );
  PE pes_7_4 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_4_op),
    .io_westIn   (_pes_6_4_io_eastOut),
    .io_northIn  (_pes_7_3_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_7_4_io_southOut)
  );
  PE pes_0_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (io_west_5_data),
    .io_northIn  (_pes_0_4_io_southOut),
    .io_eastOut  (_pes_0_5_io_eastOut),
    .io_southOut (_pes_0_5_io_southOut)
  );
  PE pes_1_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (_pes_0_5_io_eastOut),
    .io_northIn  (_pes_1_4_io_southOut),
    .io_eastOut  (_pes_1_5_io_eastOut),
    .io_southOut (_pes_1_5_io_southOut)
  );
  PE pes_2_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (_pes_1_5_io_eastOut),
    .io_northIn  (_pes_2_4_io_southOut),
    .io_eastOut  (_pes_2_5_io_eastOut),
    .io_southOut (_pes_2_5_io_southOut)
  );
  PE pes_3_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (_pes_2_5_io_eastOut),
    .io_northIn  (_pes_3_4_io_southOut),
    .io_eastOut  (_pes_3_5_io_eastOut),
    .io_southOut (_pes_3_5_io_southOut)
  );
  PE pes_4_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (_pes_3_5_io_eastOut),
    .io_northIn  (_pes_4_4_io_southOut),
    .io_eastOut  (_pes_4_5_io_eastOut),
    .io_southOut (_pes_4_5_io_southOut)
  );
  PE pes_5_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (_pes_4_5_io_eastOut),
    .io_northIn  (_pes_5_4_io_southOut),
    .io_eastOut  (_pes_5_5_io_eastOut),
    .io_southOut (_pes_5_5_io_southOut)
  );
  PE pes_6_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (_pes_5_5_io_eastOut),
    .io_northIn  (_pes_6_4_io_southOut),
    .io_eastOut  (_pes_6_5_io_eastOut),
    .io_southOut (_pes_6_5_io_southOut)
  );
  PE pes_7_5 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_5_op),
    .io_westIn   (_pes_6_5_io_eastOut),
    .io_northIn  (_pes_7_4_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_7_5_io_southOut)
  );
  PE pes_0_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (io_west_6_data),
    .io_northIn  (_pes_0_5_io_southOut),
    .io_eastOut  (_pes_0_6_io_eastOut),
    .io_southOut (_pes_0_6_io_southOut)
  );
  PE pes_1_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (_pes_0_6_io_eastOut),
    .io_northIn  (_pes_1_5_io_southOut),
    .io_eastOut  (_pes_1_6_io_eastOut),
    .io_southOut (_pes_1_6_io_southOut)
  );
  PE pes_2_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (_pes_1_6_io_eastOut),
    .io_northIn  (_pes_2_5_io_southOut),
    .io_eastOut  (_pes_2_6_io_eastOut),
    .io_southOut (_pes_2_6_io_southOut)
  );
  PE pes_3_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (_pes_2_6_io_eastOut),
    .io_northIn  (_pes_3_5_io_southOut),
    .io_eastOut  (_pes_3_6_io_eastOut),
    .io_southOut (_pes_3_6_io_southOut)
  );
  PE pes_4_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (_pes_3_6_io_eastOut),
    .io_northIn  (_pes_4_5_io_southOut),
    .io_eastOut  (_pes_4_6_io_eastOut),
    .io_southOut (_pes_4_6_io_southOut)
  );
  PE pes_5_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (_pes_4_6_io_eastOut),
    .io_northIn  (_pes_5_5_io_southOut),
    .io_eastOut  (_pes_5_6_io_eastOut),
    .io_southOut (_pes_5_6_io_southOut)
  );
  PE pes_6_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (_pes_5_6_io_eastOut),
    .io_northIn  (_pes_6_5_io_southOut),
    .io_eastOut  (_pes_6_6_io_eastOut),
    .io_southOut (_pes_6_6_io_southOut)
  );
  PE pes_7_6 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_6_op),
    .io_westIn   (_pes_6_6_io_eastOut),
    .io_northIn  (_pes_7_5_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (_pes_7_6_io_southOut)
  );
  PE pes_0_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (io_west_7_data),
    .io_northIn  (_pes_0_6_io_southOut),
    .io_eastOut  (_pes_0_7_io_eastOut),
    .io_southOut (io_southRaw_0)
  );
  PE pes_1_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (_pes_0_7_io_eastOut),
    .io_northIn  (_pes_1_6_io_southOut),
    .io_eastOut  (_pes_1_7_io_eastOut),
    .io_southOut (io_southRaw_1)
  );
  PE pes_2_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (_pes_1_7_io_eastOut),
    .io_northIn  (_pes_2_6_io_southOut),
    .io_eastOut  (_pes_2_7_io_eastOut),
    .io_southOut (io_southRaw_2)
  );
  PE pes_3_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (_pes_2_7_io_eastOut),
    .io_northIn  (_pes_3_6_io_southOut),
    .io_eastOut  (_pes_3_7_io_eastOut),
    .io_southOut (io_southRaw_3)
  );
  PE pes_4_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (_pes_3_7_io_eastOut),
    .io_northIn  (_pes_4_6_io_southOut),
    .io_eastOut  (_pes_4_7_io_eastOut),
    .io_southOut (io_southRaw_4)
  );
  PE pes_5_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (_pes_4_7_io_eastOut),
    .io_northIn  (_pes_5_6_io_southOut),
    .io_eastOut  (_pes_5_7_io_eastOut),
    .io_southOut (io_southRaw_5)
  );
  PE pes_6_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (_pes_5_7_io_eastOut),
    .io_northIn  (_pes_6_6_io_southOut),
    .io_eastOut  (_pes_6_7_io_eastOut),
    .io_southOut (io_southRaw_6)
  );
  PE pes_7_7 (
    .clock       (clock),
    .reset       (reset),
    .io_westOpIn (io_west_7_op),
    .io_westIn   (_pes_6_7_io_eastOut),
    .io_northIn  (_pes_7_6_io_southOut),
    .io_eastOut  (/* unused */),
    .io_southOut (io_southRaw_7)
  );
endmodule

