// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [15:0] io_west_0_data_bits,
  input  [1:0]  io_west_1_op,
  input  [15:0] io_west_1_data_bits,
  input  [1:0]  io_west_2_op,
  input  [15:0] io_west_2_data_bits,
  input  [1:0]  io_west_3_op,
  input  [15:0] io_west_3_data_bits,
  input  [1:0]  io_west_4_op,
  input  [15:0] io_west_4_data_bits,
  input  [1:0]  io_west_5_op,
  input  [15:0] io_west_5_data_bits,
  input  [1:0]  io_west_6_op,
  input  [15:0] io_west_6_data_bits,
  input  [1:0]  io_west_7_op,
  input  [15:0] io_west_7_data_bits,
                io_north_0_bits,
                io_north_1_bits,
                io_north_2_bits,
                io_north_3_bits,
                io_north_4_bits,
                io_north_5_bits,
                io_north_6_bits,
                io_north_7_bits,
  output [15:0] io_southRaw_0_bits,
                io_southRaw_1_bits,
                io_southRaw_2_bits,
                io_southRaw_3_bits,
                io_southRaw_4_bits,
                io_southRaw_5_bits,
                io_southRaw_6_bits,
                io_southRaw_7_bits
);

  wire [15:0] _pes_6_7_io_eastOut_bits;
  wire [15:0] _pes_5_7_io_eastOut_bits;
  wire [15:0] _pes_4_7_io_eastOut_bits;
  wire [15:0] _pes_3_7_io_eastOut_bits;
  wire [15:0] _pes_2_7_io_eastOut_bits;
  wire [15:0] _pes_1_7_io_eastOut_bits;
  wire [15:0] _pes_0_7_io_eastOut_bits;
  wire [15:0] _pes_7_6_io_southOut_bits;
  wire [15:0] _pes_6_6_io_eastOut_bits;
  wire [15:0] _pes_6_6_io_southOut_bits;
  wire [15:0] _pes_5_6_io_eastOut_bits;
  wire [15:0] _pes_5_6_io_southOut_bits;
  wire [15:0] _pes_4_6_io_eastOut_bits;
  wire [15:0] _pes_4_6_io_southOut_bits;
  wire [15:0] _pes_3_6_io_eastOut_bits;
  wire [15:0] _pes_3_6_io_southOut_bits;
  wire [15:0] _pes_2_6_io_eastOut_bits;
  wire [15:0] _pes_2_6_io_southOut_bits;
  wire [15:0] _pes_1_6_io_eastOut_bits;
  wire [15:0] _pes_1_6_io_southOut_bits;
  wire [15:0] _pes_0_6_io_eastOut_bits;
  wire [15:0] _pes_0_6_io_southOut_bits;
  wire [15:0] _pes_7_5_io_southOut_bits;
  wire [15:0] _pes_6_5_io_eastOut_bits;
  wire [15:0] _pes_6_5_io_southOut_bits;
  wire [15:0] _pes_5_5_io_eastOut_bits;
  wire [15:0] _pes_5_5_io_southOut_bits;
  wire [15:0] _pes_4_5_io_eastOut_bits;
  wire [15:0] _pes_4_5_io_southOut_bits;
  wire [15:0] _pes_3_5_io_eastOut_bits;
  wire [15:0] _pes_3_5_io_southOut_bits;
  wire [15:0] _pes_2_5_io_eastOut_bits;
  wire [15:0] _pes_2_5_io_southOut_bits;
  wire [15:0] _pes_1_5_io_eastOut_bits;
  wire [15:0] _pes_1_5_io_southOut_bits;
  wire [15:0] _pes_0_5_io_eastOut_bits;
  wire [15:0] _pes_0_5_io_southOut_bits;
  wire [15:0] _pes_7_4_io_southOut_bits;
  wire [15:0] _pes_6_4_io_eastOut_bits;
  wire [15:0] _pes_6_4_io_southOut_bits;
  wire [15:0] _pes_5_4_io_eastOut_bits;
  wire [15:0] _pes_5_4_io_southOut_bits;
  wire [15:0] _pes_4_4_io_eastOut_bits;
  wire [15:0] _pes_4_4_io_southOut_bits;
  wire [15:0] _pes_3_4_io_eastOut_bits;
  wire [15:0] _pes_3_4_io_southOut_bits;
  wire [15:0] _pes_2_4_io_eastOut_bits;
  wire [15:0] _pes_2_4_io_southOut_bits;
  wire [15:0] _pes_1_4_io_eastOut_bits;
  wire [15:0] _pes_1_4_io_southOut_bits;
  wire [15:0] _pes_0_4_io_eastOut_bits;
  wire [15:0] _pes_0_4_io_southOut_bits;
  wire [15:0] _pes_7_3_io_southOut_bits;
  wire [15:0] _pes_6_3_io_eastOut_bits;
  wire [15:0] _pes_6_3_io_southOut_bits;
  wire [15:0] _pes_5_3_io_eastOut_bits;
  wire [15:0] _pes_5_3_io_southOut_bits;
  wire [15:0] _pes_4_3_io_eastOut_bits;
  wire [15:0] _pes_4_3_io_southOut_bits;
  wire [15:0] _pes_3_3_io_eastOut_bits;
  wire [15:0] _pes_3_3_io_southOut_bits;
  wire [15:0] _pes_2_3_io_eastOut_bits;
  wire [15:0] _pes_2_3_io_southOut_bits;
  wire [15:0] _pes_1_3_io_eastOut_bits;
  wire [15:0] _pes_1_3_io_southOut_bits;
  wire [15:0] _pes_0_3_io_eastOut_bits;
  wire [15:0] _pes_0_3_io_southOut_bits;
  wire [15:0] _pes_7_2_io_southOut_bits;
  wire [15:0] _pes_6_2_io_eastOut_bits;
  wire [15:0] _pes_6_2_io_southOut_bits;
  wire [15:0] _pes_5_2_io_eastOut_bits;
  wire [15:0] _pes_5_2_io_southOut_bits;
  wire [15:0] _pes_4_2_io_eastOut_bits;
  wire [15:0] _pes_4_2_io_southOut_bits;
  wire [15:0] _pes_3_2_io_eastOut_bits;
  wire [15:0] _pes_3_2_io_southOut_bits;
  wire [15:0] _pes_2_2_io_eastOut_bits;
  wire [15:0] _pes_2_2_io_southOut_bits;
  wire [15:0] _pes_1_2_io_eastOut_bits;
  wire [15:0] _pes_1_2_io_southOut_bits;
  wire [15:0] _pes_0_2_io_eastOut_bits;
  wire [15:0] _pes_0_2_io_southOut_bits;
  wire [15:0] _pes_7_1_io_southOut_bits;
  wire [15:0] _pes_6_1_io_eastOut_bits;
  wire [15:0] _pes_6_1_io_southOut_bits;
  wire [15:0] _pes_5_1_io_eastOut_bits;
  wire [15:0] _pes_5_1_io_southOut_bits;
  wire [15:0] _pes_4_1_io_eastOut_bits;
  wire [15:0] _pes_4_1_io_southOut_bits;
  wire [15:0] _pes_3_1_io_eastOut_bits;
  wire [15:0] _pes_3_1_io_southOut_bits;
  wire [15:0] _pes_2_1_io_eastOut_bits;
  wire [15:0] _pes_2_1_io_southOut_bits;
  wire [15:0] _pes_1_1_io_eastOut_bits;
  wire [15:0] _pes_1_1_io_southOut_bits;
  wire [15:0] _pes_0_1_io_eastOut_bits;
  wire [15:0] _pes_0_1_io_southOut_bits;
  wire [15:0] _pes_7_io_southOut_bits;
  wire [15:0] _pes_6_io_eastOut_bits;
  wire [15:0] _pes_6_io_southOut_bits;
  wire [15:0] _pes_5_io_eastOut_bits;
  wire [15:0] _pes_5_io_southOut_bits;
  wire [15:0] _pes_4_io_eastOut_bits;
  wire [15:0] _pes_4_io_southOut_bits;
  wire [15:0] _pes_3_io_eastOut_bits;
  wire [15:0] _pes_3_io_southOut_bits;
  wire [15:0] _pes_2_io_eastOut_bits;
  wire [15:0] _pes_2_io_southOut_bits;
  wire [15:0] _pes_1_io_eastOut_bits;
  wire [15:0] _pes_1_io_southOut_bits;
  wire [15:0] _pes_0_io_eastOut_bits;
  wire [15:0] _pes_0_io_southOut_bits;
  PE pes_0 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (io_west_0_data_bits),
    .io_northIn_bits  (io_north_0_bits),
    .io_eastOut_bits  (_pes_0_io_eastOut_bits),
    .io_southOut_bits (_pes_0_io_southOut_bits)
  );
  PE pes_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_0_io_eastOut_bits),
    .io_northIn_bits  (io_north_1_bits),
    .io_eastOut_bits  (_pes_1_io_eastOut_bits),
    .io_southOut_bits (_pes_1_io_southOut_bits)
  );
  PE pes_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_1_io_eastOut_bits),
    .io_northIn_bits  (io_north_2_bits),
    .io_eastOut_bits  (_pes_2_io_eastOut_bits),
    .io_southOut_bits (_pes_2_io_southOut_bits)
  );
  PE pes_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_2_io_eastOut_bits),
    .io_northIn_bits  (io_north_3_bits),
    .io_eastOut_bits  (_pes_3_io_eastOut_bits),
    .io_southOut_bits (_pes_3_io_southOut_bits)
  );
  PE pes_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_3_io_eastOut_bits),
    .io_northIn_bits  (io_north_4_bits),
    .io_eastOut_bits  (_pes_4_io_eastOut_bits),
    .io_southOut_bits (_pes_4_io_southOut_bits)
  );
  PE pes_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_4_io_eastOut_bits),
    .io_northIn_bits  (io_north_5_bits),
    .io_eastOut_bits  (_pes_5_io_eastOut_bits),
    .io_southOut_bits (_pes_5_io_southOut_bits)
  );
  PE pes_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_5_io_eastOut_bits),
    .io_northIn_bits  (io_north_6_bits),
    .io_eastOut_bits  (_pes_6_io_eastOut_bits),
    .io_southOut_bits (_pes_6_io_southOut_bits)
  );
  PE pes_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_6_io_eastOut_bits),
    .io_northIn_bits  (io_north_7_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_7_io_southOut_bits)
  );
  PE pes_0_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (io_west_1_data_bits),
    .io_northIn_bits  (_pes_0_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_1_io_eastOut_bits),
    .io_southOut_bits (_pes_0_1_io_southOut_bits)
  );
  PE pes_1_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_0_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_1_io_eastOut_bits),
    .io_southOut_bits (_pes_1_1_io_southOut_bits)
  );
  PE pes_2_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_1_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_1_io_eastOut_bits),
    .io_southOut_bits (_pes_2_1_io_southOut_bits)
  );
  PE pes_3_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_2_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_1_io_eastOut_bits),
    .io_southOut_bits (_pes_3_1_io_southOut_bits)
  );
  PE pes_4_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_3_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_1_io_eastOut_bits),
    .io_southOut_bits (_pes_4_1_io_southOut_bits)
  );
  PE pes_5_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_4_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_1_io_eastOut_bits),
    .io_southOut_bits (_pes_5_1_io_southOut_bits)
  );
  PE pes_6_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_5_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_1_io_eastOut_bits),
    .io_southOut_bits (_pes_6_1_io_southOut_bits)
  );
  PE pes_7_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_6_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_7_1_io_southOut_bits)
  );
  PE pes_0_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (io_west_2_data_bits),
    .io_northIn_bits  (_pes_0_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_2_io_eastOut_bits),
    .io_southOut_bits (_pes_0_2_io_southOut_bits)
  );
  PE pes_1_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_0_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_2_io_eastOut_bits),
    .io_southOut_bits (_pes_1_2_io_southOut_bits)
  );
  PE pes_2_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_1_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_2_io_eastOut_bits),
    .io_southOut_bits (_pes_2_2_io_southOut_bits)
  );
  PE pes_3_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_2_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_2_io_eastOut_bits),
    .io_southOut_bits (_pes_3_2_io_southOut_bits)
  );
  PE pes_4_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_3_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_2_io_eastOut_bits),
    .io_southOut_bits (_pes_4_2_io_southOut_bits)
  );
  PE pes_5_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_4_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_2_io_eastOut_bits),
    .io_southOut_bits (_pes_5_2_io_southOut_bits)
  );
  PE pes_6_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_5_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_2_io_eastOut_bits),
    .io_southOut_bits (_pes_6_2_io_southOut_bits)
  );
  PE pes_7_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_6_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_1_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_7_2_io_southOut_bits)
  );
  PE pes_0_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (io_west_3_data_bits),
    .io_northIn_bits  (_pes_0_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_3_io_eastOut_bits),
    .io_southOut_bits (_pes_0_3_io_southOut_bits)
  );
  PE pes_1_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_0_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_3_io_eastOut_bits),
    .io_southOut_bits (_pes_1_3_io_southOut_bits)
  );
  PE pes_2_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_1_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_3_io_eastOut_bits),
    .io_southOut_bits (_pes_2_3_io_southOut_bits)
  );
  PE pes_3_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_2_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_3_io_eastOut_bits),
    .io_southOut_bits (_pes_3_3_io_southOut_bits)
  );
  PE pes_4_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_3_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_3_io_eastOut_bits),
    .io_southOut_bits (_pes_4_3_io_southOut_bits)
  );
  PE pes_5_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_4_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_3_io_eastOut_bits),
    .io_southOut_bits (_pes_5_3_io_southOut_bits)
  );
  PE pes_6_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_5_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_3_io_eastOut_bits),
    .io_southOut_bits (_pes_6_3_io_southOut_bits)
  );
  PE pes_7_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_6_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_2_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_7_3_io_southOut_bits)
  );
  PE pes_0_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (io_west_4_data_bits),
    .io_northIn_bits  (_pes_0_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_4_io_eastOut_bits),
    .io_southOut_bits (_pes_0_4_io_southOut_bits)
  );
  PE pes_1_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_0_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_4_io_eastOut_bits),
    .io_southOut_bits (_pes_1_4_io_southOut_bits)
  );
  PE pes_2_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_1_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_4_io_eastOut_bits),
    .io_southOut_bits (_pes_2_4_io_southOut_bits)
  );
  PE pes_3_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_2_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_4_io_eastOut_bits),
    .io_southOut_bits (_pes_3_4_io_southOut_bits)
  );
  PE pes_4_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_3_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_4_io_eastOut_bits),
    .io_southOut_bits (_pes_4_4_io_southOut_bits)
  );
  PE pes_5_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_4_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_4_io_eastOut_bits),
    .io_southOut_bits (_pes_5_4_io_southOut_bits)
  );
  PE pes_6_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_5_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_4_io_eastOut_bits),
    .io_southOut_bits (_pes_6_4_io_southOut_bits)
  );
  PE pes_7_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_6_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_3_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_7_4_io_southOut_bits)
  );
  PE pes_0_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (io_west_5_data_bits),
    .io_northIn_bits  (_pes_0_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_5_io_eastOut_bits),
    .io_southOut_bits (_pes_0_5_io_southOut_bits)
  );
  PE pes_1_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_0_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_5_io_eastOut_bits),
    .io_southOut_bits (_pes_1_5_io_southOut_bits)
  );
  PE pes_2_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_1_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_5_io_eastOut_bits),
    .io_southOut_bits (_pes_2_5_io_southOut_bits)
  );
  PE pes_3_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_2_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_5_io_eastOut_bits),
    .io_southOut_bits (_pes_3_5_io_southOut_bits)
  );
  PE pes_4_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_3_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_5_io_eastOut_bits),
    .io_southOut_bits (_pes_4_5_io_southOut_bits)
  );
  PE pes_5_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_4_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_5_io_eastOut_bits),
    .io_southOut_bits (_pes_5_5_io_southOut_bits)
  );
  PE pes_6_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_5_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_5_io_eastOut_bits),
    .io_southOut_bits (_pes_6_5_io_southOut_bits)
  );
  PE pes_7_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_6_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_4_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_7_5_io_southOut_bits)
  );
  PE pes_0_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (io_west_6_data_bits),
    .io_northIn_bits  (_pes_0_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_6_io_eastOut_bits),
    .io_southOut_bits (_pes_0_6_io_southOut_bits)
  );
  PE pes_1_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_0_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_6_io_eastOut_bits),
    .io_southOut_bits (_pes_1_6_io_southOut_bits)
  );
  PE pes_2_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_1_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_6_io_eastOut_bits),
    .io_southOut_bits (_pes_2_6_io_southOut_bits)
  );
  PE pes_3_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_2_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_6_io_eastOut_bits),
    .io_southOut_bits (_pes_3_6_io_southOut_bits)
  );
  PE pes_4_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_3_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_6_io_eastOut_bits),
    .io_southOut_bits (_pes_4_6_io_southOut_bits)
  );
  PE pes_5_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_4_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_6_io_eastOut_bits),
    .io_southOut_bits (_pes_5_6_io_southOut_bits)
  );
  PE pes_6_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_5_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_6_io_eastOut_bits),
    .io_southOut_bits (_pes_6_6_io_southOut_bits)
  );
  PE pes_7_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_6_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_5_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_7_6_io_southOut_bits)
  );
  PE pes_0_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (io_west_7_data_bits),
    .io_northIn_bits  (_pes_0_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_7_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_0_bits)
  );
  PE pes_1_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_0_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_7_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_1_bits)
  );
  PE pes_2_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_1_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_7_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_2_bits)
  );
  PE pes_3_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_2_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_7_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_3_bits)
  );
  PE pes_4_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_3_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_7_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_4_bits)
  );
  PE pes_5_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_4_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_7_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_5_bits)
  );
  PE pes_6_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_5_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_7_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_6_bits)
  );
  PE pes_7_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_6_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_6_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (io_southRaw_7_bits)
  );
endmodule

