// Generated by CIRCT firtool-1.140.0
module RecFNToRecFN(
  input  [16:0] io_in,
  output [8:0]  io_out
);

  wire rawIn_isNaN = (&(io_in[15:14])) & io_in[13];
  RoundAnyRawFNToRecFN_ie5_is11_oe5_os3 roundAnyRawFNToRecFN (
    .io_invalidExc (rawIn_isNaN & ~(io_in[9])),
    .io_in_isNaN   (rawIn_isNaN),
    .io_in_isInf   ((&(io_in[15:14])) & ~(io_in[13])),
    .io_in_isZero  (~(|(io_in[15:13]))),
    .io_in_sign    (io_in[16]),
    .io_in_sExp    ({1'h0, io_in[15:10]}),
    .io_in_sig     ({1'h0, |(io_in[15:13]), io_in[9:0]}),
    .io_out        (io_out)
  );
endmodule

