// Generated by CIRCT firtool-1.140.0
module OneSaPEComputation(
  input         clock,
                reset,
  input  [1:0]  io_op,
  input  [7:0]  io_westIn_lanes_0_bits,
                io_westIn_lanes_1_bits,
                io_northIn_lanes_0_bits,
                io_northIn_lanes_1_bits,
  input  [15:0] io_psumIn_bits,
  output [7:0]  io_eastOut_lanes_0_bits,
                io_eastOut_lanes_1_bits,
  output [15:0] io_psumOut_bits,
                io_diagPairsOut_0_bits
);

  wire [15:0] _regPsum_mac_z;
  wire [15:0] _sharedPairs_pairs_adder_z;
  wire [15:0] _sharedPairs_products_mult_1_z;
  wire [15:0] _sharedPairs_products_mult_z;
  reg  [7:0]  regEast_lanes_0_bits;
  reg  [7:0]  regEast_lanes_1_bits;
  reg  [15:0] regPsum_bits;
  reg  [7:0]  regWeight_lanes_0_bits;
  reg  [7:0]  regWeight_lanes_1_bits;
  reg  [15:0] regSharedPairs_0_bits;
  wire        _sharedMacRhs_T = io_op == 2'h2;
  always @(posedge clock) begin
    if (reset) begin
      regEast_lanes_0_bits <= 8'h0;
      regEast_lanes_1_bits <= 8'h0;
      regPsum_bits <= 16'h0;
      regWeight_lanes_0_bits <= 8'h0;
      regWeight_lanes_1_bits <= 8'h0;
      regSharedPairs_0_bits <= 16'h0;
    end
    else begin
      automatic logic _GEN = io_op == 2'h1;
      automatic logic _GEN_0 = io_op == 2'h2;
      automatic logic _GEN_1 = _GEN | _GEN_0;
      regEast_lanes_0_bits <= _GEN_1 ? io_westIn_lanes_0_bits : 8'h0;
      regEast_lanes_1_bits <= _GEN_1 ? io_westIn_lanes_1_bits : 8'h0;
      regPsum_bits <= _GEN ? io_psumIn_bits : _GEN_0 ? _regPsum_mac_z : 16'h0;
      if (_GEN) begin
        regWeight_lanes_0_bits <= io_westIn_lanes_0_bits;
        regWeight_lanes_1_bits <= io_westIn_lanes_1_bits;
      end
      if (_GEN | ~_GEN_0) begin
      end
      else
        regSharedPairs_0_bits <= _sharedPairs_pairs_adder_z;
    end
  end // always @(posedge)
  DW_fp_mult #(
    .en_ubr_flag(0),
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) sharedPairs_products_mult (
    .a      ({io_westIn_lanes_0_bits, 8'h0}),
    .b      ({_sharedMacRhs_T ? regWeight_lanes_0_bits : io_northIn_lanes_0_bits, 8'h0}),
    .rnd    (3'h0),
    .z      (_sharedPairs_products_mult_z),
    .status (/* unused */)
  );
  DW_fp_mult #(
    .en_ubr_flag(0),
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) sharedPairs_products_mult_1 (
    .a      ({io_westIn_lanes_1_bits, 8'h0}),
    .b      ({_sharedMacRhs_T ? regWeight_lanes_1_bits : io_northIn_lanes_1_bits, 8'h0}),
    .rnd    (3'h0),
    .z      (_sharedPairs_products_mult_1_z),
    .status (/* unused */)
  );
  DW_fp_add #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) sharedPairs_pairs_adder (
    .a      (_sharedPairs_products_mult_z),
    .b      (_sharedPairs_products_mult_1_z),
    .rnd    (3'h0),
    .z      (_sharedPairs_pairs_adder_z),
    .status (/* unused */)
  );
  DW_fp_mac #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) regPsum_mac (
    .a      (regSharedPairs_0_bits),
    .b      (16'h3C00),
    .c      (io_psumIn_bits),
    .rnd    (3'h0),
    .z      (_regPsum_mac_z),
    .status (/* unused */)
  );
  assign io_eastOut_lanes_0_bits = regEast_lanes_0_bits;
  assign io_eastOut_lanes_1_bits = regEast_lanes_1_bits;
  assign io_psumOut_bits = regPsum_bits;
  assign io_diagPairsOut_0_bits = (&io_op) ? _sharedPairs_pairs_adder_z : 16'h0;
endmodule

