// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [7:0]  io_west_0_data,
  input  [1:0]  io_west_1_op,
  input  [7:0]  io_west_1_data,
  input  [1:0]  io_west_2_op,
  input  [7:0]  io_west_2_data,
  input  [1:0]  io_west_3_op,
  input  [7:0]  io_west_3_data,
  input  [1:0]  io_west_4_op,
  input  [7:0]  io_west_4_data,
  input  [1:0]  io_west_5_op,
  input  [7:0]  io_west_5_data,
  input  [1:0]  io_west_6_op,
  input  [7:0]  io_west_6_data,
  input  [1:0]  io_west_7_op,
  input  [7:0]  io_west_7_data,
  input         io_stripNorth_0_0_op,
  input  [31:0] io_stripNorth_0_0_data,
  input         io_stripNorth_0_1_op,
  input  [31:0] io_stripNorth_0_1_data,
  input         io_stripNorth_0_2_op,
  input  [31:0] io_stripNorth_0_2_data,
  input         io_stripNorth_0_3_op,
  input  [31:0] io_stripNorth_0_3_data,
  input         io_stripNorth_1_0_op,
  input  [31:0] io_stripNorth_1_0_data,
  input         io_stripNorth_1_1_op,
  input  [31:0] io_stripNorth_1_1_data,
  input         io_stripNorth_1_2_op,
  input  [31:0] io_stripNorth_1_2_data,
  input         io_stripNorth_1_3_op,
  input  [31:0] io_stripNorth_1_3_data,
  input         io_stripNorth_2_0_op,
  input  [31:0] io_stripNorth_2_0_data,
  input         io_stripNorth_2_1_op,
  input  [31:0] io_stripNorth_2_1_data,
  input         io_stripNorth_2_2_op,
  input  [31:0] io_stripNorth_2_2_data,
  input         io_stripNorth_2_3_op,
  input  [31:0] io_stripNorth_2_3_data,
  input         io_stripNorth_3_0_op,
  input  [31:0] io_stripNorth_3_0_data,
  input         io_stripNorth_3_1_op,
  input  [31:0] io_stripNorth_3_1_data,
  input         io_stripNorth_3_2_op,
  input  [31:0] io_stripNorth_3_2_data,
  input         io_stripNorth_3_3_op,
  input  [31:0] io_stripNorth_3_3_data,
  input         io_stripNorth_4_0_op,
  input  [31:0] io_stripNorth_4_0_data,
  input         io_stripNorth_4_1_op,
  input  [31:0] io_stripNorth_4_1_data,
  input         io_stripNorth_4_2_op,
  input  [31:0] io_stripNorth_4_2_data,
  input         io_stripNorth_4_3_op,
  input  [31:0] io_stripNorth_4_3_data,
  input         io_stripNorth_5_0_op,
  input  [31:0] io_stripNorth_5_0_data,
  input         io_stripNorth_5_1_op,
  input  [31:0] io_stripNorth_5_1_data,
  input         io_stripNorth_5_2_op,
  input  [31:0] io_stripNorth_5_2_data,
  input         io_stripNorth_5_3_op,
  input  [31:0] io_stripNorth_5_3_data,
  input         io_stripNorth_6_0_op,
  input  [31:0] io_stripNorth_6_0_data,
  input         io_stripNorth_6_1_op,
  input  [31:0] io_stripNorth_6_1_data,
  input         io_stripNorth_6_2_op,
  input  [31:0] io_stripNorth_6_2_data,
  input         io_stripNorth_6_3_op,
  input  [31:0] io_stripNorth_6_3_data,
  input         io_stripNorth_7_0_op,
  input  [31:0] io_stripNorth_7_0_data,
  input         io_stripNorth_7_1_op,
  input  [31:0] io_stripNorth_7_1_data,
  input         io_stripNorth_7_2_op,
  input  [31:0] io_stripNorth_7_2_data,
  input         io_stripNorth_7_3_op,
  input  [31:0] io_stripNorth_7_3_data,
  output [31:0] io_gemmSouthRaw_0,
                io_gemmSouthRaw_1,
                io_gemmSouthRaw_2,
                io_gemmSouthRaw_3,
                io_gemmSouthRaw_4,
                io_gemmSouthRaw_5,
                io_gemmSouthRaw_6,
                io_gemmSouthRaw_7,
                io_pinnSouthRaw_0,
                io_pinnSouthRaw_1,
                io_pinnSouthRaw_2,
                io_pinnSouthRaw_3,
                io_pinnSouthRaw_4,
                io_pinnSouthRaw_5,
                io_pinnSouthRaw_6,
                io_pinnSouthRaw_7
);

  wire [31:0] _pairs_3_7_io_southOut_1;
  wire [7:0]  _pairs_2_7_io_eastOut;
  wire [31:0] _pairs_2_7_io_southOut_1;
  wire [7:0]  _pairs_1_7_io_eastOut;
  wire [31:0] _pairs_1_7_io_southOut_1;
  wire [7:0]  _pairs_0_7_io_eastOut;
  wire [31:0] _pairs_0_7_io_southOut_1;
  wire [31:0] _pairs_3_6_io_southOut_0;
  wire [31:0] _pairs_3_6_io_southOut_1;
  wire [7:0]  _pairs_2_6_io_eastOut;
  wire [31:0] _pairs_2_6_io_southOut_0;
  wire [31:0] _pairs_2_6_io_southOut_1;
  wire [7:0]  _pairs_1_6_io_eastOut;
  wire [31:0] _pairs_1_6_io_southOut_0;
  wire [31:0] _pairs_1_6_io_southOut_1;
  wire [7:0]  _pairs_0_6_io_eastOut;
  wire [31:0] _pairs_0_6_io_southOut_0;
  wire [31:0] _pairs_0_6_io_southOut_1;
  wire [31:0] _pairs_3_5_io_southOut_0;
  wire [31:0] _pairs_3_5_io_southOut_1;
  wire [7:0]  _pairs_2_5_io_eastOut;
  wire [31:0] _pairs_2_5_io_southOut_0;
  wire [31:0] _pairs_2_5_io_southOut_1;
  wire [7:0]  _pairs_1_5_io_eastOut;
  wire [31:0] _pairs_1_5_io_southOut_0;
  wire [31:0] _pairs_1_5_io_southOut_1;
  wire [7:0]  _pairs_0_5_io_eastOut;
  wire [31:0] _pairs_0_5_io_southOut_0;
  wire [31:0] _pairs_0_5_io_southOut_1;
  wire [31:0] _pairs_3_4_io_southOut_0;
  wire [31:0] _pairs_3_4_io_southOut_1;
  wire [7:0]  _pairs_2_4_io_eastOut;
  wire [31:0] _pairs_2_4_io_southOut_0;
  wire [31:0] _pairs_2_4_io_southOut_1;
  wire [7:0]  _pairs_1_4_io_eastOut;
  wire [31:0] _pairs_1_4_io_southOut_0;
  wire [31:0] _pairs_1_4_io_southOut_1;
  wire [7:0]  _pairs_0_4_io_eastOut;
  wire [31:0] _pairs_0_4_io_southOut_0;
  wire [31:0] _pairs_0_4_io_southOut_1;
  wire [31:0] _pairs_3_3_io_southOut_0;
  wire [31:0] _pairs_3_3_io_southOut_1;
  wire [7:0]  _pairs_2_3_io_eastOut;
  wire [31:0] _pairs_2_3_io_southOut_0;
  wire [31:0] _pairs_2_3_io_southOut_1;
  wire [7:0]  _pairs_1_3_io_eastOut;
  wire [31:0] _pairs_1_3_io_southOut_0;
  wire [31:0] _pairs_1_3_io_southOut_1;
  wire [7:0]  _pairs_0_3_io_eastOut;
  wire [31:0] _pairs_0_3_io_southOut_0;
  wire [31:0] _pairs_0_3_io_southOut_1;
  wire [31:0] _pairs_3_2_io_southOut_0;
  wire [31:0] _pairs_3_2_io_southOut_1;
  wire [7:0]  _pairs_2_2_io_eastOut;
  wire [31:0] _pairs_2_2_io_southOut_0;
  wire [31:0] _pairs_2_2_io_southOut_1;
  wire [7:0]  _pairs_1_2_io_eastOut;
  wire [31:0] _pairs_1_2_io_southOut_0;
  wire [31:0] _pairs_1_2_io_southOut_1;
  wire [7:0]  _pairs_0_2_io_eastOut;
  wire [31:0] _pairs_0_2_io_southOut_0;
  wire [31:0] _pairs_0_2_io_southOut_1;
  wire [31:0] _pairs_3_1_io_southOut_0;
  wire [31:0] _pairs_3_1_io_southOut_1;
  wire [7:0]  _pairs_2_1_io_eastOut;
  wire [31:0] _pairs_2_1_io_southOut_0;
  wire [31:0] _pairs_2_1_io_southOut_1;
  wire [7:0]  _pairs_1_1_io_eastOut;
  wire [31:0] _pairs_1_1_io_southOut_0;
  wire [31:0] _pairs_1_1_io_southOut_1;
  wire [7:0]  _pairs_0_1_io_eastOut;
  wire [31:0] _pairs_0_1_io_southOut_0;
  wire [31:0] _pairs_0_1_io_southOut_1;
  wire [31:0] _pairs_3_io_southOut_0;
  wire [31:0] _pairs_3_io_southOut_1;
  wire [7:0]  _pairs_2_io_eastOut;
  wire [31:0] _pairs_2_io_southOut_0;
  wire [31:0] _pairs_2_io_southOut_1;
  wire [7:0]  _pairs_1_io_eastOut;
  wire [31:0] _pairs_1_io_southOut_0;
  wire [31:0] _pairs_1_io_southOut_1;
  wire [7:0]  _pairs_0_io_eastOut;
  wire [31:0] _pairs_0_io_southOut_0;
  wire [31:0] _pairs_0_io_southOut_1;
  StripPair pairs_0 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_0_op),
    .io_westIn     (io_west_0_data),
    .io_northOpIn  (io_stripNorth_0_0_op),
    .io_northIn_0  (io_stripNorth_0_0_op ? io_stripNorth_0_0_data : 32'h0),
    .io_northIn_1  (32'h0),
    .io_eastOut    (_pairs_0_io_eastOut),
    .io_southOut_0 (_pairs_0_io_southOut_0),
    .io_southOut_1 (_pairs_0_io_southOut_1)
  );
  StripPair pairs_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_0_op),
    .io_westIn     (_pairs_0_io_eastOut),
    .io_northOpIn  (io_stripNorth_0_1_op),
    .io_northIn_0  (io_stripNorth_0_1_op ? io_stripNorth_0_1_data : 32'h0),
    .io_northIn_1  (32'h0),
    .io_eastOut    (_pairs_1_io_eastOut),
    .io_southOut_0 (_pairs_1_io_southOut_0),
    .io_southOut_1 (_pairs_1_io_southOut_1)
  );
  StripPair pairs_2 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_0_op),
    .io_westIn     (_pairs_1_io_eastOut),
    .io_northOpIn  (io_stripNorth_0_2_op),
    .io_northIn_0  (io_stripNorth_0_2_op ? io_stripNorth_0_2_data : 32'h0),
    .io_northIn_1  (32'h0),
    .io_eastOut    (_pairs_2_io_eastOut),
    .io_southOut_0 (_pairs_2_io_southOut_0),
    .io_southOut_1 (_pairs_2_io_southOut_1)
  );
  StripPair pairs_3 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_0_op),
    .io_westIn     (_pairs_2_io_eastOut),
    .io_northOpIn  (io_stripNorth_0_3_op),
    .io_northIn_0  (io_stripNorth_0_3_op ? io_stripNorth_0_3_data : 32'h0),
    .io_northIn_1  (32'h0),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_3_io_southOut_0),
    .io_southOut_1 (_pairs_3_io_southOut_1)
  );
  StripPair pairs_0_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_1_op),
    .io_westIn     (io_west_1_data),
    .io_northOpIn  (io_stripNorth_1_0_op),
    .io_northIn_0  (_pairs_0_io_southOut_0),
    .io_northIn_1  (_pairs_0_io_southOut_1),
    .io_eastOut    (_pairs_0_1_io_eastOut),
    .io_southOut_0 (_pairs_0_1_io_southOut_0),
    .io_southOut_1 (_pairs_0_1_io_southOut_1)
  );
  StripPair pairs_1_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_1_op),
    .io_westIn     (_pairs_0_1_io_eastOut),
    .io_northOpIn  (io_stripNorth_1_1_op),
    .io_northIn_0  (_pairs_1_io_southOut_0),
    .io_northIn_1  (_pairs_1_io_southOut_1),
    .io_eastOut    (_pairs_1_1_io_eastOut),
    .io_southOut_0 (_pairs_1_1_io_southOut_0),
    .io_southOut_1 (_pairs_1_1_io_southOut_1)
  );
  StripPair pairs_2_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_1_op),
    .io_westIn     (_pairs_1_1_io_eastOut),
    .io_northOpIn  (io_stripNorth_1_2_op),
    .io_northIn_0  (_pairs_2_io_southOut_0),
    .io_northIn_1  (_pairs_2_io_southOut_1),
    .io_eastOut    (_pairs_2_1_io_eastOut),
    .io_southOut_0 (_pairs_2_1_io_southOut_0),
    .io_southOut_1 (_pairs_2_1_io_southOut_1)
  );
  StripPair pairs_3_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_1_op),
    .io_westIn     (_pairs_2_1_io_eastOut),
    .io_northOpIn  (io_stripNorth_1_3_op),
    .io_northIn_0  (_pairs_3_io_southOut_0),
    .io_northIn_1  (_pairs_3_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_3_1_io_southOut_0),
    .io_southOut_1 (_pairs_3_1_io_southOut_1)
  );
  StripPair pairs_0_2 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_2_op),
    .io_westIn     (io_west_2_data),
    .io_northOpIn  (io_stripNorth_2_0_op),
    .io_northIn_0  (_pairs_0_1_io_southOut_0),
    .io_northIn_1  (_pairs_0_1_io_southOut_1),
    .io_eastOut    (_pairs_0_2_io_eastOut),
    .io_southOut_0 (_pairs_0_2_io_southOut_0),
    .io_southOut_1 (_pairs_0_2_io_southOut_1)
  );
  StripPair pairs_1_2 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_2_op),
    .io_westIn     (_pairs_0_2_io_eastOut),
    .io_northOpIn  (io_stripNorth_2_1_op),
    .io_northIn_0  (_pairs_1_1_io_southOut_0),
    .io_northIn_1  (_pairs_1_1_io_southOut_1),
    .io_eastOut    (_pairs_1_2_io_eastOut),
    .io_southOut_0 (_pairs_1_2_io_southOut_0),
    .io_southOut_1 (_pairs_1_2_io_southOut_1)
  );
  StripPair pairs_2_2 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_2_op),
    .io_westIn     (_pairs_1_2_io_eastOut),
    .io_northOpIn  (io_stripNorth_2_2_op),
    .io_northIn_0  (_pairs_2_1_io_southOut_0),
    .io_northIn_1  (_pairs_2_1_io_southOut_1),
    .io_eastOut    (_pairs_2_2_io_eastOut),
    .io_southOut_0 (_pairs_2_2_io_southOut_0),
    .io_southOut_1 (_pairs_2_2_io_southOut_1)
  );
  StripPair pairs_3_2 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_2_op),
    .io_westIn     (_pairs_2_2_io_eastOut),
    .io_northOpIn  (io_stripNorth_2_3_op),
    .io_northIn_0  (_pairs_3_1_io_southOut_0),
    .io_northIn_1  (_pairs_3_1_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_3_2_io_southOut_0),
    .io_southOut_1 (_pairs_3_2_io_southOut_1)
  );
  StripPair pairs_0_3 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_3_op),
    .io_westIn     (io_west_3_data),
    .io_northOpIn  (io_stripNorth_3_0_op),
    .io_northIn_0  (_pairs_0_2_io_southOut_0),
    .io_northIn_1  (_pairs_0_2_io_southOut_1),
    .io_eastOut    (_pairs_0_3_io_eastOut),
    .io_southOut_0 (_pairs_0_3_io_southOut_0),
    .io_southOut_1 (_pairs_0_3_io_southOut_1)
  );
  StripPair pairs_1_3 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_3_op),
    .io_westIn     (_pairs_0_3_io_eastOut),
    .io_northOpIn  (io_stripNorth_3_1_op),
    .io_northIn_0  (_pairs_1_2_io_southOut_0),
    .io_northIn_1  (_pairs_1_2_io_southOut_1),
    .io_eastOut    (_pairs_1_3_io_eastOut),
    .io_southOut_0 (_pairs_1_3_io_southOut_0),
    .io_southOut_1 (_pairs_1_3_io_southOut_1)
  );
  StripPair pairs_2_3 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_3_op),
    .io_westIn     (_pairs_1_3_io_eastOut),
    .io_northOpIn  (io_stripNorth_3_2_op),
    .io_northIn_0  (_pairs_2_2_io_southOut_0),
    .io_northIn_1  (_pairs_2_2_io_southOut_1),
    .io_eastOut    (_pairs_2_3_io_eastOut),
    .io_southOut_0 (_pairs_2_3_io_southOut_0),
    .io_southOut_1 (_pairs_2_3_io_southOut_1)
  );
  StripPair pairs_3_3 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_3_op),
    .io_westIn     (_pairs_2_3_io_eastOut),
    .io_northOpIn  (io_stripNorth_3_3_op),
    .io_northIn_0  (_pairs_3_2_io_southOut_0),
    .io_northIn_1  (_pairs_3_2_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_3_3_io_southOut_0),
    .io_southOut_1 (_pairs_3_3_io_southOut_1)
  );
  StripPair pairs_0_4 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_4_op),
    .io_westIn     (io_west_4_data),
    .io_northOpIn  (io_stripNorth_4_0_op),
    .io_northIn_0
      (io_stripNorth_4_0_op ? io_stripNorth_4_0_data : _pairs_0_3_io_southOut_0),
    .io_northIn_1  (io_stripNorth_4_0_op ? 32'h0 : _pairs_0_3_io_southOut_1),
    .io_eastOut    (_pairs_0_4_io_eastOut),
    .io_southOut_0 (_pairs_0_4_io_southOut_0),
    .io_southOut_1 (_pairs_0_4_io_southOut_1)
  );
  StripPair pairs_1_4 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_4_op),
    .io_westIn     (_pairs_0_4_io_eastOut),
    .io_northOpIn  (io_stripNorth_4_1_op),
    .io_northIn_0
      (io_stripNorth_4_1_op ? io_stripNorth_4_1_data : _pairs_1_3_io_southOut_0),
    .io_northIn_1  (io_stripNorth_4_1_op ? 32'h0 : _pairs_1_3_io_southOut_1),
    .io_eastOut    (_pairs_1_4_io_eastOut),
    .io_southOut_0 (_pairs_1_4_io_southOut_0),
    .io_southOut_1 (_pairs_1_4_io_southOut_1)
  );
  StripPair pairs_2_4 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_4_op),
    .io_westIn     (_pairs_1_4_io_eastOut),
    .io_northOpIn  (io_stripNorth_4_2_op),
    .io_northIn_0
      (io_stripNorth_4_2_op ? io_stripNorth_4_2_data : _pairs_2_3_io_southOut_0),
    .io_northIn_1  (io_stripNorth_4_2_op ? 32'h0 : _pairs_2_3_io_southOut_1),
    .io_eastOut    (_pairs_2_4_io_eastOut),
    .io_southOut_0 (_pairs_2_4_io_southOut_0),
    .io_southOut_1 (_pairs_2_4_io_southOut_1)
  );
  StripPair pairs_3_4 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_4_op),
    .io_westIn     (_pairs_2_4_io_eastOut),
    .io_northOpIn  (io_stripNorth_4_3_op),
    .io_northIn_0
      (io_stripNorth_4_3_op ? io_stripNorth_4_3_data : _pairs_3_3_io_southOut_0),
    .io_northIn_1  (io_stripNorth_4_3_op ? 32'h0 : _pairs_3_3_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_3_4_io_southOut_0),
    .io_southOut_1 (_pairs_3_4_io_southOut_1)
  );
  StripPair pairs_0_5 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_5_op),
    .io_westIn     (io_west_5_data),
    .io_northOpIn  (io_stripNorth_5_0_op),
    .io_northIn_0  (_pairs_0_4_io_southOut_0),
    .io_northIn_1  (_pairs_0_4_io_southOut_1),
    .io_eastOut    (_pairs_0_5_io_eastOut),
    .io_southOut_0 (_pairs_0_5_io_southOut_0),
    .io_southOut_1 (_pairs_0_5_io_southOut_1)
  );
  StripPair pairs_1_5 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_5_op),
    .io_westIn     (_pairs_0_5_io_eastOut),
    .io_northOpIn  (io_stripNorth_5_1_op),
    .io_northIn_0  (_pairs_1_4_io_southOut_0),
    .io_northIn_1  (_pairs_1_4_io_southOut_1),
    .io_eastOut    (_pairs_1_5_io_eastOut),
    .io_southOut_0 (_pairs_1_5_io_southOut_0),
    .io_southOut_1 (_pairs_1_5_io_southOut_1)
  );
  StripPair pairs_2_5 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_5_op),
    .io_westIn     (_pairs_1_5_io_eastOut),
    .io_northOpIn  (io_stripNorth_5_2_op),
    .io_northIn_0  (_pairs_2_4_io_southOut_0),
    .io_northIn_1  (_pairs_2_4_io_southOut_1),
    .io_eastOut    (_pairs_2_5_io_eastOut),
    .io_southOut_0 (_pairs_2_5_io_southOut_0),
    .io_southOut_1 (_pairs_2_5_io_southOut_1)
  );
  StripPair pairs_3_5 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_5_op),
    .io_westIn     (_pairs_2_5_io_eastOut),
    .io_northOpIn  (io_stripNorth_5_3_op),
    .io_northIn_0  (_pairs_3_4_io_southOut_0),
    .io_northIn_1  (_pairs_3_4_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_3_5_io_southOut_0),
    .io_southOut_1 (_pairs_3_5_io_southOut_1)
  );
  StripPair pairs_0_6 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_6_op),
    .io_westIn     (io_west_6_data),
    .io_northOpIn  (io_stripNorth_6_0_op),
    .io_northIn_0  (_pairs_0_5_io_southOut_0),
    .io_northIn_1  (_pairs_0_5_io_southOut_1),
    .io_eastOut    (_pairs_0_6_io_eastOut),
    .io_southOut_0 (_pairs_0_6_io_southOut_0),
    .io_southOut_1 (_pairs_0_6_io_southOut_1)
  );
  StripPair pairs_1_6 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_6_op),
    .io_westIn     (_pairs_0_6_io_eastOut),
    .io_northOpIn  (io_stripNorth_6_1_op),
    .io_northIn_0  (_pairs_1_5_io_southOut_0),
    .io_northIn_1  (_pairs_1_5_io_southOut_1),
    .io_eastOut    (_pairs_1_6_io_eastOut),
    .io_southOut_0 (_pairs_1_6_io_southOut_0),
    .io_southOut_1 (_pairs_1_6_io_southOut_1)
  );
  StripPair pairs_2_6 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_6_op),
    .io_westIn     (_pairs_1_6_io_eastOut),
    .io_northOpIn  (io_stripNorth_6_2_op),
    .io_northIn_0  (_pairs_2_5_io_southOut_0),
    .io_northIn_1  (_pairs_2_5_io_southOut_1),
    .io_eastOut    (_pairs_2_6_io_eastOut),
    .io_southOut_0 (_pairs_2_6_io_southOut_0),
    .io_southOut_1 (_pairs_2_6_io_southOut_1)
  );
  StripPair pairs_3_6 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_6_op),
    .io_westIn     (_pairs_2_6_io_eastOut),
    .io_northOpIn  (io_stripNorth_6_3_op),
    .io_northIn_0  (_pairs_3_5_io_southOut_0),
    .io_northIn_1  (_pairs_3_5_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_3_6_io_southOut_0),
    .io_southOut_1 (_pairs_3_6_io_southOut_1)
  );
  StripPair pairs_0_7 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_7_op),
    .io_westIn     (io_west_7_data),
    .io_northOpIn  (io_stripNorth_7_0_op),
    .io_northIn_0  (_pairs_0_6_io_southOut_0),
    .io_northIn_1  (_pairs_0_6_io_southOut_1),
    .io_eastOut    (_pairs_0_7_io_eastOut),
    .io_southOut_0 (io_gemmSouthRaw_0),
    .io_southOut_1 (_pairs_0_7_io_southOut_1)
  );
  StripPair pairs_1_7 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_7_op),
    .io_westIn     (_pairs_0_7_io_eastOut),
    .io_northOpIn  (io_stripNorth_7_1_op),
    .io_northIn_0  (_pairs_1_6_io_southOut_0),
    .io_northIn_1  (_pairs_1_6_io_southOut_1),
    .io_eastOut    (_pairs_1_7_io_eastOut),
    .io_southOut_0 (io_gemmSouthRaw_2),
    .io_southOut_1 (_pairs_1_7_io_southOut_1)
  );
  StripPair pairs_2_7 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_7_op),
    .io_westIn     (_pairs_1_7_io_eastOut),
    .io_northOpIn  (io_stripNorth_7_2_op),
    .io_northIn_0  (_pairs_2_6_io_southOut_0),
    .io_northIn_1  (_pairs_2_6_io_southOut_1),
    .io_eastOut    (_pairs_2_7_io_eastOut),
    .io_southOut_0 (io_gemmSouthRaw_4),
    .io_southOut_1 (_pairs_2_7_io_southOut_1)
  );
  StripPair pairs_3_7 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_7_op),
    .io_westIn     (_pairs_2_7_io_eastOut),
    .io_northOpIn  (io_stripNorth_7_3_op),
    .io_northIn_0  (_pairs_3_6_io_southOut_0),
    .io_northIn_1  (_pairs_3_6_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (io_gemmSouthRaw_6),
    .io_southOut_1 (_pairs_3_7_io_southOut_1)
  );
  assign io_gemmSouthRaw_1 = _pairs_0_7_io_southOut_1;
  assign io_gemmSouthRaw_3 = _pairs_1_7_io_southOut_1;
  assign io_gemmSouthRaw_5 = _pairs_2_7_io_southOut_1;
  assign io_gemmSouthRaw_7 = _pairs_3_7_io_southOut_1;
  assign io_pinnSouthRaw_0 = _pairs_0_3_io_southOut_1;
  assign io_pinnSouthRaw_1 = _pairs_1_3_io_southOut_1;
  assign io_pinnSouthRaw_2 = _pairs_2_3_io_southOut_1;
  assign io_pinnSouthRaw_3 = _pairs_3_3_io_southOut_1;
  assign io_pinnSouthRaw_4 = _pairs_0_7_io_southOut_1;
  assign io_pinnSouthRaw_5 = _pairs_1_7_io_southOut_1;
  assign io_pinnSouthRaw_6 = _pairs_2_7_io_southOut_1;
  assign io_pinnSouthRaw_7 = _pairs_3_7_io_southOut_1;
endmodule

