// Generated by CIRCT firtool-1.140.0
module OneSaPEComputation(
  input         clock,
                reset,
  input  [1:0]  io_op,
  input  [7:0]  io_westIn_lanes_0,
                io_westIn_lanes_1,
                io_northIn_lanes_0,
                io_northIn_lanes_1,
  input  [31:0] io_psumIn,
  output [7:0]  io_eastOut_lanes_0,
                io_eastOut_lanes_1,
  output [31:0] io_psumOut,
                io_diagPairsOut_0
);

  reg  [7:0]  regEast_lanes_0;
  reg  [7:0]  regEast_lanes_1;
  reg  [31:0] regPsum;
  reg  [7:0]  regWeight_lanes_0;
  reg  [7:0]  regWeight_lanes_1;
  reg  [31:0] regSharedPairs_0;
  wire        _sharedMacRhs_T = io_op == 2'h2;
  wire [7:0]  sharedMacRhs_lanes_0 =
    _sharedMacRhs_T ? regWeight_lanes_0 : io_northIn_lanes_0;
  wire [7:0]  sharedMacRhs_lanes_1 =
    _sharedMacRhs_T ? regWeight_lanes_1 : io_northIn_lanes_1;
  wire [31:0] _sharedPairs_pairs_T =
    {{24{io_westIn_lanes_0[7]}}, io_westIn_lanes_0}
    * {{24{sharedMacRhs_lanes_0[7]}}, sharedMacRhs_lanes_0}
    + {{24{io_westIn_lanes_1[7]}}, io_westIn_lanes_1}
    * {{24{sharedMacRhs_lanes_1[7]}}, sharedMacRhs_lanes_1};
  always @(posedge clock) begin
    if (reset) begin
      regEast_lanes_0 <= 8'h0;
      regEast_lanes_1 <= 8'h0;
      regPsum <= 32'h0;
      regWeight_lanes_0 <= 8'h0;
      regWeight_lanes_1 <= 8'h0;
      regSharedPairs_0 <= 32'h0;
    end
    else begin
      automatic logic _GEN = io_op == 2'h1;
      automatic logic _GEN_0 = io_op == 2'h2;
      automatic logic _GEN_1 = _GEN | _GEN_0;
      regEast_lanes_0 <= _GEN_1 ? io_westIn_lanes_0 : 8'h0;
      regEast_lanes_1 <= _GEN_1 ? io_westIn_lanes_1 : 8'h0;
      regPsum <= _GEN ? io_psumIn : _GEN_0 ? regSharedPairs_0 + io_psumIn : 32'h0;
      if (_GEN) begin
        regWeight_lanes_0 <= io_westIn_lanes_0;
        regWeight_lanes_1 <= io_westIn_lanes_1;
      end
      if (_GEN | ~_GEN_0) begin
      end
      else
        regSharedPairs_0 <= _sharedPairs_pairs_T;
    end
  end // always @(posedge)
  assign io_eastOut_lanes_0 = regEast_lanes_0;
  assign io_eastOut_lanes_1 = regEast_lanes_1;
  assign io_psumOut = regPsum;
  assign io_diagPairsOut_0 = (&io_op) ? _sharedPairs_pairs_T : 32'h0;
endmodule

