// Generated by CIRCT firtool-1.140.0
module StripPair(
  input         clock,
                reset,
  input  [1:0]  io_westOpIn,
  input  [7:0]  io_westIn_bits,
  input         io_northOpIn,
  input  [15:0] io_northIn_0_bits,
                io_northIn_1_bits,
  output [7:0]  io_eastOut_bits,
  output [15:0] io_southOut_0_bits,
                io_southOut_1_bits
);

  wire [7:0]  _right_io_outLeftB_bits;
  wire [7:0]  _left_io_eastOut_bits;
  wire [15:0] _left_io_outRightP_bits;
  PELeft left (
    .clock             (clock),
    .reset             (reset),
    .io_westOpIn       (io_westOpIn),
    .io_westIn_bits    (io_westIn_bits),
    .io_northOpIn      (io_northOpIn),
    .io_northIn_bits   (io_northIn_0_bits),
    .io_inRightB_bits  (_right_io_outLeftB_bits),
    .io_eastOut_bits   (_left_io_eastOut_bits),
    .io_southOut_bits  (io_southOut_0_bits),
    .io_outRightP_bits (_left_io_outRightP_bits)
  );
  PERight right (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_westOpIn),
    .io_westIn_bits   (_left_io_eastOut_bits),
    .io_northOpIn     (io_northOpIn),
    .io_northIn_bits  (io_northIn_1_bits),
    .io_inLeftP_bits  (_left_io_outRightP_bits),
    .io_eastOut_bits  (io_eastOut_bits),
    .io_southOut_bits (io_southOut_1_bits),
    .io_outLeftB_bits (_right_io_outLeftB_bits)
  );
endmodule

