// Generated by CIRCT firtool-1.140.0
module OneSaMesh(
  input         clock,
                reset,
  input  [1:0]  io_op_0,
                io_op_1,
                io_op_2,
                io_op_3,
  input  [7:0]  io_west_0_lanes_0_bits,
                io_west_0_lanes_1_bits,
                io_west_1_lanes_0_bits,
                io_west_1_lanes_1_bits,
                io_west_2_lanes_0_bits,
                io_west_2_lanes_1_bits,
                io_west_3_lanes_0_bits,
                io_west_3_lanes_1_bits,
                io_north_0_lanes_0_bits,
                io_north_0_lanes_1_bits,
                io_north_1_lanes_0_bits,
                io_north_1_lanes_1_bits,
                io_north_2_lanes_0_bits,
                io_north_2_lanes_1_bits,
                io_north_3_lanes_0_bits,
                io_north_3_lanes_1_bits,
  input  [15:0] io_psum_0_bits,
                io_psum_1_bits,
                io_psum_2_bits,
                io_psum_3_bits,
  output [15:0] io_south_0_bits,
                io_south_1_bits,
                io_south_2_bits,
                io_south_3_bits,
                io_diag_0_bits,
                io_diag_1_bits,
                io_diag_2_bits,
                io_diag_3_bits,
                io_diagPairs_0_0_bits,
                io_diagPairs_1_0_bits,
                io_diagPairs_2_0_bits,
                io_diagPairs_3_0_bits,
  output        io_diagValid_0,
                io_diagValid_1,
                io_diagValid_2,
                io_diagValid_3
);

  wire [15:0] _pes_3_3_io_diagPairsOut_0_bits;
  wire [7:0]  _pes_3_2_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_3_2_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_3_1_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_3_1_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_3_0_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_3_0_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_2_3_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_2_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_3_io_psumOut_bits;
  wire [7:0]  _pes_2_2_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_2_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_2_io_psumOut_bits;
  wire [15:0] _pes_2_2_io_diagPairsOut_0_bits;
  wire [7:0]  _pes_2_1_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_2_1_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_2_1_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_2_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_1_io_psumOut_bits;
  wire [7:0]  _pes_2_0_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_2_0_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_2_0_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_2_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_0_io_psumOut_bits;
  wire [7:0]  _pes_1_3_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_1_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_3_io_psumOut_bits;
  wire [7:0]  _pes_1_2_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_1_2_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_1_2_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_1_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_2_io_psumOut_bits;
  wire [7:0]  _pes_1_1_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_1_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_1_io_psumOut_bits;
  wire [15:0] _pes_1_1_io_diagPairsOut_0_bits;
  wire [7:0]  _pes_1_0_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_1_0_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_1_0_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_1_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_0_io_psumOut_bits;
  wire [7:0]  _pes_0_3_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_0_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_3_io_psumOut_bits;
  wire [7:0]  _pes_0_2_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_0_2_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_0_2_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_0_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_2_io_psumOut_bits;
  wire [7:0]  _pes_0_1_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_0_1_io_eastOut_lanes_1_bits;
  wire [7:0]  _pes_0_1_io_southOut_lanes_0_bits;
  wire [7:0]  _pes_0_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_1_io_psumOut_bits;
  wire [7:0]  _pes_0_0_io_eastOut_lanes_0_bits;
  wire [7:0]  _pes_0_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_0_io_psumOut_bits;
  wire [15:0] _pes_0_0_io_diagPairsOut_0_bits;
  OneSaPEComputation pes_0_0 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_0),
    .io_westIn_lanes_0_bits  (io_west_0_lanes_0_bits),
    .io_westIn_lanes_1_bits  (io_west_0_lanes_1_bits),
    .io_northIn_lanes_0_bits (io_north_0_lanes_0_bits),
    .io_northIn_lanes_1_bits (io_north_0_lanes_1_bits),
    .io_psumIn_bits          (io_psum_0_bits),
    .io_eastOut_lanes_0_bits (_pes_0_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_0_0_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_0_0_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_0_0_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_0_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_1_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_1_lanes_1_bits),
    .io_psumIn_bits           (io_psum_1_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_1_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_2_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_2_lanes_1_bits),
    .io_psumIn_bits           (io_psum_2_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_2_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_3_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_3_lanes_1_bits),
    .io_psumIn_bits           (io_psum_3_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_0_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (io_west_1_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_1_lanes_1_bits),
    .io_northIn_lanes_0_bits  (8'h0),
    .io_northIn_lanes_1_bits  (8'h0),
    .io_psumIn_bits           (_pes_0_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_0_io_psumOut_bits)
  );
  OneSaPEComputation pes_1_1 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_1),
    .io_westIn_lanes_0_bits  (_pes_1_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_1_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_0_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_0_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_0_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_1_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_1_1_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_1_1_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_1_1_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_1_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_2_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_1_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (io_west_2_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_2_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_0_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (8'h0),
    .io_northIn_lanes_1_bits  (8'h0),
    .io_psumIn_bits           (_pes_1_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_1_io_psumOut_bits)
  );
  OneSaPEComputation pes_2_2 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_2),
    .io_westIn_lanes_0_bits  (_pes_2_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_2_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_1_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_1_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_1_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_2_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_2_2_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_2_2_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_2_2_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_2_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_2_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_3_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (io_west_3_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_3_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_0_bits)
  );
  OneSaPETransmission pes_3_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_1_bits)
  );
  OneSaPETransmission pes_3_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (8'h0),
    .io_northIn_lanes_1_bits  (8'h0),
    .io_psumIn_bits           (_pes_2_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_2_bits)
  );
  OneSaPEComputation pes_3_3 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_3),
    .io_westIn_lanes_0_bits  (_pes_3_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_3_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_2_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_2_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_2_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (/* unused */),
    .io_eastOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits         (io_south_3_bits),
    .io_diagPairsOut_0_bits  (_pes_3_3_io_diagPairsOut_0_bits)
  );
  assign io_diag_0_bits = _pes_0_0_io_diagPairsOut_0_bits;
  assign io_diag_1_bits = _pes_1_1_io_diagPairsOut_0_bits;
  assign io_diag_2_bits = _pes_2_2_io_diagPairsOut_0_bits;
  assign io_diag_3_bits = _pes_3_3_io_diagPairsOut_0_bits;
  assign io_diagPairs_0_0_bits = _pes_0_0_io_diagPairsOut_0_bits;
  assign io_diagPairs_1_0_bits = _pes_1_1_io_diagPairsOut_0_bits;
  assign io_diagPairs_2_0_bits = _pes_2_2_io_diagPairsOut_0_bits;
  assign io_diagPairs_3_0_bits = _pes_3_3_io_diagPairsOut_0_bits;
  assign io_diagValid_0 = &io_op_0;
  assign io_diagValid_1 = &io_op_1;
  assign io_diagValid_2 = &io_op_2;
  assign io_diagValid_3 = &io_op_3;
endmodule

