// Generated by CIRCT firtool-1.140.0
`ifndef layers_FuseMax2DArray_Verification
  `define layers_FuseMax2DArray_Verification
  `include "layers-FuseMax2DPE-Verification.sv"
`endif // not def layers_FuseMax2DArray_Verification
