// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [2:0]  io_peOp_0_0,
                io_peOp_0_1,
                io_peOp_0_2,
                io_peOp_0_3,
                io_peOp_0_4,
                io_peOp_0_5,
                io_peOp_0_6,
                io_peOp_0_7,
                io_peOp_1_0,
                io_peOp_1_1,
                io_peOp_1_2,
                io_peOp_1_3,
                io_peOp_1_4,
                io_peOp_1_5,
                io_peOp_1_6,
                io_peOp_1_7,
                io_peOp_2_0,
                io_peOp_2_1,
                io_peOp_2_2,
                io_peOp_2_3,
                io_peOp_2_4,
                io_peOp_2_5,
                io_peOp_2_6,
                io_peOp_2_7,
                io_peOp_3_0,
                io_peOp_3_1,
                io_peOp_3_2,
                io_peOp_3_3,
                io_peOp_3_4,
                io_peOp_3_5,
                io_peOp_3_6,
                io_peOp_3_7,
                io_peOp_4_0,
                io_peOp_4_1,
                io_peOp_4_2,
                io_peOp_4_3,
                io_peOp_4_4,
                io_peOp_4_5,
                io_peOp_4_6,
                io_peOp_4_7,
                io_peOp_5_0,
                io_peOp_5_1,
                io_peOp_5_2,
                io_peOp_5_3,
                io_peOp_5_4,
                io_peOp_5_5,
                io_peOp_5_6,
                io_peOp_5_7,
                io_peOp_6_0,
                io_peOp_6_1,
                io_peOp_6_2,
                io_peOp_6_3,
                io_peOp_6_4,
                io_peOp_6_5,
                io_peOp_6_6,
                io_peOp_6_7,
                io_peOp_7_0,
                io_peOp_7_1,
                io_peOp_7_2,
                io_peOp_7_3,
                io_peOp_7_4,
                io_peOp_7_5,
                io_peOp_7_6,
                io_peOp_7_7,
  input  [15:0] io_leftIn_0_bits,
                io_leftIn_1_bits,
                io_leftIn_2_bits,
                io_leftIn_3_bits,
                io_leftIn_4_bits,
                io_leftIn_5_bits,
                io_leftIn_6_bits,
                io_leftIn_7_bits,
                io_bottomIn_0_bits,
                io_bottomIn_1_bits,
                io_bottomIn_2_bits,
                io_bottomIn_3_bits,
                io_bottomIn_4_bits,
                io_bottomIn_5_bits,
                io_bottomIn_6_bits,
                io_bottomIn_7_bits,
  input  [2:0]  io_cmpOp_0,
                io_cmpOp_1,
                io_cmpOp_2,
                io_cmpOp_3,
                io_cmpOp_4,
                io_cmpOp_5,
                io_cmpOp_6,
                io_cmpOp_7,
  input  [15:0] io_cmpSeedOldMax_0_bits,
                io_cmpSeedOldMax_1_bits,
                io_cmpSeedOldMax_2_bits,
                io_cmpSeedOldMax_3_bits,
                io_cmpSeedOldMax_4_bits,
                io_cmpSeedOldMax_5_bits,
                io_cmpSeedOldMax_6_bits,
                io_cmpSeedOldMax_7_bits,
                io_cmpIntercept_0_bits,
                io_cmpIntercept_1_bits,
                io_cmpIntercept_2_bits,
                io_cmpIntercept_3_bits,
                io_cmpIntercept_4_bits,
                io_cmpIntercept_5_bits,
                io_cmpIntercept_6_bits,
                io_cmpIntercept_7_bits,
  output [15:0] io_accOut_0_bits,
                io_accOut_1_bits,
                io_accOut_2_bits,
                io_accOut_3_bits,
                io_accOut_4_bits,
                io_accOut_5_bits,
                io_accOut_6_bits,
                io_accOut_7_bits,
                io_rowMax_0_bits,
                io_rowMax_1_bits,
                io_rowMax_2_bits,
                io_rowMax_3_bits,
                io_rowMax_4_bits,
                io_rowMax_5_bits,
                io_rowMax_6_bits,
                io_rowMax_7_bits,
                io_rowDiff_0_bits,
                io_rowDiff_1_bits,
                io_rowDiff_2_bits,
                io_rowDiff_3_bits,
                io_rowDiff_4_bits,
                io_rowDiff_5_bits,
                io_rowDiff_6_bits,
                io_rowDiff_7_bits
);

  wire [15:0] _mesh_7_7_io_dOutput_bits;
  wire [15:0] _mesh_7_7_io_uOutput_bits;
  wire [15:0] _mesh_7_6_io_rOutput_bits;
  wire [15:0] _mesh_7_6_io_dOutput_bits;
  wire [15:0] _mesh_7_6_io_uOutput_bits;
  wire [15:0] _mesh_7_5_io_rOutput_bits;
  wire [15:0] _mesh_7_5_io_dOutput_bits;
  wire [15:0] _mesh_7_5_io_uOutput_bits;
  wire [15:0] _mesh_7_4_io_rOutput_bits;
  wire [15:0] _mesh_7_4_io_dOutput_bits;
  wire [15:0] _mesh_7_4_io_uOutput_bits;
  wire [15:0] _mesh_7_3_io_rOutput_bits;
  wire [15:0] _mesh_7_3_io_dOutput_bits;
  wire [15:0] _mesh_7_3_io_uOutput_bits;
  wire [15:0] _mesh_7_2_io_rOutput_bits;
  wire [15:0] _mesh_7_2_io_dOutput_bits;
  wire [15:0] _mesh_7_2_io_uOutput_bits;
  wire [15:0] _mesh_7_1_io_rOutput_bits;
  wire [15:0] _mesh_7_1_io_dOutput_bits;
  wire [15:0] _mesh_7_1_io_uOutput_bits;
  wire [15:0] _mesh_7_0_io_rOutput_bits;
  wire [15:0] _mesh_7_0_io_dOutput_bits;
  wire [15:0] _mesh_7_0_io_uOutput_bits;
  wire [15:0] _mesh_6_7_io_dOutput_bits;
  wire [15:0] _mesh_6_7_io_uOutput_bits;
  wire [15:0] _mesh_6_6_io_rOutput_bits;
  wire [15:0] _mesh_6_6_io_dOutput_bits;
  wire [15:0] _mesh_6_6_io_uOutput_bits;
  wire [15:0] _mesh_6_5_io_rOutput_bits;
  wire [15:0] _mesh_6_5_io_dOutput_bits;
  wire [15:0] _mesh_6_5_io_uOutput_bits;
  wire [15:0] _mesh_6_4_io_rOutput_bits;
  wire [15:0] _mesh_6_4_io_dOutput_bits;
  wire [15:0] _mesh_6_4_io_uOutput_bits;
  wire [15:0] _mesh_6_3_io_rOutput_bits;
  wire [15:0] _mesh_6_3_io_dOutput_bits;
  wire [15:0] _mesh_6_3_io_uOutput_bits;
  wire [15:0] _mesh_6_2_io_rOutput_bits;
  wire [15:0] _mesh_6_2_io_dOutput_bits;
  wire [15:0] _mesh_6_2_io_uOutput_bits;
  wire [15:0] _mesh_6_1_io_rOutput_bits;
  wire [15:0] _mesh_6_1_io_dOutput_bits;
  wire [15:0] _mesh_6_1_io_uOutput_bits;
  wire [15:0] _mesh_6_0_io_rOutput_bits;
  wire [15:0] _mesh_6_0_io_dOutput_bits;
  wire [15:0] _mesh_6_0_io_uOutput_bits;
  wire [15:0] _mesh_5_7_io_dOutput_bits;
  wire [15:0] _mesh_5_7_io_uOutput_bits;
  wire [15:0] _mesh_5_6_io_rOutput_bits;
  wire [15:0] _mesh_5_6_io_dOutput_bits;
  wire [15:0] _mesh_5_6_io_uOutput_bits;
  wire [15:0] _mesh_5_5_io_rOutput_bits;
  wire [15:0] _mesh_5_5_io_dOutput_bits;
  wire [15:0] _mesh_5_5_io_uOutput_bits;
  wire [15:0] _mesh_5_4_io_rOutput_bits;
  wire [15:0] _mesh_5_4_io_dOutput_bits;
  wire [15:0] _mesh_5_4_io_uOutput_bits;
  wire [15:0] _mesh_5_3_io_rOutput_bits;
  wire [15:0] _mesh_5_3_io_dOutput_bits;
  wire [15:0] _mesh_5_3_io_uOutput_bits;
  wire [15:0] _mesh_5_2_io_rOutput_bits;
  wire [15:0] _mesh_5_2_io_dOutput_bits;
  wire [15:0] _mesh_5_2_io_uOutput_bits;
  wire [15:0] _mesh_5_1_io_rOutput_bits;
  wire [15:0] _mesh_5_1_io_dOutput_bits;
  wire [15:0] _mesh_5_1_io_uOutput_bits;
  wire [15:0] _mesh_5_0_io_rOutput_bits;
  wire [15:0] _mesh_5_0_io_dOutput_bits;
  wire [15:0] _mesh_5_0_io_uOutput_bits;
  wire [15:0] _mesh_4_7_io_dOutput_bits;
  wire [15:0] _mesh_4_7_io_uOutput_bits;
  wire [15:0] _mesh_4_6_io_rOutput_bits;
  wire [15:0] _mesh_4_6_io_dOutput_bits;
  wire [15:0] _mesh_4_6_io_uOutput_bits;
  wire [15:0] _mesh_4_5_io_rOutput_bits;
  wire [15:0] _mesh_4_5_io_dOutput_bits;
  wire [15:0] _mesh_4_5_io_uOutput_bits;
  wire [15:0] _mesh_4_4_io_rOutput_bits;
  wire [15:0] _mesh_4_4_io_dOutput_bits;
  wire [15:0] _mesh_4_4_io_uOutput_bits;
  wire [15:0] _mesh_4_3_io_rOutput_bits;
  wire [15:0] _mesh_4_3_io_dOutput_bits;
  wire [15:0] _mesh_4_3_io_uOutput_bits;
  wire [15:0] _mesh_4_2_io_rOutput_bits;
  wire [15:0] _mesh_4_2_io_dOutput_bits;
  wire [15:0] _mesh_4_2_io_uOutput_bits;
  wire [15:0] _mesh_4_1_io_rOutput_bits;
  wire [15:0] _mesh_4_1_io_dOutput_bits;
  wire [15:0] _mesh_4_1_io_uOutput_bits;
  wire [15:0] _mesh_4_0_io_rOutput_bits;
  wire [15:0] _mesh_4_0_io_dOutput_bits;
  wire [15:0] _mesh_4_0_io_uOutput_bits;
  wire [15:0] _mesh_3_7_io_dOutput_bits;
  wire [15:0] _mesh_3_7_io_uOutput_bits;
  wire [15:0] _mesh_3_6_io_rOutput_bits;
  wire [15:0] _mesh_3_6_io_dOutput_bits;
  wire [15:0] _mesh_3_6_io_uOutput_bits;
  wire [15:0] _mesh_3_5_io_rOutput_bits;
  wire [15:0] _mesh_3_5_io_dOutput_bits;
  wire [15:0] _mesh_3_5_io_uOutput_bits;
  wire [15:0] _mesh_3_4_io_rOutput_bits;
  wire [15:0] _mesh_3_4_io_dOutput_bits;
  wire [15:0] _mesh_3_4_io_uOutput_bits;
  wire [15:0] _mesh_3_3_io_rOutput_bits;
  wire [15:0] _mesh_3_3_io_dOutput_bits;
  wire [15:0] _mesh_3_3_io_uOutput_bits;
  wire [15:0] _mesh_3_2_io_rOutput_bits;
  wire [15:0] _mesh_3_2_io_dOutput_bits;
  wire [15:0] _mesh_3_2_io_uOutput_bits;
  wire [15:0] _mesh_3_1_io_rOutput_bits;
  wire [15:0] _mesh_3_1_io_dOutput_bits;
  wire [15:0] _mesh_3_1_io_uOutput_bits;
  wire [15:0] _mesh_3_0_io_rOutput_bits;
  wire [15:0] _mesh_3_0_io_dOutput_bits;
  wire [15:0] _mesh_3_0_io_uOutput_bits;
  wire [15:0] _mesh_2_7_io_dOutput_bits;
  wire [15:0] _mesh_2_7_io_uOutput_bits;
  wire [15:0] _mesh_2_6_io_rOutput_bits;
  wire [15:0] _mesh_2_6_io_dOutput_bits;
  wire [15:0] _mesh_2_6_io_uOutput_bits;
  wire [15:0] _mesh_2_5_io_rOutput_bits;
  wire [15:0] _mesh_2_5_io_dOutput_bits;
  wire [15:0] _mesh_2_5_io_uOutput_bits;
  wire [15:0] _mesh_2_4_io_rOutput_bits;
  wire [15:0] _mesh_2_4_io_dOutput_bits;
  wire [15:0] _mesh_2_4_io_uOutput_bits;
  wire [15:0] _mesh_2_3_io_rOutput_bits;
  wire [15:0] _mesh_2_3_io_dOutput_bits;
  wire [15:0] _mesh_2_3_io_uOutput_bits;
  wire [15:0] _mesh_2_2_io_rOutput_bits;
  wire [15:0] _mesh_2_2_io_dOutput_bits;
  wire [15:0] _mesh_2_2_io_uOutput_bits;
  wire [15:0] _mesh_2_1_io_rOutput_bits;
  wire [15:0] _mesh_2_1_io_dOutput_bits;
  wire [15:0] _mesh_2_1_io_uOutput_bits;
  wire [15:0] _mesh_2_0_io_rOutput_bits;
  wire [15:0] _mesh_2_0_io_dOutput_bits;
  wire [15:0] _mesh_2_0_io_uOutput_bits;
  wire [15:0] _mesh_1_7_io_dOutput_bits;
  wire [15:0] _mesh_1_7_io_uOutput_bits;
  wire [15:0] _mesh_1_6_io_rOutput_bits;
  wire [15:0] _mesh_1_6_io_dOutput_bits;
  wire [15:0] _mesh_1_6_io_uOutput_bits;
  wire [15:0] _mesh_1_5_io_rOutput_bits;
  wire [15:0] _mesh_1_5_io_dOutput_bits;
  wire [15:0] _mesh_1_5_io_uOutput_bits;
  wire [15:0] _mesh_1_4_io_rOutput_bits;
  wire [15:0] _mesh_1_4_io_dOutput_bits;
  wire [15:0] _mesh_1_4_io_uOutput_bits;
  wire [15:0] _mesh_1_3_io_rOutput_bits;
  wire [15:0] _mesh_1_3_io_dOutput_bits;
  wire [15:0] _mesh_1_3_io_uOutput_bits;
  wire [15:0] _mesh_1_2_io_rOutput_bits;
  wire [15:0] _mesh_1_2_io_dOutput_bits;
  wire [15:0] _mesh_1_2_io_uOutput_bits;
  wire [15:0] _mesh_1_1_io_rOutput_bits;
  wire [15:0] _mesh_1_1_io_dOutput_bits;
  wire [15:0] _mesh_1_1_io_uOutput_bits;
  wire [15:0] _mesh_1_0_io_rOutput_bits;
  wire [15:0] _mesh_1_0_io_dOutput_bits;
  wire [15:0] _mesh_1_0_io_uOutput_bits;
  wire [15:0] _mesh_0_7_io_dOutput_bits;
  wire [15:0] _mesh_0_7_io_uOutput_bits;
  wire [15:0] _mesh_0_6_io_rOutput_bits;
  wire [15:0] _mesh_0_6_io_dOutput_bits;
  wire [15:0] _mesh_0_6_io_uOutput_bits;
  wire [15:0] _mesh_0_5_io_rOutput_bits;
  wire [15:0] _mesh_0_5_io_dOutput_bits;
  wire [15:0] _mesh_0_5_io_uOutput_bits;
  wire [15:0] _mesh_0_4_io_rOutput_bits;
  wire [15:0] _mesh_0_4_io_dOutput_bits;
  wire [15:0] _mesh_0_4_io_uOutput_bits;
  wire [15:0] _mesh_0_3_io_rOutput_bits;
  wire [15:0] _mesh_0_3_io_dOutput_bits;
  wire [15:0] _mesh_0_3_io_uOutput_bits;
  wire [15:0] _mesh_0_2_io_rOutput_bits;
  wire [15:0] _mesh_0_2_io_dOutput_bits;
  wire [15:0] _mesh_0_2_io_uOutput_bits;
  wire [15:0] _mesh_0_1_io_rOutput_bits;
  wire [15:0] _mesh_0_1_io_dOutput_bits;
  wire [15:0] _mesh_0_1_io_uOutput_bits;
  wire [15:0] _mesh_0_0_io_rOutput_bits;
  wire [15:0] _mesh_0_0_io_dOutput_bits;
  wire [15:0] _mesh_0_0_io_uOutput_bits;
  wire [15:0] _cmpArray_7_io_dOutput_bits;
  wire [15:0] _cmpArray_6_io_dOutput_bits;
  wire [15:0] _cmpArray_5_io_dOutput_bits;
  wire [15:0] _cmpArray_4_io_dOutput_bits;
  wire [15:0] _cmpArray_3_io_dOutput_bits;
  wire [15:0] _cmpArray_2_io_dOutput_bits;
  wire [15:0] _cmpArray_1_io_dOutput_bits;
  wire [15:0] _cmpArray_0_io_dOutput_bits;
  reg  [15:0] dIn_bits;
  reg  [15:0] lIn_bits;
  reg  [15:0] dIn_1_bits;
  reg  [15:0] lIn_1_bits;
  reg  [15:0] dIn_2_bits;
  reg  [15:0] lIn_2_bits;
  reg  [15:0] dIn_3_bits;
  reg  [15:0] lIn_3_bits;
  reg  [15:0] dIn_4_bits;
  reg  [15:0] lIn_4_bits;
  reg  [15:0] dIn_5_bits;
  reg  [15:0] lIn_5_bits;
  reg  [15:0] dIn_6_bits;
  reg  [15:0] lIn_6_bits;
  reg  [15:0] dIn_7_bits;
  reg  [15:0] uIn_bits;
  reg  [15:0] dIn_8_bits;
  reg  [15:0] lIn_7_bits;
  reg  [15:0] uIn_1_bits;
  reg  [15:0] dIn_9_bits;
  reg  [15:0] lIn_8_bits;
  reg  [15:0] uIn_2_bits;
  reg  [15:0] dIn_10_bits;
  reg  [15:0] lIn_9_bits;
  reg  [15:0] uIn_3_bits;
  reg  [15:0] dIn_11_bits;
  reg  [15:0] lIn_10_bits;
  reg  [15:0] uIn_4_bits;
  reg  [15:0] dIn_12_bits;
  reg  [15:0] lIn_11_bits;
  reg  [15:0] uIn_5_bits;
  reg  [15:0] dIn_13_bits;
  reg  [15:0] lIn_12_bits;
  reg  [15:0] uIn_6_bits;
  reg  [15:0] dIn_14_bits;
  reg  [15:0] lIn_13_bits;
  reg  [15:0] uIn_7_bits;
  reg  [15:0] dIn_15_bits;
  reg  [15:0] uIn_8_bits;
  reg  [15:0] dIn_16_bits;
  reg  [15:0] lIn_14_bits;
  reg  [15:0] uIn_9_bits;
  reg  [15:0] dIn_17_bits;
  reg  [15:0] lIn_15_bits;
  reg  [15:0] uIn_10_bits;
  reg  [15:0] dIn_18_bits;
  reg  [15:0] lIn_16_bits;
  reg  [15:0] uIn_11_bits;
  reg  [15:0] dIn_19_bits;
  reg  [15:0] lIn_17_bits;
  reg  [15:0] uIn_12_bits;
  reg  [15:0] dIn_20_bits;
  reg  [15:0] lIn_18_bits;
  reg  [15:0] uIn_13_bits;
  reg  [15:0] dIn_21_bits;
  reg  [15:0] lIn_19_bits;
  reg  [15:0] uIn_14_bits;
  reg  [15:0] dIn_22_bits;
  reg  [15:0] lIn_20_bits;
  reg  [15:0] uIn_15_bits;
  reg  [15:0] dIn_23_bits;
  reg  [15:0] uIn_16_bits;
  reg  [15:0] dIn_24_bits;
  reg  [15:0] lIn_21_bits;
  reg  [15:0] uIn_17_bits;
  reg  [15:0] dIn_25_bits;
  reg  [15:0] lIn_22_bits;
  reg  [15:0] uIn_18_bits;
  reg  [15:0] dIn_26_bits;
  reg  [15:0] lIn_23_bits;
  reg  [15:0] uIn_19_bits;
  reg  [15:0] dIn_27_bits;
  reg  [15:0] lIn_24_bits;
  reg  [15:0] uIn_20_bits;
  reg  [15:0] dIn_28_bits;
  reg  [15:0] lIn_25_bits;
  reg  [15:0] uIn_21_bits;
  reg  [15:0] dIn_29_bits;
  reg  [15:0] lIn_26_bits;
  reg  [15:0] uIn_22_bits;
  reg  [15:0] dIn_30_bits;
  reg  [15:0] lIn_27_bits;
  reg  [15:0] uIn_23_bits;
  reg  [15:0] dIn_31_bits;
  reg  [15:0] uIn_24_bits;
  reg  [15:0] dIn_32_bits;
  reg  [15:0] lIn_28_bits;
  reg  [15:0] uIn_25_bits;
  reg  [15:0] dIn_33_bits;
  reg  [15:0] lIn_29_bits;
  reg  [15:0] uIn_26_bits;
  reg  [15:0] dIn_34_bits;
  reg  [15:0] lIn_30_bits;
  reg  [15:0] uIn_27_bits;
  reg  [15:0] dIn_35_bits;
  reg  [15:0] lIn_31_bits;
  reg  [15:0] uIn_28_bits;
  reg  [15:0] dIn_36_bits;
  reg  [15:0] lIn_32_bits;
  reg  [15:0] uIn_29_bits;
  reg  [15:0] dIn_37_bits;
  reg  [15:0] lIn_33_bits;
  reg  [15:0] uIn_30_bits;
  reg  [15:0] dIn_38_bits;
  reg  [15:0] lIn_34_bits;
  reg  [15:0] uIn_31_bits;
  reg  [15:0] dIn_39_bits;
  reg  [15:0] uIn_32_bits;
  reg  [15:0] dIn_40_bits;
  reg  [15:0] lIn_35_bits;
  reg  [15:0] uIn_33_bits;
  reg  [15:0] dIn_41_bits;
  reg  [15:0] lIn_36_bits;
  reg  [15:0] uIn_34_bits;
  reg  [15:0] dIn_42_bits;
  reg  [15:0] lIn_37_bits;
  reg  [15:0] uIn_35_bits;
  reg  [15:0] dIn_43_bits;
  reg  [15:0] lIn_38_bits;
  reg  [15:0] uIn_36_bits;
  reg  [15:0] dIn_44_bits;
  reg  [15:0] lIn_39_bits;
  reg  [15:0] uIn_37_bits;
  reg  [15:0] dIn_45_bits;
  reg  [15:0] lIn_40_bits;
  reg  [15:0] uIn_38_bits;
  reg  [15:0] dIn_46_bits;
  reg  [15:0] lIn_41_bits;
  reg  [15:0] uIn_39_bits;
  reg  [15:0] dIn_47_bits;
  reg  [15:0] uIn_40_bits;
  reg  [15:0] dIn_48_bits;
  reg  [15:0] lIn_42_bits;
  reg  [15:0] uIn_41_bits;
  reg  [15:0] dIn_49_bits;
  reg  [15:0] lIn_43_bits;
  reg  [15:0] uIn_42_bits;
  reg  [15:0] dIn_50_bits;
  reg  [15:0] lIn_44_bits;
  reg  [15:0] uIn_43_bits;
  reg  [15:0] dIn_51_bits;
  reg  [15:0] lIn_45_bits;
  reg  [15:0] uIn_44_bits;
  reg  [15:0] dIn_52_bits;
  reg  [15:0] lIn_46_bits;
  reg  [15:0] uIn_45_bits;
  reg  [15:0] dIn_53_bits;
  reg  [15:0] lIn_47_bits;
  reg  [15:0] uIn_46_bits;
  reg  [15:0] dIn_54_bits;
  reg  [15:0] lIn_48_bits;
  reg  [15:0] uIn_47_bits;
  reg  [15:0] dIn_55_bits;
  reg  [15:0] uIn_48_bits;
  reg  [15:0] lIn_49_bits;
  reg  [15:0] uIn_49_bits;
  reg  [15:0] lIn_50_bits;
  reg  [15:0] uIn_50_bits;
  reg  [15:0] lIn_51_bits;
  reg  [15:0] uIn_51_bits;
  reg  [15:0] lIn_52_bits;
  reg  [15:0] uIn_52_bits;
  reg  [15:0] lIn_53_bits;
  reg  [15:0] uIn_53_bits;
  reg  [15:0] lIn_54_bits;
  reg  [15:0] uIn_54_bits;
  reg  [15:0] lIn_55_bits;
  reg  [15:0] uIn_55_bits;
  reg  [15:0] cmpIn_bits;
  reg  [15:0] io_accOut_0_REG_bits;
  reg  [15:0] cmpIn_1_bits;
  reg  [15:0] io_accOut_1_REG_bits;
  reg  [15:0] cmpIn_2_bits;
  reg  [15:0] io_accOut_2_REG_bits;
  reg  [15:0] cmpIn_3_bits;
  reg  [15:0] io_accOut_3_REG_bits;
  reg  [15:0] cmpIn_4_bits;
  reg  [15:0] io_accOut_4_REG_bits;
  reg  [15:0] cmpIn_5_bits;
  reg  [15:0] io_accOut_5_REG_bits;
  reg  [15:0] cmpIn_6_bits;
  reg  [15:0] io_accOut_6_REG_bits;
  reg  [15:0] cmpIn_7_bits;
  reg  [15:0] io_accOut_7_REG_bits;
  always @(posedge clock) begin
    dIn_bits <= _mesh_1_0_io_uOutput_bits;
    lIn_bits <= _mesh_0_0_io_rOutput_bits;
    dIn_1_bits <= _mesh_1_1_io_uOutput_bits;
    lIn_1_bits <= _mesh_0_1_io_rOutput_bits;
    dIn_2_bits <= _mesh_1_2_io_uOutput_bits;
    lIn_2_bits <= _mesh_0_2_io_rOutput_bits;
    dIn_3_bits <= _mesh_1_3_io_uOutput_bits;
    lIn_3_bits <= _mesh_0_3_io_rOutput_bits;
    dIn_4_bits <= _mesh_1_4_io_uOutput_bits;
    lIn_4_bits <= _mesh_0_4_io_rOutput_bits;
    dIn_5_bits <= _mesh_1_5_io_uOutput_bits;
    lIn_5_bits <= _mesh_0_5_io_rOutput_bits;
    dIn_6_bits <= _mesh_1_6_io_uOutput_bits;
    lIn_6_bits <= _mesh_0_6_io_rOutput_bits;
    dIn_7_bits <= _mesh_1_7_io_uOutput_bits;
    uIn_bits <= _mesh_0_0_io_dOutput_bits;
    dIn_8_bits <= _mesh_2_0_io_uOutput_bits;
    lIn_7_bits <= _mesh_1_0_io_rOutput_bits;
    uIn_1_bits <= _mesh_0_1_io_dOutput_bits;
    dIn_9_bits <= _mesh_2_1_io_uOutput_bits;
    lIn_8_bits <= _mesh_1_1_io_rOutput_bits;
    uIn_2_bits <= _mesh_0_2_io_dOutput_bits;
    dIn_10_bits <= _mesh_2_2_io_uOutput_bits;
    lIn_9_bits <= _mesh_1_2_io_rOutput_bits;
    uIn_3_bits <= _mesh_0_3_io_dOutput_bits;
    dIn_11_bits <= _mesh_2_3_io_uOutput_bits;
    lIn_10_bits <= _mesh_1_3_io_rOutput_bits;
    uIn_4_bits <= _mesh_0_4_io_dOutput_bits;
    dIn_12_bits <= _mesh_2_4_io_uOutput_bits;
    lIn_11_bits <= _mesh_1_4_io_rOutput_bits;
    uIn_5_bits <= _mesh_0_5_io_dOutput_bits;
    dIn_13_bits <= _mesh_2_5_io_uOutput_bits;
    lIn_12_bits <= _mesh_1_5_io_rOutput_bits;
    uIn_6_bits <= _mesh_0_6_io_dOutput_bits;
    dIn_14_bits <= _mesh_2_6_io_uOutput_bits;
    lIn_13_bits <= _mesh_1_6_io_rOutput_bits;
    uIn_7_bits <= _mesh_0_7_io_dOutput_bits;
    dIn_15_bits <= _mesh_2_7_io_uOutput_bits;
    uIn_8_bits <= _mesh_1_0_io_dOutput_bits;
    dIn_16_bits <= _mesh_3_0_io_uOutput_bits;
    lIn_14_bits <= _mesh_2_0_io_rOutput_bits;
    uIn_9_bits <= _mesh_1_1_io_dOutput_bits;
    dIn_17_bits <= _mesh_3_1_io_uOutput_bits;
    lIn_15_bits <= _mesh_2_1_io_rOutput_bits;
    uIn_10_bits <= _mesh_1_2_io_dOutput_bits;
    dIn_18_bits <= _mesh_3_2_io_uOutput_bits;
    lIn_16_bits <= _mesh_2_2_io_rOutput_bits;
    uIn_11_bits <= _mesh_1_3_io_dOutput_bits;
    dIn_19_bits <= _mesh_3_3_io_uOutput_bits;
    lIn_17_bits <= _mesh_2_3_io_rOutput_bits;
    uIn_12_bits <= _mesh_1_4_io_dOutput_bits;
    dIn_20_bits <= _mesh_3_4_io_uOutput_bits;
    lIn_18_bits <= _mesh_2_4_io_rOutput_bits;
    uIn_13_bits <= _mesh_1_5_io_dOutput_bits;
    dIn_21_bits <= _mesh_3_5_io_uOutput_bits;
    lIn_19_bits <= _mesh_2_5_io_rOutput_bits;
    uIn_14_bits <= _mesh_1_6_io_dOutput_bits;
    dIn_22_bits <= _mesh_3_6_io_uOutput_bits;
    lIn_20_bits <= _mesh_2_6_io_rOutput_bits;
    uIn_15_bits <= _mesh_1_7_io_dOutput_bits;
    dIn_23_bits <= _mesh_3_7_io_uOutput_bits;
    uIn_16_bits <= _mesh_2_0_io_dOutput_bits;
    dIn_24_bits <= _mesh_4_0_io_uOutput_bits;
    lIn_21_bits <= _mesh_3_0_io_rOutput_bits;
    uIn_17_bits <= _mesh_2_1_io_dOutput_bits;
    dIn_25_bits <= _mesh_4_1_io_uOutput_bits;
    lIn_22_bits <= _mesh_3_1_io_rOutput_bits;
    uIn_18_bits <= _mesh_2_2_io_dOutput_bits;
    dIn_26_bits <= _mesh_4_2_io_uOutput_bits;
    lIn_23_bits <= _mesh_3_2_io_rOutput_bits;
    uIn_19_bits <= _mesh_2_3_io_dOutput_bits;
    dIn_27_bits <= _mesh_4_3_io_uOutput_bits;
    lIn_24_bits <= _mesh_3_3_io_rOutput_bits;
    uIn_20_bits <= _mesh_2_4_io_dOutput_bits;
    dIn_28_bits <= _mesh_4_4_io_uOutput_bits;
    lIn_25_bits <= _mesh_3_4_io_rOutput_bits;
    uIn_21_bits <= _mesh_2_5_io_dOutput_bits;
    dIn_29_bits <= _mesh_4_5_io_uOutput_bits;
    lIn_26_bits <= _mesh_3_5_io_rOutput_bits;
    uIn_22_bits <= _mesh_2_6_io_dOutput_bits;
    dIn_30_bits <= _mesh_4_6_io_uOutput_bits;
    lIn_27_bits <= _mesh_3_6_io_rOutput_bits;
    uIn_23_bits <= _mesh_2_7_io_dOutput_bits;
    dIn_31_bits <= _mesh_4_7_io_uOutput_bits;
    uIn_24_bits <= _mesh_3_0_io_dOutput_bits;
    dIn_32_bits <= _mesh_5_0_io_uOutput_bits;
    lIn_28_bits <= _mesh_4_0_io_rOutput_bits;
    uIn_25_bits <= _mesh_3_1_io_dOutput_bits;
    dIn_33_bits <= _mesh_5_1_io_uOutput_bits;
    lIn_29_bits <= _mesh_4_1_io_rOutput_bits;
    uIn_26_bits <= _mesh_3_2_io_dOutput_bits;
    dIn_34_bits <= _mesh_5_2_io_uOutput_bits;
    lIn_30_bits <= _mesh_4_2_io_rOutput_bits;
    uIn_27_bits <= _mesh_3_3_io_dOutput_bits;
    dIn_35_bits <= _mesh_5_3_io_uOutput_bits;
    lIn_31_bits <= _mesh_4_3_io_rOutput_bits;
    uIn_28_bits <= _mesh_3_4_io_dOutput_bits;
    dIn_36_bits <= _mesh_5_4_io_uOutput_bits;
    lIn_32_bits <= _mesh_4_4_io_rOutput_bits;
    uIn_29_bits <= _mesh_3_5_io_dOutput_bits;
    dIn_37_bits <= _mesh_5_5_io_uOutput_bits;
    lIn_33_bits <= _mesh_4_5_io_rOutput_bits;
    uIn_30_bits <= _mesh_3_6_io_dOutput_bits;
    dIn_38_bits <= _mesh_5_6_io_uOutput_bits;
    lIn_34_bits <= _mesh_4_6_io_rOutput_bits;
    uIn_31_bits <= _mesh_3_7_io_dOutput_bits;
    dIn_39_bits <= _mesh_5_7_io_uOutput_bits;
    uIn_32_bits <= _mesh_4_0_io_dOutput_bits;
    dIn_40_bits <= _mesh_6_0_io_uOutput_bits;
    lIn_35_bits <= _mesh_5_0_io_rOutput_bits;
    uIn_33_bits <= _mesh_4_1_io_dOutput_bits;
    dIn_41_bits <= _mesh_6_1_io_uOutput_bits;
    lIn_36_bits <= _mesh_5_1_io_rOutput_bits;
    uIn_34_bits <= _mesh_4_2_io_dOutput_bits;
    dIn_42_bits <= _mesh_6_2_io_uOutput_bits;
    lIn_37_bits <= _mesh_5_2_io_rOutput_bits;
    uIn_35_bits <= _mesh_4_3_io_dOutput_bits;
    dIn_43_bits <= _mesh_6_3_io_uOutput_bits;
    lIn_38_bits <= _mesh_5_3_io_rOutput_bits;
    uIn_36_bits <= _mesh_4_4_io_dOutput_bits;
    dIn_44_bits <= _mesh_6_4_io_uOutput_bits;
    lIn_39_bits <= _mesh_5_4_io_rOutput_bits;
    uIn_37_bits <= _mesh_4_5_io_dOutput_bits;
    dIn_45_bits <= _mesh_6_5_io_uOutput_bits;
    lIn_40_bits <= _mesh_5_5_io_rOutput_bits;
    uIn_38_bits <= _mesh_4_6_io_dOutput_bits;
    dIn_46_bits <= _mesh_6_6_io_uOutput_bits;
    lIn_41_bits <= _mesh_5_6_io_rOutput_bits;
    uIn_39_bits <= _mesh_4_7_io_dOutput_bits;
    dIn_47_bits <= _mesh_6_7_io_uOutput_bits;
    uIn_40_bits <= _mesh_5_0_io_dOutput_bits;
    dIn_48_bits <= _mesh_7_0_io_uOutput_bits;
    lIn_42_bits <= _mesh_6_0_io_rOutput_bits;
    uIn_41_bits <= _mesh_5_1_io_dOutput_bits;
    dIn_49_bits <= _mesh_7_1_io_uOutput_bits;
    lIn_43_bits <= _mesh_6_1_io_rOutput_bits;
    uIn_42_bits <= _mesh_5_2_io_dOutput_bits;
    dIn_50_bits <= _mesh_7_2_io_uOutput_bits;
    lIn_44_bits <= _mesh_6_2_io_rOutput_bits;
    uIn_43_bits <= _mesh_5_3_io_dOutput_bits;
    dIn_51_bits <= _mesh_7_3_io_uOutput_bits;
    lIn_45_bits <= _mesh_6_3_io_rOutput_bits;
    uIn_44_bits <= _mesh_5_4_io_dOutput_bits;
    dIn_52_bits <= _mesh_7_4_io_uOutput_bits;
    lIn_46_bits <= _mesh_6_4_io_rOutput_bits;
    uIn_45_bits <= _mesh_5_5_io_dOutput_bits;
    dIn_53_bits <= _mesh_7_5_io_uOutput_bits;
    lIn_47_bits <= _mesh_6_5_io_rOutput_bits;
    uIn_46_bits <= _mesh_5_6_io_dOutput_bits;
    dIn_54_bits <= _mesh_7_6_io_uOutput_bits;
    lIn_48_bits <= _mesh_6_6_io_rOutput_bits;
    uIn_47_bits <= _mesh_5_7_io_dOutput_bits;
    dIn_55_bits <= _mesh_7_7_io_uOutput_bits;
    uIn_48_bits <= _mesh_6_0_io_dOutput_bits;
    lIn_49_bits <= _mesh_7_0_io_rOutput_bits;
    uIn_49_bits <= _mesh_6_1_io_dOutput_bits;
    lIn_50_bits <= _mesh_7_1_io_rOutput_bits;
    uIn_50_bits <= _mesh_6_2_io_dOutput_bits;
    lIn_51_bits <= _mesh_7_2_io_rOutput_bits;
    uIn_51_bits <= _mesh_6_3_io_dOutput_bits;
    lIn_52_bits <= _mesh_7_3_io_rOutput_bits;
    uIn_52_bits <= _mesh_6_4_io_dOutput_bits;
    lIn_53_bits <= _mesh_7_4_io_rOutput_bits;
    uIn_53_bits <= _mesh_6_5_io_dOutput_bits;
    lIn_54_bits <= _mesh_7_5_io_rOutput_bits;
    uIn_54_bits <= _mesh_6_6_io_dOutput_bits;
    lIn_55_bits <= _mesh_7_6_io_rOutput_bits;
    uIn_55_bits <= _mesh_6_7_io_dOutput_bits;
    cmpIn_bits <= _mesh_0_0_io_uOutput_bits;
    io_accOut_0_REG_bits <= _mesh_7_0_io_dOutput_bits;
    cmpIn_1_bits <= _mesh_0_1_io_uOutput_bits;
    io_accOut_1_REG_bits <= _mesh_7_1_io_dOutput_bits;
    cmpIn_2_bits <= _mesh_0_2_io_uOutput_bits;
    io_accOut_2_REG_bits <= _mesh_7_2_io_dOutput_bits;
    cmpIn_3_bits <= _mesh_0_3_io_uOutput_bits;
    io_accOut_3_REG_bits <= _mesh_7_3_io_dOutput_bits;
    cmpIn_4_bits <= _mesh_0_4_io_uOutput_bits;
    io_accOut_4_REG_bits <= _mesh_7_4_io_dOutput_bits;
    cmpIn_5_bits <= _mesh_0_5_io_uOutput_bits;
    io_accOut_5_REG_bits <= _mesh_7_5_io_dOutput_bits;
    cmpIn_6_bits <= _mesh_0_6_io_uOutput_bits;
    io_accOut_6_REG_bits <= _mesh_7_6_io_dOutput_bits;
    cmpIn_7_bits <= _mesh_0_7_io_uOutput_bits;
    io_accOut_7_REG_bits <= _mesh_7_7_io_dOutput_bits;
  end // always @(posedge)
  CMP cmpArray_0 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_0),
    .io_dInput_bits     (cmpIn_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_0_bits),
    .io_intercept_bits  (io_cmpIntercept_0_bits),
    .io_dOutput_bits    (_cmpArray_0_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_0_bits),
    .io_diffOut_bits    (io_rowDiff_0_bits)
  );
  CMP cmpArray_1 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_1),
    .io_dInput_bits     (cmpIn_1_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_1_bits),
    .io_intercept_bits  (io_cmpIntercept_1_bits),
    .io_dOutput_bits    (_cmpArray_1_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_1_bits),
    .io_diffOut_bits    (io_rowDiff_1_bits)
  );
  CMP cmpArray_2 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_2),
    .io_dInput_bits     (cmpIn_2_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_2_bits),
    .io_intercept_bits  (io_cmpIntercept_2_bits),
    .io_dOutput_bits    (_cmpArray_2_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_2_bits),
    .io_diffOut_bits    (io_rowDiff_2_bits)
  );
  CMP cmpArray_3 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_3),
    .io_dInput_bits     (cmpIn_3_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_3_bits),
    .io_intercept_bits  (io_cmpIntercept_3_bits),
    .io_dOutput_bits    (_cmpArray_3_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_3_bits),
    .io_diffOut_bits    (io_rowDiff_3_bits)
  );
  CMP cmpArray_4 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_4),
    .io_dInput_bits     (cmpIn_4_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_4_bits),
    .io_intercept_bits  (io_cmpIntercept_4_bits),
    .io_dOutput_bits    (_cmpArray_4_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_4_bits),
    .io_diffOut_bits    (io_rowDiff_4_bits)
  );
  CMP cmpArray_5 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_5),
    .io_dInput_bits     (cmpIn_5_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_5_bits),
    .io_intercept_bits  (io_cmpIntercept_5_bits),
    .io_dOutput_bits    (_cmpArray_5_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_5_bits),
    .io_diffOut_bits    (io_rowDiff_5_bits)
  );
  CMP cmpArray_6 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_6),
    .io_dInput_bits     (cmpIn_6_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_6_bits),
    .io_intercept_bits  (io_cmpIntercept_6_bits),
    .io_dOutput_bits    (_cmpArray_6_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_6_bits),
    .io_diffOut_bits    (io_rowDiff_6_bits)
  );
  CMP cmpArray_7 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_7),
    .io_dInput_bits     (cmpIn_7_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_7_bits),
    .io_intercept_bits  (io_cmpIntercept_7_bits),
    .io_dOutput_bits    (_cmpArray_7_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_7_bits),
    .io_diffOut_bits    (io_rowDiff_7_bits)
  );
  PE mesh_0_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_0),
    .io_lInput_bits  (io_leftIn_0_bits),
    .io_uInput_bits  (_cmpArray_0_io_dOutput_bits),
    .io_dInput_bits  (dIn_bits),
    .io_rOutput_bits (_mesh_0_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_0_io_uOutput_bits)
  );
  PE mesh_0_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_1),
    .io_lInput_bits  (lIn_bits),
    .io_uInput_bits  (_cmpArray_1_io_dOutput_bits),
    .io_dInput_bits  (dIn_1_bits),
    .io_rOutput_bits (_mesh_0_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_1_io_uOutput_bits)
  );
  PE mesh_0_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_2),
    .io_lInput_bits  (lIn_1_bits),
    .io_uInput_bits  (_cmpArray_2_io_dOutput_bits),
    .io_dInput_bits  (dIn_2_bits),
    .io_rOutput_bits (_mesh_0_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_2_io_uOutput_bits)
  );
  PE mesh_0_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_3),
    .io_lInput_bits  (lIn_2_bits),
    .io_uInput_bits  (_cmpArray_3_io_dOutput_bits),
    .io_dInput_bits  (dIn_3_bits),
    .io_rOutput_bits (_mesh_0_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_3_io_uOutput_bits)
  );
  PE mesh_0_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_4),
    .io_lInput_bits  (lIn_3_bits),
    .io_uInput_bits  (_cmpArray_4_io_dOutput_bits),
    .io_dInput_bits  (dIn_4_bits),
    .io_rOutput_bits (_mesh_0_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_4_io_uOutput_bits)
  );
  PE mesh_0_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_5),
    .io_lInput_bits  (lIn_4_bits),
    .io_uInput_bits  (_cmpArray_5_io_dOutput_bits),
    .io_dInput_bits  (dIn_5_bits),
    .io_rOutput_bits (_mesh_0_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_5_io_uOutput_bits)
  );
  PE mesh_0_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_6),
    .io_lInput_bits  (lIn_5_bits),
    .io_uInput_bits  (_cmpArray_6_io_dOutput_bits),
    .io_dInput_bits  (dIn_6_bits),
    .io_rOutput_bits (_mesh_0_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_6_io_uOutput_bits)
  );
  PE mesh_0_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_7),
    .io_lInput_bits  (lIn_6_bits),
    .io_uInput_bits  (_cmpArray_7_io_dOutput_bits),
    .io_dInput_bits  (dIn_7_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_0_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_7_io_uOutput_bits)
  );
  PE mesh_1_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_0),
    .io_lInput_bits  (io_leftIn_1_bits),
    .io_uInput_bits  (uIn_bits),
    .io_dInput_bits  (dIn_8_bits),
    .io_rOutput_bits (_mesh_1_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_0_io_uOutput_bits)
  );
  PE mesh_1_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_1),
    .io_lInput_bits  (lIn_7_bits),
    .io_uInput_bits  (uIn_1_bits),
    .io_dInput_bits  (dIn_9_bits),
    .io_rOutput_bits (_mesh_1_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_1_io_uOutput_bits)
  );
  PE mesh_1_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_2),
    .io_lInput_bits  (lIn_8_bits),
    .io_uInput_bits  (uIn_2_bits),
    .io_dInput_bits  (dIn_10_bits),
    .io_rOutput_bits (_mesh_1_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_2_io_uOutput_bits)
  );
  PE mesh_1_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_3),
    .io_lInput_bits  (lIn_9_bits),
    .io_uInput_bits  (uIn_3_bits),
    .io_dInput_bits  (dIn_11_bits),
    .io_rOutput_bits (_mesh_1_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_3_io_uOutput_bits)
  );
  PE mesh_1_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_4),
    .io_lInput_bits  (lIn_10_bits),
    .io_uInput_bits  (uIn_4_bits),
    .io_dInput_bits  (dIn_12_bits),
    .io_rOutput_bits (_mesh_1_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_4_io_uOutput_bits)
  );
  PE mesh_1_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_5),
    .io_lInput_bits  (lIn_11_bits),
    .io_uInput_bits  (uIn_5_bits),
    .io_dInput_bits  (dIn_13_bits),
    .io_rOutput_bits (_mesh_1_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_5_io_uOutput_bits)
  );
  PE mesh_1_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_6),
    .io_lInput_bits  (lIn_12_bits),
    .io_uInput_bits  (uIn_6_bits),
    .io_dInput_bits  (dIn_14_bits),
    .io_rOutput_bits (_mesh_1_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_6_io_uOutput_bits)
  );
  PE mesh_1_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_7),
    .io_lInput_bits  (lIn_13_bits),
    .io_uInput_bits  (uIn_7_bits),
    .io_dInput_bits  (dIn_15_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_1_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_7_io_uOutput_bits)
  );
  PE mesh_2_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_0),
    .io_lInput_bits  (io_leftIn_2_bits),
    .io_uInput_bits  (uIn_8_bits),
    .io_dInput_bits  (dIn_16_bits),
    .io_rOutput_bits (_mesh_2_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_0_io_uOutput_bits)
  );
  PE mesh_2_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_1),
    .io_lInput_bits  (lIn_14_bits),
    .io_uInput_bits  (uIn_9_bits),
    .io_dInput_bits  (dIn_17_bits),
    .io_rOutput_bits (_mesh_2_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_1_io_uOutput_bits)
  );
  PE mesh_2_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_2),
    .io_lInput_bits  (lIn_15_bits),
    .io_uInput_bits  (uIn_10_bits),
    .io_dInput_bits  (dIn_18_bits),
    .io_rOutput_bits (_mesh_2_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_2_io_uOutput_bits)
  );
  PE mesh_2_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_3),
    .io_lInput_bits  (lIn_16_bits),
    .io_uInput_bits  (uIn_11_bits),
    .io_dInput_bits  (dIn_19_bits),
    .io_rOutput_bits (_mesh_2_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_3_io_uOutput_bits)
  );
  PE mesh_2_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_4),
    .io_lInput_bits  (lIn_17_bits),
    .io_uInput_bits  (uIn_12_bits),
    .io_dInput_bits  (dIn_20_bits),
    .io_rOutput_bits (_mesh_2_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_4_io_uOutput_bits)
  );
  PE mesh_2_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_5),
    .io_lInput_bits  (lIn_18_bits),
    .io_uInput_bits  (uIn_13_bits),
    .io_dInput_bits  (dIn_21_bits),
    .io_rOutput_bits (_mesh_2_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_5_io_uOutput_bits)
  );
  PE mesh_2_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_6),
    .io_lInput_bits  (lIn_19_bits),
    .io_uInput_bits  (uIn_14_bits),
    .io_dInput_bits  (dIn_22_bits),
    .io_rOutput_bits (_mesh_2_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_6_io_uOutput_bits)
  );
  PE mesh_2_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_7),
    .io_lInput_bits  (lIn_20_bits),
    .io_uInput_bits  (uIn_15_bits),
    .io_dInput_bits  (dIn_23_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_2_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_7_io_uOutput_bits)
  );
  PE mesh_3_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_0),
    .io_lInput_bits  (io_leftIn_3_bits),
    .io_uInput_bits  (uIn_16_bits),
    .io_dInput_bits  (dIn_24_bits),
    .io_rOutput_bits (_mesh_3_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_0_io_uOutput_bits)
  );
  PE mesh_3_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_1),
    .io_lInput_bits  (lIn_21_bits),
    .io_uInput_bits  (uIn_17_bits),
    .io_dInput_bits  (dIn_25_bits),
    .io_rOutput_bits (_mesh_3_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_1_io_uOutput_bits)
  );
  PE mesh_3_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_2),
    .io_lInput_bits  (lIn_22_bits),
    .io_uInput_bits  (uIn_18_bits),
    .io_dInput_bits  (dIn_26_bits),
    .io_rOutput_bits (_mesh_3_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_2_io_uOutput_bits)
  );
  PE mesh_3_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_3),
    .io_lInput_bits  (lIn_23_bits),
    .io_uInput_bits  (uIn_19_bits),
    .io_dInput_bits  (dIn_27_bits),
    .io_rOutput_bits (_mesh_3_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_3_io_uOutput_bits)
  );
  PE mesh_3_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_4),
    .io_lInput_bits  (lIn_24_bits),
    .io_uInput_bits  (uIn_20_bits),
    .io_dInput_bits  (dIn_28_bits),
    .io_rOutput_bits (_mesh_3_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_4_io_uOutput_bits)
  );
  PE mesh_3_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_5),
    .io_lInput_bits  (lIn_25_bits),
    .io_uInput_bits  (uIn_21_bits),
    .io_dInput_bits  (dIn_29_bits),
    .io_rOutput_bits (_mesh_3_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_5_io_uOutput_bits)
  );
  PE mesh_3_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_6),
    .io_lInput_bits  (lIn_26_bits),
    .io_uInput_bits  (uIn_22_bits),
    .io_dInput_bits  (dIn_30_bits),
    .io_rOutput_bits (_mesh_3_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_6_io_uOutput_bits)
  );
  PE mesh_3_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_7),
    .io_lInput_bits  (lIn_27_bits),
    .io_uInput_bits  (uIn_23_bits),
    .io_dInput_bits  (dIn_31_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_3_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_7_io_uOutput_bits)
  );
  PE mesh_4_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_0),
    .io_lInput_bits  (io_leftIn_4_bits),
    .io_uInput_bits  (uIn_24_bits),
    .io_dInput_bits  (dIn_32_bits),
    .io_rOutput_bits (_mesh_4_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_4_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_0_io_uOutput_bits)
  );
  PE mesh_4_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_1),
    .io_lInput_bits  (lIn_28_bits),
    .io_uInput_bits  (uIn_25_bits),
    .io_dInput_bits  (dIn_33_bits),
    .io_rOutput_bits (_mesh_4_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_4_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_1_io_uOutput_bits)
  );
  PE mesh_4_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_2),
    .io_lInput_bits  (lIn_29_bits),
    .io_uInput_bits  (uIn_26_bits),
    .io_dInput_bits  (dIn_34_bits),
    .io_rOutput_bits (_mesh_4_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_4_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_2_io_uOutput_bits)
  );
  PE mesh_4_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_3),
    .io_lInput_bits  (lIn_30_bits),
    .io_uInput_bits  (uIn_27_bits),
    .io_dInput_bits  (dIn_35_bits),
    .io_rOutput_bits (_mesh_4_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_4_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_3_io_uOutput_bits)
  );
  PE mesh_4_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_4),
    .io_lInput_bits  (lIn_31_bits),
    .io_uInput_bits  (uIn_28_bits),
    .io_dInput_bits  (dIn_36_bits),
    .io_rOutput_bits (_mesh_4_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_4_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_4_io_uOutput_bits)
  );
  PE mesh_4_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_5),
    .io_lInput_bits  (lIn_32_bits),
    .io_uInput_bits  (uIn_29_bits),
    .io_dInput_bits  (dIn_37_bits),
    .io_rOutput_bits (_mesh_4_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_4_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_5_io_uOutput_bits)
  );
  PE mesh_4_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_6),
    .io_lInput_bits  (lIn_33_bits),
    .io_uInput_bits  (uIn_30_bits),
    .io_dInput_bits  (dIn_38_bits),
    .io_rOutput_bits (_mesh_4_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_4_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_6_io_uOutput_bits)
  );
  PE mesh_4_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_4_7),
    .io_lInput_bits  (lIn_34_bits),
    .io_uInput_bits  (uIn_31_bits),
    .io_dInput_bits  (dIn_39_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_4_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_4_7_io_uOutput_bits)
  );
  PE mesh_5_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_0),
    .io_lInput_bits  (io_leftIn_5_bits),
    .io_uInput_bits  (uIn_32_bits),
    .io_dInput_bits  (dIn_40_bits),
    .io_rOutput_bits (_mesh_5_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_5_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_0_io_uOutput_bits)
  );
  PE mesh_5_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_1),
    .io_lInput_bits  (lIn_35_bits),
    .io_uInput_bits  (uIn_33_bits),
    .io_dInput_bits  (dIn_41_bits),
    .io_rOutput_bits (_mesh_5_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_5_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_1_io_uOutput_bits)
  );
  PE mesh_5_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_2),
    .io_lInput_bits  (lIn_36_bits),
    .io_uInput_bits  (uIn_34_bits),
    .io_dInput_bits  (dIn_42_bits),
    .io_rOutput_bits (_mesh_5_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_5_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_2_io_uOutput_bits)
  );
  PE mesh_5_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_3),
    .io_lInput_bits  (lIn_37_bits),
    .io_uInput_bits  (uIn_35_bits),
    .io_dInput_bits  (dIn_43_bits),
    .io_rOutput_bits (_mesh_5_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_5_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_3_io_uOutput_bits)
  );
  PE mesh_5_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_4),
    .io_lInput_bits  (lIn_38_bits),
    .io_uInput_bits  (uIn_36_bits),
    .io_dInput_bits  (dIn_44_bits),
    .io_rOutput_bits (_mesh_5_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_5_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_4_io_uOutput_bits)
  );
  PE mesh_5_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_5),
    .io_lInput_bits  (lIn_39_bits),
    .io_uInput_bits  (uIn_37_bits),
    .io_dInput_bits  (dIn_45_bits),
    .io_rOutput_bits (_mesh_5_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_5_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_5_io_uOutput_bits)
  );
  PE mesh_5_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_6),
    .io_lInput_bits  (lIn_40_bits),
    .io_uInput_bits  (uIn_38_bits),
    .io_dInput_bits  (dIn_46_bits),
    .io_rOutput_bits (_mesh_5_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_5_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_6_io_uOutput_bits)
  );
  PE mesh_5_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_5_7),
    .io_lInput_bits  (lIn_41_bits),
    .io_uInput_bits  (uIn_39_bits),
    .io_dInput_bits  (dIn_47_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_5_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_5_7_io_uOutput_bits)
  );
  PE mesh_6_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_0),
    .io_lInput_bits  (io_leftIn_6_bits),
    .io_uInput_bits  (uIn_40_bits),
    .io_dInput_bits  (dIn_48_bits),
    .io_rOutput_bits (_mesh_6_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_6_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_0_io_uOutput_bits)
  );
  PE mesh_6_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_1),
    .io_lInput_bits  (lIn_42_bits),
    .io_uInput_bits  (uIn_41_bits),
    .io_dInput_bits  (dIn_49_bits),
    .io_rOutput_bits (_mesh_6_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_6_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_1_io_uOutput_bits)
  );
  PE mesh_6_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_2),
    .io_lInput_bits  (lIn_43_bits),
    .io_uInput_bits  (uIn_42_bits),
    .io_dInput_bits  (dIn_50_bits),
    .io_rOutput_bits (_mesh_6_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_6_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_2_io_uOutput_bits)
  );
  PE mesh_6_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_3),
    .io_lInput_bits  (lIn_44_bits),
    .io_uInput_bits  (uIn_43_bits),
    .io_dInput_bits  (dIn_51_bits),
    .io_rOutput_bits (_mesh_6_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_6_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_3_io_uOutput_bits)
  );
  PE mesh_6_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_4),
    .io_lInput_bits  (lIn_45_bits),
    .io_uInput_bits  (uIn_44_bits),
    .io_dInput_bits  (dIn_52_bits),
    .io_rOutput_bits (_mesh_6_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_6_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_4_io_uOutput_bits)
  );
  PE mesh_6_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_5),
    .io_lInput_bits  (lIn_46_bits),
    .io_uInput_bits  (uIn_45_bits),
    .io_dInput_bits  (dIn_53_bits),
    .io_rOutput_bits (_mesh_6_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_6_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_5_io_uOutput_bits)
  );
  PE mesh_6_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_6),
    .io_lInput_bits  (lIn_47_bits),
    .io_uInput_bits  (uIn_46_bits),
    .io_dInput_bits  (dIn_54_bits),
    .io_rOutput_bits (_mesh_6_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_6_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_6_io_uOutput_bits)
  );
  PE mesh_6_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_6_7),
    .io_lInput_bits  (lIn_48_bits),
    .io_uInput_bits  (uIn_47_bits),
    .io_dInput_bits  (dIn_55_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_6_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_6_7_io_uOutput_bits)
  );
  PE mesh_7_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_0),
    .io_lInput_bits  (io_leftIn_7_bits),
    .io_uInput_bits  (uIn_48_bits),
    .io_dInput_bits  (io_bottomIn_0_bits),
    .io_rOutput_bits (_mesh_7_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_7_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_0_io_uOutput_bits)
  );
  PE mesh_7_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_1),
    .io_lInput_bits  (lIn_49_bits),
    .io_uInput_bits  (uIn_49_bits),
    .io_dInput_bits  (io_bottomIn_1_bits),
    .io_rOutput_bits (_mesh_7_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_7_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_1_io_uOutput_bits)
  );
  PE mesh_7_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_2),
    .io_lInput_bits  (lIn_50_bits),
    .io_uInput_bits  (uIn_50_bits),
    .io_dInput_bits  (io_bottomIn_2_bits),
    .io_rOutput_bits (_mesh_7_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_7_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_2_io_uOutput_bits)
  );
  PE mesh_7_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_3),
    .io_lInput_bits  (lIn_51_bits),
    .io_uInput_bits  (uIn_51_bits),
    .io_dInput_bits  (io_bottomIn_3_bits),
    .io_rOutput_bits (_mesh_7_3_io_rOutput_bits),
    .io_dOutput_bits (_mesh_7_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_3_io_uOutput_bits)
  );
  PE mesh_7_4 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_4),
    .io_lInput_bits  (lIn_52_bits),
    .io_uInput_bits  (uIn_52_bits),
    .io_dInput_bits  (io_bottomIn_4_bits),
    .io_rOutput_bits (_mesh_7_4_io_rOutput_bits),
    .io_dOutput_bits (_mesh_7_4_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_4_io_uOutput_bits)
  );
  PE mesh_7_5 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_5),
    .io_lInput_bits  (lIn_53_bits),
    .io_uInput_bits  (uIn_53_bits),
    .io_dInput_bits  (io_bottomIn_5_bits),
    .io_rOutput_bits (_mesh_7_5_io_rOutput_bits),
    .io_dOutput_bits (_mesh_7_5_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_5_io_uOutput_bits)
  );
  PE mesh_7_6 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_6),
    .io_lInput_bits  (lIn_54_bits),
    .io_uInput_bits  (uIn_54_bits),
    .io_dInput_bits  (io_bottomIn_6_bits),
    .io_rOutput_bits (_mesh_7_6_io_rOutput_bits),
    .io_dOutput_bits (_mesh_7_6_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_6_io_uOutput_bits)
  );
  PE mesh_7_7 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_7_7),
    .io_lInput_bits  (lIn_55_bits),
    .io_uInput_bits  (uIn_55_bits),
    .io_dInput_bits  (io_bottomIn_7_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_7_7_io_dOutput_bits),
    .io_uOutput_bits (_mesh_7_7_io_uOutput_bits)
  );
  assign io_accOut_0_bits = io_accOut_0_REG_bits;
  assign io_accOut_1_bits = io_accOut_1_REG_bits;
  assign io_accOut_2_bits = io_accOut_2_REG_bits;
  assign io_accOut_3_bits = io_accOut_3_REG_bits;
  assign io_accOut_4_bits = io_accOut_4_REG_bits;
  assign io_accOut_5_bits = io_accOut_5_REG_bits;
  assign io_accOut_6_bits = io_accOut_6_REG_bits;
  assign io_accOut_7_bits = io_accOut_7_REG_bits;
endmodule

