// Generated by CIRCT firtool-1.140.0
module PE(
  input         clock,
                reset,
  input  [1:0]  io_westOpIn,
  input  [15:0] io_westIn_bits,
                io_northIn_bits,
  output [15:0] io_eastOut_bits,
                io_southOut_bits
);

  wire [15:0] _macOut_mac_z;
  reg  [15:0] regE_bits;
  reg  [15:0] regS_bits;
  reg  [15:0] regW_bits;
  always @(posedge clock) begin
    if (reset) begin
      regE_bits <= 16'h0;
      regS_bits <= 16'h0;
      regW_bits <= 16'h0;
    end
    else begin
      automatic logic _GEN = io_westOpIn == 2'h1;
      if (_GEN | io_westOpIn != 2'h2) begin
      end
      else begin
        regE_bits <= io_westIn_bits;
        regS_bits <= _macOut_mac_z;
      end
      if (_GEN)
        regW_bits <= io_westIn_bits;
    end
  end // always @(posedge)
  DW_fp_mac #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) macOut_mac (
    .a      (regW_bits),
    .b      (io_westIn_bits),
    .c      (io_northIn_bits),
    .rnd    (3'h0),
    .z      (_macOut_mac_z),
    .status (/* unused */)
  );
  assign io_eastOut_bits = io_westOpIn == 2'h1 ? regW_bits : regE_bits;
  assign io_southOut_bits = regS_bits;
endmodule

