// Generated by CIRCT firtool-1.140.0
module CMP(
  input         clock,
                reset,
  input  [2:0]  io_op,
  input  [15:0] io_dInput_bits,
                io_seedOldMax_bits,
                io_intercept_bits,
  output [15:0] io_dOutput_bits,
                io_newMaxOut_bits,
                io_diffOut_bits
);

  wire        _newMax_cmp_agtb;
  reg  [15:0] oldMax_bits;
  reg  [15:0] newMax_bits;
  always @(posedge clock) begin
    if (reset) begin
      oldMax_bits <= 16'hFC00;
      newMax_bits <= 16'hFC00;
    end
    else begin
      automatic logic _GEN = io_op == 3'h1;
      automatic logic _GEN_0;
      _GEN_0 = io_op == 3'h2;
      if (_GEN)
        oldMax_bits <= 16'hFC00;
      else if (_GEN_0)
        oldMax_bits <= io_seedOldMax_bits;
      if (_GEN | _GEN_0)
        newMax_bits <= 16'hFC00;
      else if (io_op == 3'h3 & _newMax_cmp_agtb)
        newMax_bits <= io_dInput_bits;
    end
  end // always @(posedge)
  DW_fp_cmp #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) newMax_cmp (
    .a         (io_dInput_bits),
    .b         (newMax_bits),
    .zctr      (1'h0),
    .aeqb      (/* unused */),
    .altb      (/* unused */),
    .agtb      (_newMax_cmp_agtb),
    .unordered (/* unused */),
    .z0        (/* unused */),
    .z1        (/* unused */),
    .status0   (/* unused */),
    .status1   (/* unused */)
  );
  DW_fp_add #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) io_diffOut_adder (
    .a      (oldMax_bits),
    .b      ({~(newMax_bits[15]), newMax_bits[14:0]}),
    .rnd    (3'h0),
    .z      (io_diffOut_bits),
    .status (/* unused */)
  );
  assign io_dOutput_bits =
    io_op == 3'h6
      ? io_intercept_bits
      : io_op == 3'h5 | io_op != 3'h4 ? 16'h0 : newMax_bits;
  assign io_newMaxOut_bits = newMax_bits;
endmodule

