// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [7:0]  io_west_0_data_bits,
  input  [1:0]  io_west_1_op,
  input  [7:0]  io_west_1_data_bits,
  input  [1:0]  io_west_2_op,
  input  [7:0]  io_west_2_data_bits,
  input  [1:0]  io_west_3_op,
  input  [7:0]  io_west_3_data_bits,
  input  [15:0] io_north_0_bits,
                io_north_1_bits,
                io_north_2_bits,
                io_north_3_bits,
  output [15:0] io_southRaw_0_bits,
                io_southRaw_1_bits,
                io_southRaw_2_bits,
                io_southRaw_3_bits
);

  wire [7:0]  _pes_2_3_io_eastOut_bits;
  wire [7:0]  _pes_1_3_io_eastOut_bits;
  wire [7:0]  _pes_0_3_io_eastOut_bits;
  wire [15:0] _pes_3_2_io_southOut_bits;
  wire [7:0]  _pes_2_2_io_eastOut_bits;
  wire [15:0] _pes_2_2_io_southOut_bits;
  wire [7:0]  _pes_1_2_io_eastOut_bits;
  wire [15:0] _pes_1_2_io_southOut_bits;
  wire [7:0]  _pes_0_2_io_eastOut_bits;
  wire [15:0] _pes_0_2_io_southOut_bits;
  wire [15:0] _pes_3_1_io_southOut_bits;
  wire [7:0]  _pes_2_1_io_eastOut_bits;
  wire [15:0] _pes_2_1_io_southOut_bits;
  wire [7:0]  _pes_1_1_io_eastOut_bits;
  wire [15:0] _pes_1_1_io_southOut_bits;
  wire [7:0]  _pes_0_1_io_eastOut_bits;
  wire [15:0] _pes_0_1_io_southOut_bits;
  wire [15:0] _pes_3_io_southOut_bits;
  wire [7:0]  _pes_2_io_eastOut_bits;
  wire [15:0] _pes_2_io_southOut_bits;
  wire [7:0]  _pes_1_io_eastOut_bits;
  wire [15:0] _pes_1_io_southOut_bits;
  wire [7:0]  _pes_0_io_eastOut_bits;
  wire [15:0] _pes_0_io_southOut_bits;
  PE pes_0 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (io_west_0_data_bits),
    .io_northIn_bits  (io_north_0_bits),
    .io_eastOut_bits  (_pes_0_io_eastOut_bits),
    .io_southOut_bits (_pes_0_io_southOut_bits)
  );
  PE pes_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_0_io_eastOut_bits),
    .io_northIn_bits  (io_north_1_bits),
    .io_eastOut_bits  (_pes_1_io_eastOut_bits),
    .io_southOut_bits (_pes_1_io_southOut_bits)
  );
  PE pes_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_1_io_eastOut_bits),
    .io_northIn_bits  (io_north_2_bits),
    .io_eastOut_bits  (_pes_2_io_eastOut_bits),
    .io_southOut_bits (_pes_2_io_southOut_bits)
  );
  PE pes_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_2_io_eastOut_bits),
    .io_northIn_bits  (io_north_3_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_3_io_southOut_bits)
  );
  PE pes_0_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (io_west_1_data_bits),
    .io_northIn_bits  (_pes_0_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_1_io_eastOut_bits),
    .io_southOut_bits (_pes_0_1_io_southOut_bits)
  );
  PE pes_1_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_0_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_1_io_eastOut_bits),
    .io_southOut_bits (_pes_1_1_io_southOut_bits)
  );
  PE pes_2_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_1_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_1_io_eastOut_bits),
    .io_southOut_bits (_pes_2_1_io_southOut_bits)
  );
  PE pes_3_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_2_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_3_1_io_southOut_bits)
  );
  PE pes_0_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (io_west_2_data_bits),
    .io_northIn_bits  (_pes_0_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_2_io_eastOut_bits),
    .io_southOut_bits (_pes_0_2_io_southOut_bits)
  );
  PE pes_1_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_0_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_2_io_eastOut_bits),
    .io_southOut_bits (_pes_1_2_io_southOut_bits)
  );
  PE pes_2_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_1_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_2_io_eastOut_bits),
    .io_southOut_bits (_pes_2_2_io_southOut_bits)
  );
  PE pes_3_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_2_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_1_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_3_2_io_southOut_bits)
  );
  PE pes_0_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (io_west_3_data_bits),
    .io_northIn_bits  (_pes_0_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_3_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_0_bits)
  );
  PE pes_1_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_0_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_3_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_1_bits)
  );
  PE pes_2_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_1_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_3_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_2_bits)
  );
  PE pes_3_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_2_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_2_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (io_southRaw_3_bits)
  );
endmodule

