// Generated by CIRCT firtool-1.140.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_
module FuseMax2DPE_Verification_Assert();
  `ifndef SYNTHESIS
    always @(posedge FuseMax2DPE.clock) begin
      if (FuseMax2DPE.io_cmd_en
          & (FuseMax2DPE.io_cmd_op == 4'h9 | FuseMax2DPE.io_cmd_op == 4'h7
             | FuseMax2DPE.io_cmd_op == 4'h8) & ~FuseMax2DPE.reset) begin
        if (`ASSERT_VERBOSE_COND_)
          $error("Assertion failed: Division and streamed reduction are only supported in the FuseMax 1D PE\n");
        if (`STOP_COND_)
          $fatal;
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
endmodule

