// Generated by CIRCT firtool-1.140.0
`ifndef layers_PERight_Verification_Assert
  `define layers_PERight_Verification_Assert
  `include "layers-PERight-Verification.sv"
  bind PERight PERight_Verification_Assert verification_assert ();
`endif // not def layers_PERight_Verification_Assert
