// Generated by CIRCT firtool-1.140.0
module PELeft(
  input         clock,
                reset,
  input  [1:0]  io_westOpIn,
  input  [15:0] io_westIn,
  input         io_northOpIn,
  input  [31:0] io_northIn,
  input  [15:0] io_inRightB,
  output [15:0] io_eastOut,
  output [31:0] io_southOut,
                io_outRightP
);

  reg  [15:0] regE;
  reg  [31:0] regS;
  reg  [15:0] regW;
  reg  [15:0] regX;
  wire        computeActive = io_westOpIn == 2'h2;
  always @(posedge clock) begin
    if (reset) begin
      regE <= 16'h0;
      regS <= 32'h0;
      regW <= 16'h0;
      regX <= 16'h0;
    end
    else begin
      automatic logic [3:0][15:0] _GEN = {{io_westIn}, {io_westIn}, {regE}, {regE}};
      regE <= _GEN[io_westOpIn];
      if (computeActive | io_northOpIn)
        regS <=
          (io_northOpIn
             ? {{16{io_northIn[15]}}, io_northIn[15:0]}
             : {{16{regW[15]}}, regW})
          * (io_northOpIn ? {{16{regE[15]}}, regE} : {{16{io_westIn[15]}}, io_westIn})
          + (io_northOpIn ? {{16{io_inRightB[15]}}, io_inRightB} : io_northIn);
      if (io_westOpIn == 2'h1)
        regW <= io_westIn;
      if (io_northOpIn)
        regX <= io_northIn[15:0];
    end
  end // always @(posedge)
  assign io_eastOut = io_westOpIn == 2'h1 ? regW : regE;
  assign io_southOut = io_northOpIn ? {16'h0, regX} : regS;
  assign io_outRightP = regS;
endmodule

