// Generated by CIRCT firtool-1.140.0
module PERight(
  input         clock,
                reset,
  input  [1:0]  io_westOpIn,
  input  [7:0]  io_westIn,
  input         io_northOpIn,
  input  [31:0] io_northIn,
                io_inLeftP,
  output [7:0]  io_eastOut,
  output [31:0] io_southOut,
  output [7:0]  io_outLeftB
);

  reg  [7:0]  regE;
  reg  [31:0] regS;
  reg  [7:0]  regW;
  wire        computeActive = io_westOpIn == 2'h2;
  always @(posedge clock) begin
    if (reset) begin
      regE <= 8'h0;
      regS <= 32'h0;
      regW <= 8'h0;
    end
    else begin
      automatic logic [3:0][7:0] _GEN = {{io_westIn}, {io_westIn}, {regE}, {regE}};
      regE <= _GEN[io_westOpIn];
      if (computeActive | io_northOpIn)
        regS <=
          (io_northOpIn ? 32'h1 : {{24{regW[7]}}, regW})
          * (io_northOpIn
               ? ($signed(io_inLeftP) > -32'sh1 ? io_inLeftP : 32'h0)
               : {{24{io_westIn[7]}}, io_westIn}) + io_northIn;
      if (io_westOpIn == 2'h1)
        regW <= io_westIn;
    end
  end // always @(posedge)
  assign io_eastOut = io_westOpIn == 2'h1 ? regW : regE;
  assign io_southOut = regS;
  assign io_outLeftB = regE;
endmodule

