// Generated by CIRCT firtool-1.140.0
module SystolicAttentionScale(
  input  [1:0]  io_cmd,
  input  [15:0] io_x_bits,
                io_w_bits,
                io_b_bits,
  input         io_coeffEncoded,
  output [15:0] io_out_bits
);

  wire [15:0]      _macOut_mac_z;
  wire [10:0]      split_mant = {|(io_x_bits[14:10]), io_x_bits[9:0]};
  wire [5:0]       _GEN = {1'h0, io_x_bits[14:10]};
  wire [5:0]       _split_exp_T_1 = _GEN - 6'hF;
  wire             _split_T_1 = ~(|(io_x_bits[14:10])) | io_x_bits[14:0] == 15'h0;
  wire             _split_T_2 = $signed(_split_exp_T_1) < 6'sh0;
  wire [10:0]      _split_fracMag_T = split_mant >> 6'h0 - _split_exp_T_1;
  wire             _split_T_3 = $signed(_split_exp_T_1) > 6'sh9;
  wire [73:0]      _split_intMag_T =
    {63'h0, |(io_x_bits[14:10]), io_x_bits[9:0]} << _GEN - 6'h19;
  wire [5:0]       _split_shiftRight_T_1 = 6'hA - _split_exp_T_1;
  wire [15:0]      split_intMag =
    _split_T_1 | _split_T_2
      ? 16'h0
      : _split_T_3 ? _split_intMag_T[15:0] : {5'h0, split_mant >> _split_shiftRight_T_1};
  wire [63:0]      _split_mask_T = 64'h1 << _split_shiftRight_T_1;
  wire [126:0]     _split_fracMag_T_3 =
    {116'h0, _split_mask_T[10:0] - 11'h1 & split_mant} << _split_exp_T_1;
  wire [9:0]       split_2 =
    _split_T_1
      ? 10'h0
      : _split_T_2 ? _split_fracMag_T[9:0] : _split_T_3 ? 10'h0 : _split_fracMag_T_3[9:0];
  wire             split_fracZero = split_2 == 10'h0;
  wire [3:0]       _split_shift_T_5 =
    (split_2[9]
       ? 4'h0
       : split_2[8]
           ? 4'h1
           : split_2[7]
               ? 4'h2
               : split_2[6]
                   ? 4'h3
                   : split_2[5]
                       ? 4'h4
                       : split_2[4]
                           ? 4'h5
                           : split_2[3]
                               ? 4'h6
                               : split_2[2] ? 4'h7 : {3'h4, ~(split_2[1])}) + 4'h1;
  wire [24:0]      _split_mantNorm_T = {15'h0, split_2} << _split_shift_T_5;
  wire             _GEN_0 = io_cmd == 2'h2;
  wire [16:0]      _io_out_adjustedExp_T_1 =
    {12'h0, _macOut_mac_z[14:10]}
    + (io_x_bits[15] ? 17'h0 - {1'h0, split_intMag} : {1'h0, split_intMag});
  wire [3:0][15:0] _GEN_1 =
    {{_macOut_mac_z[14:10] == 5'h0 | (&(_macOut_mac_z[14:10]))
        ? _macOut_mac_z
        : {_macOut_mac_z[15],
           $signed(_io_out_adjustedExp_T_1) < 17'sh1
             ? 15'h0
             : $signed(_io_out_adjustedExp_T_1) > 17'sh1E
                 ? 15'h7C00
                 : {_io_out_adjustedExp_T_1[4:0], _macOut_mac_z[9:0]}}},
     {_macOut_mac_z},
     {_macOut_mac_z},
     {16'h0}};
  DW_fp_mac #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) macOut_mac (
    .a      (io_w_bits),
    .b
      (_GEN_0 | ~(&io_cmd)
         ? io_x_bits
         : {~split_fracZero & io_x_bits[15],
            split_fracZero ? 5'h0 : 5'hF - {1'h0, _split_shift_T_5},
            split_fracZero ? 10'h0 : _split_mantNorm_T[9:0]}),
    .c
      (_GEN_0
         ? io_b_bits
         : (&io_cmd)
             ? (io_coeffEncoded ? {io_b_bits[15], 4'h7, io_b_bits[10:0]} : io_b_bits)
             : 16'h0),
    .rnd    (3'h0),
    .z      (_macOut_mac_z),
    .status (/* unused */)
  );
  assign io_out_bits = _GEN_1[io_cmd];
endmodule

