// Generated by CIRCT firtool-1.140.0
`ifndef layers_FuseMax2DPE_Verification_Assert
  `define layers_FuseMax2DPE_Verification_Assert
  `include "layers-FuseMax2DPE-Verification.sv"
  bind FuseMax2DPE FuseMax2DPE_Verification_Assert verification_assert ();
`endif // not def layers_FuseMax2DPE_Verification_Assert
