// Generated by CIRCT firtool-1.140.0
module OneSaMesh(
  input         clock,
                reset,
  input  [1:0]  io_op_0,
                io_op_1,
                io_op_2,
                io_op_3,
                io_op_4,
                io_op_5,
                io_op_6,
                io_op_7,
  input  [15:0] io_west_0_lanes_0_bits,
                io_west_0_lanes_1_bits,
                io_west_1_lanes_0_bits,
                io_west_1_lanes_1_bits,
                io_west_2_lanes_0_bits,
                io_west_2_lanes_1_bits,
                io_west_3_lanes_0_bits,
                io_west_3_lanes_1_bits,
                io_west_4_lanes_0_bits,
                io_west_4_lanes_1_bits,
                io_west_5_lanes_0_bits,
                io_west_5_lanes_1_bits,
                io_west_6_lanes_0_bits,
                io_west_6_lanes_1_bits,
                io_west_7_lanes_0_bits,
                io_west_7_lanes_1_bits,
                io_north_0_lanes_0_bits,
                io_north_0_lanes_1_bits,
                io_north_1_lanes_0_bits,
                io_north_1_lanes_1_bits,
                io_north_2_lanes_0_bits,
                io_north_2_lanes_1_bits,
                io_north_3_lanes_0_bits,
                io_north_3_lanes_1_bits,
                io_north_4_lanes_0_bits,
                io_north_4_lanes_1_bits,
                io_north_5_lanes_0_bits,
                io_north_5_lanes_1_bits,
                io_north_6_lanes_0_bits,
                io_north_6_lanes_1_bits,
                io_north_7_lanes_0_bits,
                io_north_7_lanes_1_bits,
                io_psum_0_bits,
                io_psum_1_bits,
                io_psum_2_bits,
                io_psum_3_bits,
                io_psum_4_bits,
                io_psum_5_bits,
                io_psum_6_bits,
                io_psum_7_bits,
  output [15:0] io_south_0_bits,
                io_south_1_bits,
                io_south_2_bits,
                io_south_3_bits,
                io_south_4_bits,
                io_south_5_bits,
                io_south_6_bits,
                io_south_7_bits,
                io_diag_0_bits,
                io_diag_1_bits,
                io_diag_2_bits,
                io_diag_3_bits,
                io_diag_4_bits,
                io_diag_5_bits,
                io_diag_6_bits,
                io_diag_7_bits,
                io_diagPairs_0_0_bits,
                io_diagPairs_1_0_bits,
                io_diagPairs_2_0_bits,
                io_diagPairs_3_0_bits,
                io_diagPairs_4_0_bits,
                io_diagPairs_5_0_bits,
                io_diagPairs_6_0_bits,
                io_diagPairs_7_0_bits,
  output        io_diagValid_0,
                io_diagValid_1,
                io_diagValid_2,
                io_diagValid_3,
                io_diagValid_4,
                io_diagValid_5,
                io_diagValid_6,
                io_diagValid_7
);

  wire [15:0] _pes_7_7_io_diagPairsOut_0_bits;
  wire [15:0] _pes_7_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_7_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_7_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_7_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_7_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_7_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_7_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_7_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_7_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_7_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_7_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_7_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_7_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_7_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_7_io_southOut_lanes_0_bits;
  wire [15:0] _pes_6_7_io_southOut_lanes_1_bits;
  wire [15:0] _pes_6_7_io_psumOut_bits;
  wire [15:0] _pes_6_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_6_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_6_io_psumOut_bits;
  wire [15:0] _pes_6_6_io_diagPairsOut_0_bits;
  wire [15:0] _pes_6_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_6_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_5_io_southOut_lanes_0_bits;
  wire [15:0] _pes_6_5_io_southOut_lanes_1_bits;
  wire [15:0] _pes_6_5_io_psumOut_bits;
  wire [15:0] _pes_6_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_6_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_4_io_southOut_lanes_0_bits;
  wire [15:0] _pes_6_4_io_southOut_lanes_1_bits;
  wire [15:0] _pes_6_4_io_psumOut_bits;
  wire [15:0] _pes_6_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_6_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_3_io_southOut_lanes_0_bits;
  wire [15:0] _pes_6_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_6_3_io_psumOut_bits;
  wire [15:0] _pes_6_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_6_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_2_io_southOut_lanes_0_bits;
  wire [15:0] _pes_6_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_6_2_io_psumOut_bits;
  wire [15:0] _pes_6_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_6_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_1_io_southOut_lanes_0_bits;
  wire [15:0] _pes_6_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_6_1_io_psumOut_bits;
  wire [15:0] _pes_6_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_6_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_6_0_io_southOut_lanes_0_bits;
  wire [15:0] _pes_6_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_6_0_io_psumOut_bits;
  wire [15:0] _pes_5_7_io_southOut_lanes_0_bits;
  wire [15:0] _pes_5_7_io_southOut_lanes_1_bits;
  wire [15:0] _pes_5_7_io_psumOut_bits;
  wire [15:0] _pes_5_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_5_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_5_6_io_southOut_lanes_0_bits;
  wire [15:0] _pes_5_6_io_southOut_lanes_1_bits;
  wire [15:0] _pes_5_6_io_psumOut_bits;
  wire [15:0] _pes_5_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_5_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_5_5_io_psumOut_bits;
  wire [15:0] _pes_5_5_io_diagPairsOut_0_bits;
  wire [15:0] _pes_5_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_5_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_5_4_io_southOut_lanes_0_bits;
  wire [15:0] _pes_5_4_io_southOut_lanes_1_bits;
  wire [15:0] _pes_5_4_io_psumOut_bits;
  wire [15:0] _pes_5_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_5_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_5_3_io_southOut_lanes_0_bits;
  wire [15:0] _pes_5_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_5_3_io_psumOut_bits;
  wire [15:0] _pes_5_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_5_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_5_2_io_southOut_lanes_0_bits;
  wire [15:0] _pes_5_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_5_2_io_psumOut_bits;
  wire [15:0] _pes_5_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_5_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_5_1_io_southOut_lanes_0_bits;
  wire [15:0] _pes_5_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_5_1_io_psumOut_bits;
  wire [15:0] _pes_5_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_5_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_5_0_io_southOut_lanes_0_bits;
  wire [15:0] _pes_5_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_5_0_io_psumOut_bits;
  wire [15:0] _pes_4_7_io_southOut_lanes_0_bits;
  wire [15:0] _pes_4_7_io_southOut_lanes_1_bits;
  wire [15:0] _pes_4_7_io_psumOut_bits;
  wire [15:0] _pes_4_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_4_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_4_6_io_southOut_lanes_0_bits;
  wire [15:0] _pes_4_6_io_southOut_lanes_1_bits;
  wire [15:0] _pes_4_6_io_psumOut_bits;
  wire [15:0] _pes_4_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_4_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_4_5_io_southOut_lanes_0_bits;
  wire [15:0] _pes_4_5_io_southOut_lanes_1_bits;
  wire [15:0] _pes_4_5_io_psumOut_bits;
  wire [15:0] _pes_4_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_4_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_4_4_io_psumOut_bits;
  wire [15:0] _pes_4_4_io_diagPairsOut_0_bits;
  wire [15:0] _pes_4_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_4_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_4_3_io_southOut_lanes_0_bits;
  wire [15:0] _pes_4_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_4_3_io_psumOut_bits;
  wire [15:0] _pes_4_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_4_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_4_2_io_southOut_lanes_0_bits;
  wire [15:0] _pes_4_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_4_2_io_psumOut_bits;
  wire [15:0] _pes_4_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_4_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_4_1_io_southOut_lanes_0_bits;
  wire [15:0] _pes_4_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_4_1_io_psumOut_bits;
  wire [15:0] _pes_4_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_4_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_4_0_io_southOut_lanes_0_bits;
  wire [15:0] _pes_4_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_4_0_io_psumOut_bits;
  wire [15:0] _pes_3_7_io_southOut_lanes_0_bits;
  wire [15:0] _pes_3_7_io_southOut_lanes_1_bits;
  wire [15:0] _pes_3_7_io_psumOut_bits;
  wire [15:0] _pes_3_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_3_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_3_6_io_southOut_lanes_0_bits;
  wire [15:0] _pes_3_6_io_southOut_lanes_1_bits;
  wire [15:0] _pes_3_6_io_psumOut_bits;
  wire [15:0] _pes_3_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_3_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_3_5_io_southOut_lanes_0_bits;
  wire [15:0] _pes_3_5_io_southOut_lanes_1_bits;
  wire [15:0] _pes_3_5_io_psumOut_bits;
  wire [15:0] _pes_3_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_3_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_3_4_io_southOut_lanes_0_bits;
  wire [15:0] _pes_3_4_io_southOut_lanes_1_bits;
  wire [15:0] _pes_3_4_io_psumOut_bits;
  wire [15:0] _pes_3_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_3_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_3_3_io_psumOut_bits;
  wire [15:0] _pes_3_3_io_diagPairsOut_0_bits;
  wire [15:0] _pes_3_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_3_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_3_2_io_southOut_lanes_0_bits;
  wire [15:0] _pes_3_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_3_2_io_psumOut_bits;
  wire [15:0] _pes_3_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_3_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_3_1_io_southOut_lanes_0_bits;
  wire [15:0] _pes_3_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_3_1_io_psumOut_bits;
  wire [15:0] _pes_3_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_3_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_3_0_io_southOut_lanes_0_bits;
  wire [15:0] _pes_3_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_3_0_io_psumOut_bits;
  wire [15:0] _pes_2_7_io_southOut_lanes_0_bits;
  wire [15:0] _pes_2_7_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_7_io_psumOut_bits;
  wire [15:0] _pes_2_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_2_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_6_io_southOut_lanes_0_bits;
  wire [15:0] _pes_2_6_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_6_io_psumOut_bits;
  wire [15:0] _pes_2_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_2_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_5_io_southOut_lanes_0_bits;
  wire [15:0] _pes_2_5_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_5_io_psumOut_bits;
  wire [15:0] _pes_2_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_2_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_4_io_southOut_lanes_0_bits;
  wire [15:0] _pes_2_4_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_4_io_psumOut_bits;
  wire [15:0] _pes_2_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_2_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_3_io_southOut_lanes_0_bits;
  wire [15:0] _pes_2_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_3_io_psumOut_bits;
  wire [15:0] _pes_2_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_2_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_2_io_psumOut_bits;
  wire [15:0] _pes_2_2_io_diagPairsOut_0_bits;
  wire [15:0] _pes_2_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_2_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_1_io_southOut_lanes_0_bits;
  wire [15:0] _pes_2_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_1_io_psumOut_bits;
  wire [15:0] _pes_2_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_2_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_2_0_io_southOut_lanes_0_bits;
  wire [15:0] _pes_2_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_2_0_io_psumOut_bits;
  wire [15:0] _pes_1_7_io_southOut_lanes_0_bits;
  wire [15:0] _pes_1_7_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_7_io_psumOut_bits;
  wire [15:0] _pes_1_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_1_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_6_io_southOut_lanes_0_bits;
  wire [15:0] _pes_1_6_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_6_io_psumOut_bits;
  wire [15:0] _pes_1_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_1_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_5_io_southOut_lanes_0_bits;
  wire [15:0] _pes_1_5_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_5_io_psumOut_bits;
  wire [15:0] _pes_1_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_1_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_4_io_southOut_lanes_0_bits;
  wire [15:0] _pes_1_4_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_4_io_psumOut_bits;
  wire [15:0] _pes_1_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_1_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_3_io_southOut_lanes_0_bits;
  wire [15:0] _pes_1_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_3_io_psumOut_bits;
  wire [15:0] _pes_1_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_1_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_2_io_southOut_lanes_0_bits;
  wire [15:0] _pes_1_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_2_io_psumOut_bits;
  wire [15:0] _pes_1_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_1_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_1_io_psumOut_bits;
  wire [15:0] _pes_1_1_io_diagPairsOut_0_bits;
  wire [15:0] _pes_1_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_1_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_1_0_io_southOut_lanes_0_bits;
  wire [15:0] _pes_1_0_io_southOut_lanes_1_bits;
  wire [15:0] _pes_1_0_io_psumOut_bits;
  wire [15:0] _pes_0_7_io_southOut_lanes_0_bits;
  wire [15:0] _pes_0_7_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_7_io_psumOut_bits;
  wire [15:0] _pes_0_6_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_0_6_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_6_io_southOut_lanes_0_bits;
  wire [15:0] _pes_0_6_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_6_io_psumOut_bits;
  wire [15:0] _pes_0_5_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_0_5_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_5_io_southOut_lanes_0_bits;
  wire [15:0] _pes_0_5_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_5_io_psumOut_bits;
  wire [15:0] _pes_0_4_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_0_4_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_4_io_southOut_lanes_0_bits;
  wire [15:0] _pes_0_4_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_4_io_psumOut_bits;
  wire [15:0] _pes_0_3_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_0_3_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_3_io_southOut_lanes_0_bits;
  wire [15:0] _pes_0_3_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_3_io_psumOut_bits;
  wire [15:0] _pes_0_2_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_0_2_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_2_io_southOut_lanes_0_bits;
  wire [15:0] _pes_0_2_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_2_io_psumOut_bits;
  wire [15:0] _pes_0_1_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_0_1_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_1_io_southOut_lanes_0_bits;
  wire [15:0] _pes_0_1_io_southOut_lanes_1_bits;
  wire [15:0] _pes_0_1_io_psumOut_bits;
  wire [15:0] _pes_0_0_io_eastOut_lanes_0_bits;
  wire [15:0] _pes_0_0_io_eastOut_lanes_1_bits;
  wire [15:0] _pes_0_0_io_psumOut_bits;
  wire [15:0] _pes_0_0_io_diagPairsOut_0_bits;
  OneSaPEComputation pes_0_0 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_0),
    .io_westIn_lanes_0_bits  (io_west_0_lanes_0_bits),
    .io_westIn_lanes_1_bits  (io_west_0_lanes_1_bits),
    .io_northIn_lanes_0_bits (io_north_0_lanes_0_bits),
    .io_northIn_lanes_1_bits (io_north_0_lanes_1_bits),
    .io_psumIn_bits          (io_psum_0_bits),
    .io_eastOut_lanes_0_bits (_pes_0_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_0_0_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_0_0_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_0_0_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_0_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_1_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_1_lanes_1_bits),
    .io_psumIn_bits           (io_psum_1_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_1_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_2_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_2_lanes_1_bits),
    .io_psumIn_bits           (io_psum_2_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_2_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_3_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_3_lanes_1_bits),
    .io_psumIn_bits           (io_psum_3_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_3_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_4 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_4_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_4_lanes_1_bits),
    .io_psumIn_bits           (io_psum_4_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_4_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_4_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_4_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_4_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_5 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_5_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_5_lanes_1_bits),
    .io_psumIn_bits           (io_psum_5_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_5_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_5_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_5_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_5_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_6 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_6_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_6_lanes_1_bits),
    .io_psumIn_bits           (io_psum_6_bits),
    .io_eastOut_lanes_0_bits  (_pes_0_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_0_6_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_0_6_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_6_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_6_io_psumOut_bits)
  );
  OneSaPETransmission pes_0_7 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_0),
    .io_westIn_lanes_0_bits   (_pes_0_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_0_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (io_north_7_lanes_0_bits),
    .io_northIn_lanes_1_bits  (io_north_7_lanes_1_bits),
    .io_psumIn_bits           (io_psum_7_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_0_7_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_0_7_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_0_7_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (io_west_1_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_1_lanes_1_bits),
    .io_northIn_lanes_0_bits  (16'h0),
    .io_northIn_lanes_1_bits  (16'h0),
    .io_psumIn_bits           (_pes_0_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_0_io_psumOut_bits)
  );
  OneSaPEComputation pes_1_1 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_1),
    .io_westIn_lanes_0_bits  (_pes_1_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_1_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_0_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_0_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_0_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_1_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_1_1_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_1_1_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_1_1_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_1_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_2_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_3_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_4 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_4_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_4_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_4_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_4_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_4_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_4_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_4_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_5 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_5_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_5_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_5_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_5_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_5_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_5_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_5_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_6 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_6_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_6_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_6_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_1_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_1_6_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_1_6_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_6_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_6_io_psumOut_bits)
  );
  OneSaPETransmission pes_1_7 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_1),
    .io_westIn_lanes_0_bits   (_pes_1_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_1_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_0_7_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_0_7_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_0_7_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_1_7_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_1_7_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_1_7_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (io_west_2_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_2_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_0_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (16'h0),
    .io_northIn_lanes_1_bits  (16'h0),
    .io_psumIn_bits           (_pes_1_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_1_io_psumOut_bits)
  );
  OneSaPEComputation pes_2_2 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_2),
    .io_westIn_lanes_0_bits  (_pes_2_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_2_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_1_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_1_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_1_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_2_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_2_2_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_2_2_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_2_2_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_2_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_3_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_4 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_4_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_4_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_4_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_4_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_4_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_4_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_4_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_5 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_5_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_5_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_5_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_5_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_5_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_5_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_5_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_6 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_6_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_6_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_6_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_2_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_2_6_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_2_6_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_6_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_6_io_psumOut_bits)
  );
  OneSaPETransmission pes_2_7 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_2),
    .io_westIn_lanes_0_bits   (_pes_2_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_2_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_1_7_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_1_7_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_1_7_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_2_7_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_2_7_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_2_7_io_psumOut_bits)
  );
  OneSaPETransmission pes_3_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (io_west_3_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_3_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_3_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_3_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_3_0_io_psumOut_bits)
  );
  OneSaPETransmission pes_3_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_3_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_3_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_3_1_io_psumOut_bits)
  );
  OneSaPETransmission pes_3_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (16'h0),
    .io_northIn_lanes_1_bits  (16'h0),
    .io_psumIn_bits           (_pes_2_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_3_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_3_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_3_2_io_psumOut_bits)
  );
  OneSaPEComputation pes_3_3 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_3),
    .io_westIn_lanes_0_bits  (_pes_3_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_3_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_2_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_2_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_2_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_3_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_3_3_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_3_3_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_3_3_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_3_4 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_4_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_4_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_4_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_4_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_3_4_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_3_4_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_3_4_io_psumOut_bits)
  );
  OneSaPETransmission pes_3_5 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_5_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_5_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_5_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_5_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_3_5_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_3_5_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_3_5_io_psumOut_bits)
  );
  OneSaPETransmission pes_3_6 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_6_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_6_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_6_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_3_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_3_6_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_3_6_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_3_6_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_3_6_io_psumOut_bits)
  );
  OneSaPETransmission pes_3_7 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_3),
    .io_westIn_lanes_0_bits   (_pes_3_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_3_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_2_7_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_2_7_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_2_7_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_3_7_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_3_7_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_3_7_io_psumOut_bits)
  );
  OneSaPETransmission pes_4_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_4),
    .io_westIn_lanes_0_bits   (io_west_4_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_4_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_3_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_3_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_3_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_4_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_4_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_4_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_4_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_4_0_io_psumOut_bits)
  );
  OneSaPETransmission pes_4_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_4),
    .io_westIn_lanes_0_bits   (_pes_4_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_4_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_3_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_3_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_3_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_4_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_4_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_4_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_4_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_4_1_io_psumOut_bits)
  );
  OneSaPETransmission pes_4_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_4),
    .io_westIn_lanes_0_bits   (_pes_4_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_4_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_3_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_3_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_3_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_4_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_4_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_4_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_4_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_4_2_io_psumOut_bits)
  );
  OneSaPETransmission pes_4_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_4),
    .io_westIn_lanes_0_bits   (_pes_4_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_4_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (16'h0),
    .io_northIn_lanes_1_bits  (16'h0),
    .io_psumIn_bits           (_pes_3_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_4_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_4_3_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_4_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_4_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_4_3_io_psumOut_bits)
  );
  OneSaPEComputation pes_4_4 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_4),
    .io_westIn_lanes_0_bits  (_pes_4_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_4_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_3_4_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_3_4_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_3_4_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_4_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_4_4_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_4_4_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_4_4_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_4_5 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_4),
    .io_westIn_lanes_0_bits   (_pes_4_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_4_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_3_5_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_3_5_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_3_5_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_4_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_4_5_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_4_5_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_4_5_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_4_5_io_psumOut_bits)
  );
  OneSaPETransmission pes_4_6 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_4),
    .io_westIn_lanes_0_bits   (_pes_4_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_4_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_3_6_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_3_6_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_3_6_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_4_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_4_6_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_4_6_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_4_6_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_4_6_io_psumOut_bits)
  );
  OneSaPETransmission pes_4_7 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_4),
    .io_westIn_lanes_0_bits   (_pes_4_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_4_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_3_7_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_3_7_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_3_7_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_4_7_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_4_7_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_4_7_io_psumOut_bits)
  );
  OneSaPETransmission pes_5_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_5),
    .io_westIn_lanes_0_bits   (io_west_5_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_5_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_4_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_4_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_4_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_5_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_5_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_5_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_5_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_5_0_io_psumOut_bits)
  );
  OneSaPETransmission pes_5_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_5),
    .io_westIn_lanes_0_bits   (_pes_5_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_5_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_4_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_4_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_4_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_5_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_5_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_5_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_5_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_5_1_io_psumOut_bits)
  );
  OneSaPETransmission pes_5_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_5),
    .io_westIn_lanes_0_bits   (_pes_5_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_5_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_4_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_4_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_4_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_5_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_5_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_5_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_5_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_5_2_io_psumOut_bits)
  );
  OneSaPETransmission pes_5_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_5),
    .io_westIn_lanes_0_bits   (_pes_5_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_5_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_4_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_4_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_4_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_5_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_5_3_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_5_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_5_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_5_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_5_4 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_5),
    .io_westIn_lanes_0_bits   (_pes_5_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_5_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (16'h0),
    .io_northIn_lanes_1_bits  (16'h0),
    .io_psumIn_bits           (_pes_4_4_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_5_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_5_4_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_5_4_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_5_4_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_5_4_io_psumOut_bits)
  );
  OneSaPEComputation pes_5_5 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_5),
    .io_westIn_lanes_0_bits  (_pes_5_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_5_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_4_5_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_4_5_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_4_5_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_5_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_5_5_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_5_5_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_5_5_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_5_6 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_5),
    .io_westIn_lanes_0_bits   (_pes_5_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_5_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_4_6_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_4_6_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_4_6_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_5_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_5_6_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_5_6_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_5_6_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_5_6_io_psumOut_bits)
  );
  OneSaPETransmission pes_5_7 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_5),
    .io_westIn_lanes_0_bits   (_pes_5_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_5_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_4_7_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_4_7_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_4_7_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_5_7_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_5_7_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_5_7_io_psumOut_bits)
  );
  OneSaPETransmission pes_6_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_6),
    .io_westIn_lanes_0_bits   (io_west_6_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_6_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_5_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_5_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_5_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_6_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_6_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_6_0_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_6_0_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_6_0_io_psumOut_bits)
  );
  OneSaPETransmission pes_6_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_6),
    .io_westIn_lanes_0_bits   (_pes_6_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_6_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_5_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_5_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_5_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_6_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_6_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_6_1_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_6_1_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_6_1_io_psumOut_bits)
  );
  OneSaPETransmission pes_6_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_6),
    .io_westIn_lanes_0_bits   (_pes_6_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_6_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_5_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_5_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_5_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_6_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_6_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_6_2_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_6_2_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_6_2_io_psumOut_bits)
  );
  OneSaPETransmission pes_6_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_6),
    .io_westIn_lanes_0_bits   (_pes_6_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_6_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_5_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_5_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_5_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_6_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_6_3_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_6_3_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_6_3_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_6_3_io_psumOut_bits)
  );
  OneSaPETransmission pes_6_4 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_6),
    .io_westIn_lanes_0_bits   (_pes_6_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_6_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_5_4_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_5_4_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_5_4_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_6_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_6_4_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_6_4_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_6_4_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_6_4_io_psumOut_bits)
  );
  OneSaPETransmission pes_6_5 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_6),
    .io_westIn_lanes_0_bits   (_pes_6_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_6_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (16'h0),
    .io_northIn_lanes_1_bits  (16'h0),
    .io_psumIn_bits           (_pes_5_5_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_6_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_6_5_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (_pes_6_5_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_6_5_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_6_5_io_psumOut_bits)
  );
  OneSaPEComputation pes_6_6 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_6),
    .io_westIn_lanes_0_bits  (_pes_6_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_6_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_5_6_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_5_6_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_5_6_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (_pes_6_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits (_pes_6_6_io_eastOut_lanes_1_bits),
    .io_psumOut_bits         (_pes_6_6_io_psumOut_bits),
    .io_diagPairsOut_0_bits  (_pes_6_6_io_diagPairsOut_0_bits)
  );
  OneSaPETransmission pes_6_7 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_6),
    .io_westIn_lanes_0_bits   (_pes_6_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_6_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_5_7_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_5_7_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_5_7_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (/* unused */),
    .io_eastOut_lanes_1_bits  (/* unused */),
    .io_southOut_lanes_0_bits (_pes_6_7_io_southOut_lanes_0_bits),
    .io_southOut_lanes_1_bits (_pes_6_7_io_southOut_lanes_1_bits),
    .io_psumOut_bits          (_pes_6_7_io_psumOut_bits)
  );
  OneSaPETransmission pes_7_0 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_7),
    .io_westIn_lanes_0_bits   (io_west_7_lanes_0_bits),
    .io_westIn_lanes_1_bits   (io_west_7_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_6_0_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_6_0_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_6_0_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_7_0_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_7_0_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_0_bits)
  );
  OneSaPETransmission pes_7_1 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_7),
    .io_westIn_lanes_0_bits   (_pes_7_0_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_7_0_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_6_1_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_6_1_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_6_1_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_7_1_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_7_1_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_1_bits)
  );
  OneSaPETransmission pes_7_2 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_7),
    .io_westIn_lanes_0_bits   (_pes_7_1_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_7_1_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_6_2_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_6_2_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_6_2_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_7_2_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_7_2_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_2_bits)
  );
  OneSaPETransmission pes_7_3 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_7),
    .io_westIn_lanes_0_bits   (_pes_7_2_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_7_2_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_6_3_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_6_3_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_6_3_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_7_3_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_7_3_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_3_bits)
  );
  OneSaPETransmission pes_7_4 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_7),
    .io_westIn_lanes_0_bits   (_pes_7_3_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_7_3_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_6_4_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_6_4_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_6_4_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_7_4_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_7_4_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_4_bits)
  );
  OneSaPETransmission pes_7_5 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_7),
    .io_westIn_lanes_0_bits   (_pes_7_4_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_7_4_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (_pes_6_5_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits  (_pes_6_5_io_southOut_lanes_1_bits),
    .io_psumIn_bits           (_pes_6_5_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_7_5_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_7_5_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_5_bits)
  );
  OneSaPETransmission pes_7_6 (
    .clock                    (clock),
    .reset                    (reset),
    .io_op                    (io_op_7),
    .io_westIn_lanes_0_bits   (_pes_7_5_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits   (_pes_7_5_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits  (16'h0),
    .io_northIn_lanes_1_bits  (16'h0),
    .io_psumIn_bits           (_pes_6_6_io_psumOut_bits),
    .io_eastOut_lanes_0_bits  (_pes_7_6_io_eastOut_lanes_0_bits),
    .io_eastOut_lanes_1_bits  (_pes_7_6_io_eastOut_lanes_1_bits),
    .io_southOut_lanes_0_bits (/* unused */),
    .io_southOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits          (io_south_6_bits)
  );
  OneSaPEComputation pes_7_7 (
    .clock                   (clock),
    .reset                   (reset),
    .io_op                   (io_op_7),
    .io_westIn_lanes_0_bits  (_pes_7_6_io_eastOut_lanes_0_bits),
    .io_westIn_lanes_1_bits  (_pes_7_6_io_eastOut_lanes_1_bits),
    .io_northIn_lanes_0_bits (_pes_6_7_io_southOut_lanes_0_bits),
    .io_northIn_lanes_1_bits (_pes_6_7_io_southOut_lanes_1_bits),
    .io_psumIn_bits          (_pes_6_7_io_psumOut_bits),
    .io_eastOut_lanes_0_bits (/* unused */),
    .io_eastOut_lanes_1_bits (/* unused */),
    .io_psumOut_bits         (io_south_7_bits),
    .io_diagPairsOut_0_bits  (_pes_7_7_io_diagPairsOut_0_bits)
  );
  assign io_diag_0_bits = _pes_0_0_io_diagPairsOut_0_bits;
  assign io_diag_1_bits = _pes_1_1_io_diagPairsOut_0_bits;
  assign io_diag_2_bits = _pes_2_2_io_diagPairsOut_0_bits;
  assign io_diag_3_bits = _pes_3_3_io_diagPairsOut_0_bits;
  assign io_diag_4_bits = _pes_4_4_io_diagPairsOut_0_bits;
  assign io_diag_5_bits = _pes_5_5_io_diagPairsOut_0_bits;
  assign io_diag_6_bits = _pes_6_6_io_diagPairsOut_0_bits;
  assign io_diag_7_bits = _pes_7_7_io_diagPairsOut_0_bits;
  assign io_diagPairs_0_0_bits = _pes_0_0_io_diagPairsOut_0_bits;
  assign io_diagPairs_1_0_bits = _pes_1_1_io_diagPairsOut_0_bits;
  assign io_diagPairs_2_0_bits = _pes_2_2_io_diagPairsOut_0_bits;
  assign io_diagPairs_3_0_bits = _pes_3_3_io_diagPairsOut_0_bits;
  assign io_diagPairs_4_0_bits = _pes_4_4_io_diagPairsOut_0_bits;
  assign io_diagPairs_5_0_bits = _pes_5_5_io_diagPairsOut_0_bits;
  assign io_diagPairs_6_0_bits = _pes_6_6_io_diagPairsOut_0_bits;
  assign io_diagPairs_7_0_bits = _pes_7_7_io_diagPairsOut_0_bits;
  assign io_diagValid_0 = &io_op_0;
  assign io_diagValid_1 = &io_op_1;
  assign io_diagValid_2 = &io_op_2;
  assign io_diagValid_3 = &io_op_3;
  assign io_diagValid_4 = &io_op_4;
  assign io_diagValid_5 = &io_op_5;
  assign io_diagValid_6 = &io_op_6;
  assign io_diagValid_7 = &io_op_7;
endmodule

