// Generated by CIRCT firtool-1.140.0
`ifndef layers_FuseMax2DArray_Verification_Assume
  `define layers_FuseMax2DArray_Verification_Assume
  `include "layers-FuseMax2DArray-Verification.sv"
`endif // not def layers_FuseMax2DArray_Verification_Assume
