// Generated by CIRCT firtool-1.140.0
module PELeft(
  input         clock,
                reset,
  input  [1:0]  io_westOpIn,
  input  [7:0]  io_westIn_bits,
  input         io_northOpIn,
  input  [15:0] io_northIn_bits,
  input  [7:0]  io_inRightB_bits,
  output [7:0]  io_eastOut_bits,
  output [15:0] io_southOut_bits,
                io_outRightP_bits
);

  wire [15:0] _sharedMacOut_mac_z;
  reg  [7:0]  regE_bits;
  reg  [15:0] regS_bits;
  reg  [7:0]  regW_bits;
  reg  [7:0]  regX_bits;
  wire        computeActive = io_westOpIn == 2'h2;
  always @(posedge clock) begin
    if (reset) begin
      regE_bits <= 8'h0;
      regS_bits <= 16'h0;
      regW_bits <= 8'h0;
      regX_bits <= 8'h0;
    end
    else begin
      automatic logic [3:0][7:0] _GEN =
        {{io_westIn_bits}, {io_westIn_bits}, {regE_bits}, {regE_bits}};
      regE_bits <= _GEN[io_westOpIn];
      if (computeActive | io_northOpIn)
        regS_bits <= _sharedMacOut_mac_z;
      if (io_westOpIn == 2'h1)
        regW_bits <= io_westIn_bits;
      if (io_northOpIn)
        regX_bits <= io_northIn_bits[7:0];
    end
  end // always @(posedge)
  DW_fp_mac #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) sharedMacOut_mac (
    .a      ({io_northOpIn ? io_northIn_bits[7:0] : regW_bits, 8'h0}),
    .b      ({io_northOpIn ? regE_bits : io_westIn_bits, 8'h0}),
    .c      (io_northOpIn ? {io_inRightB_bits, 8'h0} : io_northIn_bits),
    .rnd    (3'h0),
    .z      (_sharedMacOut_mac_z),
    .status (/* unused */)
  );
  assign io_eastOut_bits = io_westOpIn == 2'h1 ? regW_bits : regE_bits;
  assign io_southOut_bits = io_northOpIn ? {8'h0, regX_bits} : regS_bits;
  assign io_outRightP_bits = regS_bits;
endmodule

