// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [7:0]  io_west_0_data_bits,
  input  [1:0]  io_west_1_op,
  input  [7:0]  io_west_1_data_bits,
  input  [1:0]  io_west_2_op,
  input  [7:0]  io_west_2_data_bits,
  input  [1:0]  io_west_3_op,
  input  [7:0]  io_west_3_data_bits,
  input         io_stripNorth_0_0_op,
  input  [15:0] io_stripNorth_0_0_data_bits,
  input         io_stripNorth_0_1_op,
  input  [15:0] io_stripNorth_0_1_data_bits,
  input         io_stripNorth_1_0_op,
  input  [15:0] io_stripNorth_1_0_data_bits,
  input         io_stripNorth_1_1_op,
  input  [15:0] io_stripNorth_1_1_data_bits,
  input         io_stripNorth_2_0_op,
  input  [15:0] io_stripNorth_2_0_data_bits,
  input         io_stripNorth_2_1_op,
  input  [15:0] io_stripNorth_2_1_data_bits,
  input         io_stripNorth_3_0_op,
  input  [15:0] io_stripNorth_3_0_data_bits,
  input         io_stripNorth_3_1_op,
  input  [15:0] io_stripNorth_3_1_data_bits,
  output [15:0] io_gemmSouthRaw_0_bits,
                io_gemmSouthRaw_1_bits,
                io_gemmSouthRaw_2_bits,
                io_gemmSouthRaw_3_bits,
                io_pinnSouthRaw_0_bits,
                io_pinnSouthRaw_1_bits,
                io_pinnSouthRaw_2_bits,
                io_pinnSouthRaw_3_bits
);

  wire [15:0] _pairs_1_3_io_southOut_1_bits;
  wire [7:0]  _pairs_0_3_io_eastOut_bits;
  wire [15:0] _pairs_0_3_io_southOut_1_bits;
  wire [15:0] _pairs_1_2_io_southOut_0_bits;
  wire [15:0] _pairs_1_2_io_southOut_1_bits;
  wire [7:0]  _pairs_0_2_io_eastOut_bits;
  wire [15:0] _pairs_0_2_io_southOut_0_bits;
  wire [15:0] _pairs_0_2_io_southOut_1_bits;
  wire [15:0] _pairs_1_1_io_southOut_0_bits;
  wire [15:0] _pairs_1_1_io_southOut_1_bits;
  wire [7:0]  _pairs_0_1_io_eastOut_bits;
  wire [15:0] _pairs_0_1_io_southOut_0_bits;
  wire [15:0] _pairs_0_1_io_southOut_1_bits;
  wire [15:0] _pairs_1_io_southOut_0_bits;
  wire [15:0] _pairs_1_io_southOut_1_bits;
  wire [7:0]  _pairs_0_io_eastOut_bits;
  wire [15:0] _pairs_0_io_southOut_0_bits;
  wire [15:0] _pairs_0_io_southOut_1_bits;
  StripPair pairs_0 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_0_op),
    .io_westIn_bits     (io_west_0_data_bits),
    .io_northOpIn       (io_stripNorth_0_0_op),
    .io_northIn_0_bits  (io_stripNorth_0_0_op ? io_stripNorth_0_0_data_bits : 16'h0),
    .io_northIn_1_bits  (16'h0),
    .io_eastOut_bits    (_pairs_0_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_io_southOut_1_bits)
  );
  StripPair pairs_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_0_op),
    .io_westIn_bits     (_pairs_0_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_0_1_op),
    .io_northIn_0_bits  (io_stripNorth_0_1_op ? io_stripNorth_0_1_data_bits : 16'h0),
    .io_northIn_1_bits  (16'h0),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_io_southOut_1_bits)
  );
  StripPair pairs_0_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_1_op),
    .io_westIn_bits     (io_west_1_data_bits),
    .io_northOpIn       (io_stripNorth_1_0_op),
    .io_northIn_0_bits  (_pairs_0_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_1_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_1_io_southOut_1_bits)
  );
  StripPair pairs_1_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_1_op),
    .io_westIn_bits     (_pairs_0_1_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_1_1_op),
    .io_northIn_0_bits  (_pairs_1_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_1_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_1_io_southOut_1_bits)
  );
  StripPair pairs_0_2 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_2_op),
    .io_westIn_bits     (io_west_2_data_bits),
    .io_northOpIn       (io_stripNorth_2_0_op),
    .io_northIn_0_bits
      (io_stripNorth_2_0_op
         ? io_stripNorth_2_0_data_bits
         : _pairs_0_1_io_southOut_0_bits),
    .io_northIn_1_bits  (io_stripNorth_2_0_op ? 16'h0 : _pairs_0_1_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_2_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_2_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_2_io_southOut_1_bits)
  );
  StripPair pairs_1_2 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_2_op),
    .io_westIn_bits     (_pairs_0_2_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_2_1_op),
    .io_northIn_0_bits
      (io_stripNorth_2_1_op
         ? io_stripNorth_2_1_data_bits
         : _pairs_1_1_io_southOut_0_bits),
    .io_northIn_1_bits  (io_stripNorth_2_1_op ? 16'h0 : _pairs_1_1_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_1_2_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_2_io_southOut_1_bits)
  );
  StripPair pairs_0_3 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_3_op),
    .io_westIn_bits     (io_west_3_data_bits),
    .io_northOpIn       (io_stripNorth_3_0_op),
    .io_northIn_0_bits  (_pairs_0_2_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_2_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_3_io_eastOut_bits),
    .io_southOut_0_bits (io_gemmSouthRaw_0_bits),
    .io_southOut_1_bits (_pairs_0_3_io_southOut_1_bits)
  );
  StripPair pairs_1_3 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_3_op),
    .io_westIn_bits     (_pairs_0_3_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_3_1_op),
    .io_northIn_0_bits  (_pairs_1_2_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_2_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (io_gemmSouthRaw_2_bits),
    .io_southOut_1_bits (_pairs_1_3_io_southOut_1_bits)
  );
  assign io_gemmSouthRaw_1_bits = _pairs_0_3_io_southOut_1_bits;
  assign io_gemmSouthRaw_3_bits = _pairs_1_3_io_southOut_1_bits;
  assign io_pinnSouthRaw_0_bits = _pairs_0_1_io_southOut_1_bits;
  assign io_pinnSouthRaw_1_bits = _pairs_1_1_io_southOut_1_bits;
  assign io_pinnSouthRaw_2_bits = _pairs_0_3_io_southOut_1_bits;
  assign io_pinnSouthRaw_3_bits = _pairs_1_3_io_southOut_1_bits;
endmodule

