// Generated by CIRCT firtool-1.140.0
module PELeft(
  input         clock,
                reset,
  input  [1:0]  io_westOpIn,
  input  [7:0]  io_westIn,
  input         io_northOpIn,
  input  [31:0] io_northIn,
  input  [7:0]  io_inRightB,
  output [7:0]  io_eastOut,
  output [31:0] io_southOut,
                io_outRightP
);

  reg  [7:0]  regE;
  reg  [31:0] regS;
  reg  [7:0]  regW;
  reg  [7:0]  regX;
  wire        computeActive = io_westOpIn == 2'h2;
  always @(posedge clock) begin
    if (reset) begin
      regE <= 8'h0;
      regS <= 32'h0;
      regW <= 8'h0;
      regX <= 8'h0;
    end
    else begin
      automatic logic [3:0][7:0] _GEN = {{io_westIn}, {io_westIn}, {regE}, {regE}};
      regE <= _GEN[io_westOpIn];
      if (computeActive | io_northOpIn)
        regS <=
          (io_northOpIn ? {{24{io_northIn[7]}}, io_northIn[7:0]} : {{24{regW[7]}}, regW})
          * (io_northOpIn ? {{24{regE[7]}}, regE} : {{24{io_westIn[7]}}, io_westIn})
          + (io_northOpIn ? {{24{io_inRightB[7]}}, io_inRightB} : io_northIn);
      if (io_westOpIn == 2'h1)
        regW <= io_westIn;
      if (io_northOpIn)
        regX <= io_northIn[7:0];
    end
  end // always @(posedge)
  assign io_eastOut = io_westOpIn == 2'h1 ? regW : regE;
  assign io_southOut = io_northOpIn ? {24'h0, regX} : regS;
  assign io_outRightP = regS;
endmodule

