// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [15:0] io_west_0_data_bits,
  input  [1:0]  io_west_1_op,
  input  [15:0] io_west_1_data_bits,
  input  [1:0]  io_west_2_op,
  input  [15:0] io_west_2_data_bits,
  input  [1:0]  io_west_3_op,
  input  [15:0] io_west_3_data_bits,
  input  [1:0]  io_west_4_op,
  input  [15:0] io_west_4_data_bits,
  input  [1:0]  io_west_5_op,
  input  [15:0] io_west_5_data_bits,
  input  [1:0]  io_west_6_op,
  input  [15:0] io_west_6_data_bits,
  input  [1:0]  io_west_7_op,
  input  [15:0] io_west_7_data_bits,
  input         io_stripNorth_0_0_op,
  input  [15:0] io_stripNorth_0_0_data_bits,
  input         io_stripNorth_0_1_op,
  input  [15:0] io_stripNorth_0_1_data_bits,
  input         io_stripNorth_0_2_op,
  input  [15:0] io_stripNorth_0_2_data_bits,
  input         io_stripNorth_0_3_op,
  input  [15:0] io_stripNorth_0_3_data_bits,
  input         io_stripNorth_1_0_op,
  input  [15:0] io_stripNorth_1_0_data_bits,
  input         io_stripNorth_1_1_op,
  input  [15:0] io_stripNorth_1_1_data_bits,
  input         io_stripNorth_1_2_op,
  input  [15:0] io_stripNorth_1_2_data_bits,
  input         io_stripNorth_1_3_op,
  input  [15:0] io_stripNorth_1_3_data_bits,
  input         io_stripNorth_2_0_op,
  input  [15:0] io_stripNorth_2_0_data_bits,
  input         io_stripNorth_2_1_op,
  input  [15:0] io_stripNorth_2_1_data_bits,
  input         io_stripNorth_2_2_op,
  input  [15:0] io_stripNorth_2_2_data_bits,
  input         io_stripNorth_2_3_op,
  input  [15:0] io_stripNorth_2_3_data_bits,
  input         io_stripNorth_3_0_op,
  input  [15:0] io_stripNorth_3_0_data_bits,
  input         io_stripNorth_3_1_op,
  input  [15:0] io_stripNorth_3_1_data_bits,
  input         io_stripNorth_3_2_op,
  input  [15:0] io_stripNorth_3_2_data_bits,
  input         io_stripNorth_3_3_op,
  input  [15:0] io_stripNorth_3_3_data_bits,
  input         io_stripNorth_4_0_op,
  input  [15:0] io_stripNorth_4_0_data_bits,
  input         io_stripNorth_4_1_op,
  input  [15:0] io_stripNorth_4_1_data_bits,
  input         io_stripNorth_4_2_op,
  input  [15:0] io_stripNorth_4_2_data_bits,
  input         io_stripNorth_4_3_op,
  input  [15:0] io_stripNorth_4_3_data_bits,
  input         io_stripNorth_5_0_op,
  input  [15:0] io_stripNorth_5_0_data_bits,
  input         io_stripNorth_5_1_op,
  input  [15:0] io_stripNorth_5_1_data_bits,
  input         io_stripNorth_5_2_op,
  input  [15:0] io_stripNorth_5_2_data_bits,
  input         io_stripNorth_5_3_op,
  input  [15:0] io_stripNorth_5_3_data_bits,
  input         io_stripNorth_6_0_op,
  input  [15:0] io_stripNorth_6_0_data_bits,
  input         io_stripNorth_6_1_op,
  input  [15:0] io_stripNorth_6_1_data_bits,
  input         io_stripNorth_6_2_op,
  input  [15:0] io_stripNorth_6_2_data_bits,
  input         io_stripNorth_6_3_op,
  input  [15:0] io_stripNorth_6_3_data_bits,
  input         io_stripNorth_7_0_op,
  input  [15:0] io_stripNorth_7_0_data_bits,
  input         io_stripNorth_7_1_op,
  input  [15:0] io_stripNorth_7_1_data_bits,
  input         io_stripNorth_7_2_op,
  input  [15:0] io_stripNorth_7_2_data_bits,
  input         io_stripNorth_7_3_op,
  input  [15:0] io_stripNorth_7_3_data_bits,
  output [15:0] io_gemmSouthRaw_0_bits,
                io_gemmSouthRaw_1_bits,
                io_gemmSouthRaw_2_bits,
                io_gemmSouthRaw_3_bits,
                io_gemmSouthRaw_4_bits,
                io_gemmSouthRaw_5_bits,
                io_gemmSouthRaw_6_bits,
                io_gemmSouthRaw_7_bits,
                io_pinnSouthRaw_0_bits,
                io_pinnSouthRaw_1_bits,
                io_pinnSouthRaw_2_bits,
                io_pinnSouthRaw_3_bits,
                io_pinnSouthRaw_4_bits,
                io_pinnSouthRaw_5_bits,
                io_pinnSouthRaw_6_bits,
                io_pinnSouthRaw_7_bits
);

  wire [15:0] _pairs_3_7_io_southOut_1_bits;
  wire [15:0] _pairs_2_7_io_eastOut_bits;
  wire [15:0] _pairs_2_7_io_southOut_1_bits;
  wire [15:0] _pairs_1_7_io_eastOut_bits;
  wire [15:0] _pairs_1_7_io_southOut_1_bits;
  wire [15:0] _pairs_0_7_io_eastOut_bits;
  wire [15:0] _pairs_0_7_io_southOut_1_bits;
  wire [15:0] _pairs_3_6_io_southOut_0_bits;
  wire [15:0] _pairs_3_6_io_southOut_1_bits;
  wire [15:0] _pairs_2_6_io_eastOut_bits;
  wire [15:0] _pairs_2_6_io_southOut_0_bits;
  wire [15:0] _pairs_2_6_io_southOut_1_bits;
  wire [15:0] _pairs_1_6_io_eastOut_bits;
  wire [15:0] _pairs_1_6_io_southOut_0_bits;
  wire [15:0] _pairs_1_6_io_southOut_1_bits;
  wire [15:0] _pairs_0_6_io_eastOut_bits;
  wire [15:0] _pairs_0_6_io_southOut_0_bits;
  wire [15:0] _pairs_0_6_io_southOut_1_bits;
  wire [15:0] _pairs_3_5_io_southOut_0_bits;
  wire [15:0] _pairs_3_5_io_southOut_1_bits;
  wire [15:0] _pairs_2_5_io_eastOut_bits;
  wire [15:0] _pairs_2_5_io_southOut_0_bits;
  wire [15:0] _pairs_2_5_io_southOut_1_bits;
  wire [15:0] _pairs_1_5_io_eastOut_bits;
  wire [15:0] _pairs_1_5_io_southOut_0_bits;
  wire [15:0] _pairs_1_5_io_southOut_1_bits;
  wire [15:0] _pairs_0_5_io_eastOut_bits;
  wire [15:0] _pairs_0_5_io_southOut_0_bits;
  wire [15:0] _pairs_0_5_io_southOut_1_bits;
  wire [15:0] _pairs_3_4_io_southOut_0_bits;
  wire [15:0] _pairs_3_4_io_southOut_1_bits;
  wire [15:0] _pairs_2_4_io_eastOut_bits;
  wire [15:0] _pairs_2_4_io_southOut_0_bits;
  wire [15:0] _pairs_2_4_io_southOut_1_bits;
  wire [15:0] _pairs_1_4_io_eastOut_bits;
  wire [15:0] _pairs_1_4_io_southOut_0_bits;
  wire [15:0] _pairs_1_4_io_southOut_1_bits;
  wire [15:0] _pairs_0_4_io_eastOut_bits;
  wire [15:0] _pairs_0_4_io_southOut_0_bits;
  wire [15:0] _pairs_0_4_io_southOut_1_bits;
  wire [15:0] _pairs_3_3_io_southOut_0_bits;
  wire [15:0] _pairs_3_3_io_southOut_1_bits;
  wire [15:0] _pairs_2_3_io_eastOut_bits;
  wire [15:0] _pairs_2_3_io_southOut_0_bits;
  wire [15:0] _pairs_2_3_io_southOut_1_bits;
  wire [15:0] _pairs_1_3_io_eastOut_bits;
  wire [15:0] _pairs_1_3_io_southOut_0_bits;
  wire [15:0] _pairs_1_3_io_southOut_1_bits;
  wire [15:0] _pairs_0_3_io_eastOut_bits;
  wire [15:0] _pairs_0_3_io_southOut_0_bits;
  wire [15:0] _pairs_0_3_io_southOut_1_bits;
  wire [15:0] _pairs_3_2_io_southOut_0_bits;
  wire [15:0] _pairs_3_2_io_southOut_1_bits;
  wire [15:0] _pairs_2_2_io_eastOut_bits;
  wire [15:0] _pairs_2_2_io_southOut_0_bits;
  wire [15:0] _pairs_2_2_io_southOut_1_bits;
  wire [15:0] _pairs_1_2_io_eastOut_bits;
  wire [15:0] _pairs_1_2_io_southOut_0_bits;
  wire [15:0] _pairs_1_2_io_southOut_1_bits;
  wire [15:0] _pairs_0_2_io_eastOut_bits;
  wire [15:0] _pairs_0_2_io_southOut_0_bits;
  wire [15:0] _pairs_0_2_io_southOut_1_bits;
  wire [15:0] _pairs_3_1_io_southOut_0_bits;
  wire [15:0] _pairs_3_1_io_southOut_1_bits;
  wire [15:0] _pairs_2_1_io_eastOut_bits;
  wire [15:0] _pairs_2_1_io_southOut_0_bits;
  wire [15:0] _pairs_2_1_io_southOut_1_bits;
  wire [15:0] _pairs_1_1_io_eastOut_bits;
  wire [15:0] _pairs_1_1_io_southOut_0_bits;
  wire [15:0] _pairs_1_1_io_southOut_1_bits;
  wire [15:0] _pairs_0_1_io_eastOut_bits;
  wire [15:0] _pairs_0_1_io_southOut_0_bits;
  wire [15:0] _pairs_0_1_io_southOut_1_bits;
  wire [15:0] _pairs_3_io_southOut_0_bits;
  wire [15:0] _pairs_3_io_southOut_1_bits;
  wire [15:0] _pairs_2_io_eastOut_bits;
  wire [15:0] _pairs_2_io_southOut_0_bits;
  wire [15:0] _pairs_2_io_southOut_1_bits;
  wire [15:0] _pairs_1_io_eastOut_bits;
  wire [15:0] _pairs_1_io_southOut_0_bits;
  wire [15:0] _pairs_1_io_southOut_1_bits;
  wire [15:0] _pairs_0_io_eastOut_bits;
  wire [15:0] _pairs_0_io_southOut_0_bits;
  wire [15:0] _pairs_0_io_southOut_1_bits;
  StripPair pairs_0 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_0_op),
    .io_westIn_bits     (io_west_0_data_bits),
    .io_northOpIn       (io_stripNorth_0_0_op),
    .io_northIn_0_bits  (io_stripNorth_0_0_op ? io_stripNorth_0_0_data_bits : 16'h0),
    .io_northIn_1_bits  (16'h0),
    .io_eastOut_bits    (_pairs_0_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_io_southOut_1_bits)
  );
  StripPair pairs_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_0_op),
    .io_westIn_bits     (_pairs_0_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_0_1_op),
    .io_northIn_0_bits  (io_stripNorth_0_1_op ? io_stripNorth_0_1_data_bits : 16'h0),
    .io_northIn_1_bits  (16'h0),
    .io_eastOut_bits    (_pairs_1_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_io_southOut_1_bits)
  );
  StripPair pairs_2 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_0_op),
    .io_westIn_bits     (_pairs_1_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_0_2_op),
    .io_northIn_0_bits  (io_stripNorth_0_2_op ? io_stripNorth_0_2_data_bits : 16'h0),
    .io_northIn_1_bits  (16'h0),
    .io_eastOut_bits    (_pairs_2_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_2_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_2_io_southOut_1_bits)
  );
  StripPair pairs_3 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_0_op),
    .io_westIn_bits     (_pairs_2_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_0_3_op),
    .io_northIn_0_bits  (io_stripNorth_0_3_op ? io_stripNorth_0_3_data_bits : 16'h0),
    .io_northIn_1_bits  (16'h0),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_3_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_3_io_southOut_1_bits)
  );
  StripPair pairs_0_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_1_op),
    .io_westIn_bits     (io_west_1_data_bits),
    .io_northOpIn       (io_stripNorth_1_0_op),
    .io_northIn_0_bits  (_pairs_0_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_1_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_1_io_southOut_1_bits)
  );
  StripPair pairs_1_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_1_op),
    .io_westIn_bits     (_pairs_0_1_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_1_1_op),
    .io_northIn_0_bits  (_pairs_1_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_1_1_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_1_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_1_io_southOut_1_bits)
  );
  StripPair pairs_2_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_1_op),
    .io_westIn_bits     (_pairs_1_1_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_1_2_op),
    .io_northIn_0_bits  (_pairs_2_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_2_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_2_1_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_2_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_2_1_io_southOut_1_bits)
  );
  StripPair pairs_3_1 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_1_op),
    .io_westIn_bits     (_pairs_2_1_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_1_3_op),
    .io_northIn_0_bits  (_pairs_3_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_3_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_3_1_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_3_1_io_southOut_1_bits)
  );
  StripPair pairs_0_2 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_2_op),
    .io_westIn_bits     (io_west_2_data_bits),
    .io_northOpIn       (io_stripNorth_2_0_op),
    .io_northIn_0_bits  (_pairs_0_1_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_1_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_2_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_2_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_2_io_southOut_1_bits)
  );
  StripPair pairs_1_2 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_2_op),
    .io_westIn_bits     (_pairs_0_2_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_2_1_op),
    .io_northIn_0_bits  (_pairs_1_1_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_1_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_1_2_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_1_2_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_2_io_southOut_1_bits)
  );
  StripPair pairs_2_2 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_2_op),
    .io_westIn_bits     (_pairs_1_2_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_2_2_op),
    .io_northIn_0_bits  (_pairs_2_1_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_2_1_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_2_2_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_2_2_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_2_2_io_southOut_1_bits)
  );
  StripPair pairs_3_2 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_2_op),
    .io_westIn_bits     (_pairs_2_2_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_2_3_op),
    .io_northIn_0_bits  (_pairs_3_1_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_3_1_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_3_2_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_3_2_io_southOut_1_bits)
  );
  StripPair pairs_0_3 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_3_op),
    .io_westIn_bits     (io_west_3_data_bits),
    .io_northOpIn       (io_stripNorth_3_0_op),
    .io_northIn_0_bits  (_pairs_0_2_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_2_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_3_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_3_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_3_io_southOut_1_bits)
  );
  StripPair pairs_1_3 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_3_op),
    .io_westIn_bits     (_pairs_0_3_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_3_1_op),
    .io_northIn_0_bits  (_pairs_1_2_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_2_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_1_3_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_1_3_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_3_io_southOut_1_bits)
  );
  StripPair pairs_2_3 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_3_op),
    .io_westIn_bits     (_pairs_1_3_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_3_2_op),
    .io_northIn_0_bits  (_pairs_2_2_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_2_2_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_2_3_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_2_3_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_2_3_io_southOut_1_bits)
  );
  StripPair pairs_3_3 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_3_op),
    .io_westIn_bits     (_pairs_2_3_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_3_3_op),
    .io_northIn_0_bits  (_pairs_3_2_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_3_2_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_3_3_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_3_3_io_southOut_1_bits)
  );
  StripPair pairs_0_4 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_4_op),
    .io_westIn_bits     (io_west_4_data_bits),
    .io_northOpIn       (io_stripNorth_4_0_op),
    .io_northIn_0_bits
      (io_stripNorth_4_0_op
         ? io_stripNorth_4_0_data_bits
         : _pairs_0_3_io_southOut_0_bits),
    .io_northIn_1_bits  (io_stripNorth_4_0_op ? 16'h0 : _pairs_0_3_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_4_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_4_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_4_io_southOut_1_bits)
  );
  StripPair pairs_1_4 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_4_op),
    .io_westIn_bits     (_pairs_0_4_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_4_1_op),
    .io_northIn_0_bits
      (io_stripNorth_4_1_op
         ? io_stripNorth_4_1_data_bits
         : _pairs_1_3_io_southOut_0_bits),
    .io_northIn_1_bits  (io_stripNorth_4_1_op ? 16'h0 : _pairs_1_3_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_1_4_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_1_4_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_4_io_southOut_1_bits)
  );
  StripPair pairs_2_4 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_4_op),
    .io_westIn_bits     (_pairs_1_4_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_4_2_op),
    .io_northIn_0_bits
      (io_stripNorth_4_2_op
         ? io_stripNorth_4_2_data_bits
         : _pairs_2_3_io_southOut_0_bits),
    .io_northIn_1_bits  (io_stripNorth_4_2_op ? 16'h0 : _pairs_2_3_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_2_4_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_2_4_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_2_4_io_southOut_1_bits)
  );
  StripPair pairs_3_4 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_4_op),
    .io_westIn_bits     (_pairs_2_4_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_4_3_op),
    .io_northIn_0_bits
      (io_stripNorth_4_3_op
         ? io_stripNorth_4_3_data_bits
         : _pairs_3_3_io_southOut_0_bits),
    .io_northIn_1_bits  (io_stripNorth_4_3_op ? 16'h0 : _pairs_3_3_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_3_4_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_3_4_io_southOut_1_bits)
  );
  StripPair pairs_0_5 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_5_op),
    .io_westIn_bits     (io_west_5_data_bits),
    .io_northOpIn       (io_stripNorth_5_0_op),
    .io_northIn_0_bits  (_pairs_0_4_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_4_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_5_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_5_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_5_io_southOut_1_bits)
  );
  StripPair pairs_1_5 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_5_op),
    .io_westIn_bits     (_pairs_0_5_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_5_1_op),
    .io_northIn_0_bits  (_pairs_1_4_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_4_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_1_5_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_1_5_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_5_io_southOut_1_bits)
  );
  StripPair pairs_2_5 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_5_op),
    .io_westIn_bits     (_pairs_1_5_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_5_2_op),
    .io_northIn_0_bits  (_pairs_2_4_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_2_4_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_2_5_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_2_5_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_2_5_io_southOut_1_bits)
  );
  StripPair pairs_3_5 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_5_op),
    .io_westIn_bits     (_pairs_2_5_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_5_3_op),
    .io_northIn_0_bits  (_pairs_3_4_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_3_4_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_3_5_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_3_5_io_southOut_1_bits)
  );
  StripPair pairs_0_6 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_6_op),
    .io_westIn_bits     (io_west_6_data_bits),
    .io_northOpIn       (io_stripNorth_6_0_op),
    .io_northIn_0_bits  (_pairs_0_5_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_5_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_6_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_0_6_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_0_6_io_southOut_1_bits)
  );
  StripPair pairs_1_6 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_6_op),
    .io_westIn_bits     (_pairs_0_6_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_6_1_op),
    .io_northIn_0_bits  (_pairs_1_5_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_5_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_1_6_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_1_6_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_1_6_io_southOut_1_bits)
  );
  StripPair pairs_2_6 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_6_op),
    .io_westIn_bits     (_pairs_1_6_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_6_2_op),
    .io_northIn_0_bits  (_pairs_2_5_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_2_5_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_2_6_io_eastOut_bits),
    .io_southOut_0_bits (_pairs_2_6_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_2_6_io_southOut_1_bits)
  );
  StripPair pairs_3_6 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_6_op),
    .io_westIn_bits     (_pairs_2_6_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_6_3_op),
    .io_northIn_0_bits  (_pairs_3_5_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_3_5_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (_pairs_3_6_io_southOut_0_bits),
    .io_southOut_1_bits (_pairs_3_6_io_southOut_1_bits)
  );
  StripPair pairs_0_7 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_7_op),
    .io_westIn_bits     (io_west_7_data_bits),
    .io_northOpIn       (io_stripNorth_7_0_op),
    .io_northIn_0_bits  (_pairs_0_6_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_0_6_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_0_7_io_eastOut_bits),
    .io_southOut_0_bits (io_gemmSouthRaw_0_bits),
    .io_southOut_1_bits (_pairs_0_7_io_southOut_1_bits)
  );
  StripPair pairs_1_7 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_7_op),
    .io_westIn_bits     (_pairs_0_7_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_7_1_op),
    .io_northIn_0_bits  (_pairs_1_6_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_1_6_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_1_7_io_eastOut_bits),
    .io_southOut_0_bits (io_gemmSouthRaw_2_bits),
    .io_southOut_1_bits (_pairs_1_7_io_southOut_1_bits)
  );
  StripPair pairs_2_7 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_7_op),
    .io_westIn_bits     (_pairs_1_7_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_7_2_op),
    .io_northIn_0_bits  (_pairs_2_6_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_2_6_io_southOut_1_bits),
    .io_eastOut_bits    (_pairs_2_7_io_eastOut_bits),
    .io_southOut_0_bits (io_gemmSouthRaw_4_bits),
    .io_southOut_1_bits (_pairs_2_7_io_southOut_1_bits)
  );
  StripPair pairs_3_7 (
    .clock              (clock),
    .reset              (reset),
    .io_westOpIn        (io_west_7_op),
    .io_westIn_bits     (_pairs_2_7_io_eastOut_bits),
    .io_northOpIn       (io_stripNorth_7_3_op),
    .io_northIn_0_bits  (_pairs_3_6_io_southOut_0_bits),
    .io_northIn_1_bits  (_pairs_3_6_io_southOut_1_bits),
    .io_eastOut_bits    (/* unused */),
    .io_southOut_0_bits (io_gemmSouthRaw_6_bits),
    .io_southOut_1_bits (_pairs_3_7_io_southOut_1_bits)
  );
  assign io_gemmSouthRaw_1_bits = _pairs_0_7_io_southOut_1_bits;
  assign io_gemmSouthRaw_3_bits = _pairs_1_7_io_southOut_1_bits;
  assign io_gemmSouthRaw_5_bits = _pairs_2_7_io_southOut_1_bits;
  assign io_gemmSouthRaw_7_bits = _pairs_3_7_io_southOut_1_bits;
  assign io_pinnSouthRaw_0_bits = _pairs_0_3_io_southOut_1_bits;
  assign io_pinnSouthRaw_1_bits = _pairs_1_3_io_southOut_1_bits;
  assign io_pinnSouthRaw_2_bits = _pairs_2_3_io_southOut_1_bits;
  assign io_pinnSouthRaw_3_bits = _pairs_3_3_io_southOut_1_bits;
  assign io_pinnSouthRaw_4_bits = _pairs_0_7_io_southOut_1_bits;
  assign io_pinnSouthRaw_5_bits = _pairs_1_7_io_southOut_1_bits;
  assign io_pinnSouthRaw_6_bits = _pairs_2_7_io_southOut_1_bits;
  assign io_pinnSouthRaw_7_bits = _pairs_3_7_io_southOut_1_bits;
endmodule

