// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [15:0] io_west_0_data_bits,
  input  [1:0]  io_west_1_op,
  input  [15:0] io_west_1_data_bits,
  input  [1:0]  io_west_2_op,
  input  [15:0] io_west_2_data_bits,
  input  [1:0]  io_west_3_op,
  input  [15:0] io_west_3_data_bits,
  input  [1:0]  io_west_4_op,
  input  [15:0] io_west_4_data_bits,
  input  [1:0]  io_west_5_op,
  input  [15:0] io_west_5_data_bits,
  input  [1:0]  io_west_6_op,
  input  [15:0] io_west_6_data_bits,
  input  [1:0]  io_west_7_op,
  input  [15:0] io_west_7_data_bits,
  input  [1:0]  io_west_8_op,
  input  [15:0] io_west_8_data_bits,
  input  [1:0]  io_west_9_op,
  input  [15:0] io_west_9_data_bits,
  input  [1:0]  io_west_10_op,
  input  [15:0] io_west_10_data_bits,
  input  [1:0]  io_west_11_op,
  input  [15:0] io_west_11_data_bits,
                io_north_0_bits,
                io_north_1_bits,
                io_north_2_bits,
                io_north_3_bits,
                io_north_4_bits,
                io_north_5_bits,
                io_north_6_bits,
                io_north_7_bits,
                io_north_8_bits,
                io_north_9_bits,
                io_north_10_bits,
                io_north_11_bits,
  output [15:0] io_southRaw_0_bits,
                io_southRaw_1_bits,
                io_southRaw_2_bits,
                io_southRaw_3_bits,
                io_southRaw_4_bits,
                io_southRaw_5_bits,
                io_southRaw_6_bits,
                io_southRaw_7_bits,
                io_southRaw_8_bits,
                io_southRaw_9_bits,
                io_southRaw_10_bits,
                io_southRaw_11_bits
);

  wire [15:0] _pes_10_11_io_eastOut_bits;
  wire [15:0] _pes_9_11_io_eastOut_bits;
  wire [15:0] _pes_8_11_io_eastOut_bits;
  wire [15:0] _pes_7_11_io_eastOut_bits;
  wire [15:0] _pes_6_11_io_eastOut_bits;
  wire [15:0] _pes_5_11_io_eastOut_bits;
  wire [15:0] _pes_4_11_io_eastOut_bits;
  wire [15:0] _pes_3_11_io_eastOut_bits;
  wire [15:0] _pes_2_11_io_eastOut_bits;
  wire [15:0] _pes_1_11_io_eastOut_bits;
  wire [15:0] _pes_0_11_io_eastOut_bits;
  wire [15:0] _pes_11_10_io_southOut_bits;
  wire [15:0] _pes_10_10_io_eastOut_bits;
  wire [15:0] _pes_10_10_io_southOut_bits;
  wire [15:0] _pes_9_10_io_eastOut_bits;
  wire [15:0] _pes_9_10_io_southOut_bits;
  wire [15:0] _pes_8_10_io_eastOut_bits;
  wire [15:0] _pes_8_10_io_southOut_bits;
  wire [15:0] _pes_7_10_io_eastOut_bits;
  wire [15:0] _pes_7_10_io_southOut_bits;
  wire [15:0] _pes_6_10_io_eastOut_bits;
  wire [15:0] _pes_6_10_io_southOut_bits;
  wire [15:0] _pes_5_10_io_eastOut_bits;
  wire [15:0] _pes_5_10_io_southOut_bits;
  wire [15:0] _pes_4_10_io_eastOut_bits;
  wire [15:0] _pes_4_10_io_southOut_bits;
  wire [15:0] _pes_3_10_io_eastOut_bits;
  wire [15:0] _pes_3_10_io_southOut_bits;
  wire [15:0] _pes_2_10_io_eastOut_bits;
  wire [15:0] _pes_2_10_io_southOut_bits;
  wire [15:0] _pes_1_10_io_eastOut_bits;
  wire [15:0] _pes_1_10_io_southOut_bits;
  wire [15:0] _pes_0_10_io_eastOut_bits;
  wire [15:0] _pes_0_10_io_southOut_bits;
  wire [15:0] _pes_11_9_io_southOut_bits;
  wire [15:0] _pes_10_9_io_eastOut_bits;
  wire [15:0] _pes_10_9_io_southOut_bits;
  wire [15:0] _pes_9_9_io_eastOut_bits;
  wire [15:0] _pes_9_9_io_southOut_bits;
  wire [15:0] _pes_8_9_io_eastOut_bits;
  wire [15:0] _pes_8_9_io_southOut_bits;
  wire [15:0] _pes_7_9_io_eastOut_bits;
  wire [15:0] _pes_7_9_io_southOut_bits;
  wire [15:0] _pes_6_9_io_eastOut_bits;
  wire [15:0] _pes_6_9_io_southOut_bits;
  wire [15:0] _pes_5_9_io_eastOut_bits;
  wire [15:0] _pes_5_9_io_southOut_bits;
  wire [15:0] _pes_4_9_io_eastOut_bits;
  wire [15:0] _pes_4_9_io_southOut_bits;
  wire [15:0] _pes_3_9_io_eastOut_bits;
  wire [15:0] _pes_3_9_io_southOut_bits;
  wire [15:0] _pes_2_9_io_eastOut_bits;
  wire [15:0] _pes_2_9_io_southOut_bits;
  wire [15:0] _pes_1_9_io_eastOut_bits;
  wire [15:0] _pes_1_9_io_southOut_bits;
  wire [15:0] _pes_0_9_io_eastOut_bits;
  wire [15:0] _pes_0_9_io_southOut_bits;
  wire [15:0] _pes_11_8_io_southOut_bits;
  wire [15:0] _pes_10_8_io_eastOut_bits;
  wire [15:0] _pes_10_8_io_southOut_bits;
  wire [15:0] _pes_9_8_io_eastOut_bits;
  wire [15:0] _pes_9_8_io_southOut_bits;
  wire [15:0] _pes_8_8_io_eastOut_bits;
  wire [15:0] _pes_8_8_io_southOut_bits;
  wire [15:0] _pes_7_8_io_eastOut_bits;
  wire [15:0] _pes_7_8_io_southOut_bits;
  wire [15:0] _pes_6_8_io_eastOut_bits;
  wire [15:0] _pes_6_8_io_southOut_bits;
  wire [15:0] _pes_5_8_io_eastOut_bits;
  wire [15:0] _pes_5_8_io_southOut_bits;
  wire [15:0] _pes_4_8_io_eastOut_bits;
  wire [15:0] _pes_4_8_io_southOut_bits;
  wire [15:0] _pes_3_8_io_eastOut_bits;
  wire [15:0] _pes_3_8_io_southOut_bits;
  wire [15:0] _pes_2_8_io_eastOut_bits;
  wire [15:0] _pes_2_8_io_southOut_bits;
  wire [15:0] _pes_1_8_io_eastOut_bits;
  wire [15:0] _pes_1_8_io_southOut_bits;
  wire [15:0] _pes_0_8_io_eastOut_bits;
  wire [15:0] _pes_0_8_io_southOut_bits;
  wire [15:0] _pes_11_7_io_southOut_bits;
  wire [15:0] _pes_10_7_io_eastOut_bits;
  wire [15:0] _pes_10_7_io_southOut_bits;
  wire [15:0] _pes_9_7_io_eastOut_bits;
  wire [15:0] _pes_9_7_io_southOut_bits;
  wire [15:0] _pes_8_7_io_eastOut_bits;
  wire [15:0] _pes_8_7_io_southOut_bits;
  wire [15:0] _pes_7_7_io_eastOut_bits;
  wire [15:0] _pes_7_7_io_southOut_bits;
  wire [15:0] _pes_6_7_io_eastOut_bits;
  wire [15:0] _pes_6_7_io_southOut_bits;
  wire [15:0] _pes_5_7_io_eastOut_bits;
  wire [15:0] _pes_5_7_io_southOut_bits;
  wire [15:0] _pes_4_7_io_eastOut_bits;
  wire [15:0] _pes_4_7_io_southOut_bits;
  wire [15:0] _pes_3_7_io_eastOut_bits;
  wire [15:0] _pes_3_7_io_southOut_bits;
  wire [15:0] _pes_2_7_io_eastOut_bits;
  wire [15:0] _pes_2_7_io_southOut_bits;
  wire [15:0] _pes_1_7_io_eastOut_bits;
  wire [15:0] _pes_1_7_io_southOut_bits;
  wire [15:0] _pes_0_7_io_eastOut_bits;
  wire [15:0] _pes_0_7_io_southOut_bits;
  wire [15:0] _pes_11_6_io_southOut_bits;
  wire [15:0] _pes_10_6_io_eastOut_bits;
  wire [15:0] _pes_10_6_io_southOut_bits;
  wire [15:0] _pes_9_6_io_eastOut_bits;
  wire [15:0] _pes_9_6_io_southOut_bits;
  wire [15:0] _pes_8_6_io_eastOut_bits;
  wire [15:0] _pes_8_6_io_southOut_bits;
  wire [15:0] _pes_7_6_io_eastOut_bits;
  wire [15:0] _pes_7_6_io_southOut_bits;
  wire [15:0] _pes_6_6_io_eastOut_bits;
  wire [15:0] _pes_6_6_io_southOut_bits;
  wire [15:0] _pes_5_6_io_eastOut_bits;
  wire [15:0] _pes_5_6_io_southOut_bits;
  wire [15:0] _pes_4_6_io_eastOut_bits;
  wire [15:0] _pes_4_6_io_southOut_bits;
  wire [15:0] _pes_3_6_io_eastOut_bits;
  wire [15:0] _pes_3_6_io_southOut_bits;
  wire [15:0] _pes_2_6_io_eastOut_bits;
  wire [15:0] _pes_2_6_io_southOut_bits;
  wire [15:0] _pes_1_6_io_eastOut_bits;
  wire [15:0] _pes_1_6_io_southOut_bits;
  wire [15:0] _pes_0_6_io_eastOut_bits;
  wire [15:0] _pes_0_6_io_southOut_bits;
  wire [15:0] _pes_11_5_io_southOut_bits;
  wire [15:0] _pes_10_5_io_eastOut_bits;
  wire [15:0] _pes_10_5_io_southOut_bits;
  wire [15:0] _pes_9_5_io_eastOut_bits;
  wire [15:0] _pes_9_5_io_southOut_bits;
  wire [15:0] _pes_8_5_io_eastOut_bits;
  wire [15:0] _pes_8_5_io_southOut_bits;
  wire [15:0] _pes_7_5_io_eastOut_bits;
  wire [15:0] _pes_7_5_io_southOut_bits;
  wire [15:0] _pes_6_5_io_eastOut_bits;
  wire [15:0] _pes_6_5_io_southOut_bits;
  wire [15:0] _pes_5_5_io_eastOut_bits;
  wire [15:0] _pes_5_5_io_southOut_bits;
  wire [15:0] _pes_4_5_io_eastOut_bits;
  wire [15:0] _pes_4_5_io_southOut_bits;
  wire [15:0] _pes_3_5_io_eastOut_bits;
  wire [15:0] _pes_3_5_io_southOut_bits;
  wire [15:0] _pes_2_5_io_eastOut_bits;
  wire [15:0] _pes_2_5_io_southOut_bits;
  wire [15:0] _pes_1_5_io_eastOut_bits;
  wire [15:0] _pes_1_5_io_southOut_bits;
  wire [15:0] _pes_0_5_io_eastOut_bits;
  wire [15:0] _pes_0_5_io_southOut_bits;
  wire [15:0] _pes_11_4_io_southOut_bits;
  wire [15:0] _pes_10_4_io_eastOut_bits;
  wire [15:0] _pes_10_4_io_southOut_bits;
  wire [15:0] _pes_9_4_io_eastOut_bits;
  wire [15:0] _pes_9_4_io_southOut_bits;
  wire [15:0] _pes_8_4_io_eastOut_bits;
  wire [15:0] _pes_8_4_io_southOut_bits;
  wire [15:0] _pes_7_4_io_eastOut_bits;
  wire [15:0] _pes_7_4_io_southOut_bits;
  wire [15:0] _pes_6_4_io_eastOut_bits;
  wire [15:0] _pes_6_4_io_southOut_bits;
  wire [15:0] _pes_5_4_io_eastOut_bits;
  wire [15:0] _pes_5_4_io_southOut_bits;
  wire [15:0] _pes_4_4_io_eastOut_bits;
  wire [15:0] _pes_4_4_io_southOut_bits;
  wire [15:0] _pes_3_4_io_eastOut_bits;
  wire [15:0] _pes_3_4_io_southOut_bits;
  wire [15:0] _pes_2_4_io_eastOut_bits;
  wire [15:0] _pes_2_4_io_southOut_bits;
  wire [15:0] _pes_1_4_io_eastOut_bits;
  wire [15:0] _pes_1_4_io_southOut_bits;
  wire [15:0] _pes_0_4_io_eastOut_bits;
  wire [15:0] _pes_0_4_io_southOut_bits;
  wire [15:0] _pes_11_3_io_southOut_bits;
  wire [15:0] _pes_10_3_io_eastOut_bits;
  wire [15:0] _pes_10_3_io_southOut_bits;
  wire [15:0] _pes_9_3_io_eastOut_bits;
  wire [15:0] _pes_9_3_io_southOut_bits;
  wire [15:0] _pes_8_3_io_eastOut_bits;
  wire [15:0] _pes_8_3_io_southOut_bits;
  wire [15:0] _pes_7_3_io_eastOut_bits;
  wire [15:0] _pes_7_3_io_southOut_bits;
  wire [15:0] _pes_6_3_io_eastOut_bits;
  wire [15:0] _pes_6_3_io_southOut_bits;
  wire [15:0] _pes_5_3_io_eastOut_bits;
  wire [15:0] _pes_5_3_io_southOut_bits;
  wire [15:0] _pes_4_3_io_eastOut_bits;
  wire [15:0] _pes_4_3_io_southOut_bits;
  wire [15:0] _pes_3_3_io_eastOut_bits;
  wire [15:0] _pes_3_3_io_southOut_bits;
  wire [15:0] _pes_2_3_io_eastOut_bits;
  wire [15:0] _pes_2_3_io_southOut_bits;
  wire [15:0] _pes_1_3_io_eastOut_bits;
  wire [15:0] _pes_1_3_io_southOut_bits;
  wire [15:0] _pes_0_3_io_eastOut_bits;
  wire [15:0] _pes_0_3_io_southOut_bits;
  wire [15:0] _pes_11_2_io_southOut_bits;
  wire [15:0] _pes_10_2_io_eastOut_bits;
  wire [15:0] _pes_10_2_io_southOut_bits;
  wire [15:0] _pes_9_2_io_eastOut_bits;
  wire [15:0] _pes_9_2_io_southOut_bits;
  wire [15:0] _pes_8_2_io_eastOut_bits;
  wire [15:0] _pes_8_2_io_southOut_bits;
  wire [15:0] _pes_7_2_io_eastOut_bits;
  wire [15:0] _pes_7_2_io_southOut_bits;
  wire [15:0] _pes_6_2_io_eastOut_bits;
  wire [15:0] _pes_6_2_io_southOut_bits;
  wire [15:0] _pes_5_2_io_eastOut_bits;
  wire [15:0] _pes_5_2_io_southOut_bits;
  wire [15:0] _pes_4_2_io_eastOut_bits;
  wire [15:0] _pes_4_2_io_southOut_bits;
  wire [15:0] _pes_3_2_io_eastOut_bits;
  wire [15:0] _pes_3_2_io_southOut_bits;
  wire [15:0] _pes_2_2_io_eastOut_bits;
  wire [15:0] _pes_2_2_io_southOut_bits;
  wire [15:0] _pes_1_2_io_eastOut_bits;
  wire [15:0] _pes_1_2_io_southOut_bits;
  wire [15:0] _pes_0_2_io_eastOut_bits;
  wire [15:0] _pes_0_2_io_southOut_bits;
  wire [15:0] _pes_11_1_io_southOut_bits;
  wire [15:0] _pes_10_1_io_eastOut_bits;
  wire [15:0] _pes_10_1_io_southOut_bits;
  wire [15:0] _pes_9_1_io_eastOut_bits;
  wire [15:0] _pes_9_1_io_southOut_bits;
  wire [15:0] _pes_8_1_io_eastOut_bits;
  wire [15:0] _pes_8_1_io_southOut_bits;
  wire [15:0] _pes_7_1_io_eastOut_bits;
  wire [15:0] _pes_7_1_io_southOut_bits;
  wire [15:0] _pes_6_1_io_eastOut_bits;
  wire [15:0] _pes_6_1_io_southOut_bits;
  wire [15:0] _pes_5_1_io_eastOut_bits;
  wire [15:0] _pes_5_1_io_southOut_bits;
  wire [15:0] _pes_4_1_io_eastOut_bits;
  wire [15:0] _pes_4_1_io_southOut_bits;
  wire [15:0] _pes_3_1_io_eastOut_bits;
  wire [15:0] _pes_3_1_io_southOut_bits;
  wire [15:0] _pes_2_1_io_eastOut_bits;
  wire [15:0] _pes_2_1_io_southOut_bits;
  wire [15:0] _pes_1_1_io_eastOut_bits;
  wire [15:0] _pes_1_1_io_southOut_bits;
  wire [15:0] _pes_0_1_io_eastOut_bits;
  wire [15:0] _pes_0_1_io_southOut_bits;
  wire [15:0] _pes_11_io_southOut_bits;
  wire [15:0] _pes_10_io_eastOut_bits;
  wire [15:0] _pes_10_io_southOut_bits;
  wire [15:0] _pes_9_io_eastOut_bits;
  wire [15:0] _pes_9_io_southOut_bits;
  wire [15:0] _pes_8_io_eastOut_bits;
  wire [15:0] _pes_8_io_southOut_bits;
  wire [15:0] _pes_7_io_eastOut_bits;
  wire [15:0] _pes_7_io_southOut_bits;
  wire [15:0] _pes_6_io_eastOut_bits;
  wire [15:0] _pes_6_io_southOut_bits;
  wire [15:0] _pes_5_io_eastOut_bits;
  wire [15:0] _pes_5_io_southOut_bits;
  wire [15:0] _pes_4_io_eastOut_bits;
  wire [15:0] _pes_4_io_southOut_bits;
  wire [15:0] _pes_3_io_eastOut_bits;
  wire [15:0] _pes_3_io_southOut_bits;
  wire [15:0] _pes_2_io_eastOut_bits;
  wire [15:0] _pes_2_io_southOut_bits;
  wire [15:0] _pes_1_io_eastOut_bits;
  wire [15:0] _pes_1_io_southOut_bits;
  wire [15:0] _pes_0_io_eastOut_bits;
  wire [15:0] _pes_0_io_southOut_bits;
  PE pes_0 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (io_west_0_data_bits),
    .io_northIn_bits  (io_north_0_bits),
    .io_eastOut_bits  (_pes_0_io_eastOut_bits),
    .io_southOut_bits (_pes_0_io_southOut_bits)
  );
  PE pes_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_0_io_eastOut_bits),
    .io_northIn_bits  (io_north_1_bits),
    .io_eastOut_bits  (_pes_1_io_eastOut_bits),
    .io_southOut_bits (_pes_1_io_southOut_bits)
  );
  PE pes_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_1_io_eastOut_bits),
    .io_northIn_bits  (io_north_2_bits),
    .io_eastOut_bits  (_pes_2_io_eastOut_bits),
    .io_southOut_bits (_pes_2_io_southOut_bits)
  );
  PE pes_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_2_io_eastOut_bits),
    .io_northIn_bits  (io_north_3_bits),
    .io_eastOut_bits  (_pes_3_io_eastOut_bits),
    .io_southOut_bits (_pes_3_io_southOut_bits)
  );
  PE pes_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_3_io_eastOut_bits),
    .io_northIn_bits  (io_north_4_bits),
    .io_eastOut_bits  (_pes_4_io_eastOut_bits),
    .io_southOut_bits (_pes_4_io_southOut_bits)
  );
  PE pes_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_4_io_eastOut_bits),
    .io_northIn_bits  (io_north_5_bits),
    .io_eastOut_bits  (_pes_5_io_eastOut_bits),
    .io_southOut_bits (_pes_5_io_southOut_bits)
  );
  PE pes_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_5_io_eastOut_bits),
    .io_northIn_bits  (io_north_6_bits),
    .io_eastOut_bits  (_pes_6_io_eastOut_bits),
    .io_southOut_bits (_pes_6_io_southOut_bits)
  );
  PE pes_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_6_io_eastOut_bits),
    .io_northIn_bits  (io_north_7_bits),
    .io_eastOut_bits  (_pes_7_io_eastOut_bits),
    .io_southOut_bits (_pes_7_io_southOut_bits)
  );
  PE pes_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_7_io_eastOut_bits),
    .io_northIn_bits  (io_north_8_bits),
    .io_eastOut_bits  (_pes_8_io_eastOut_bits),
    .io_southOut_bits (_pes_8_io_southOut_bits)
  );
  PE pes_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_8_io_eastOut_bits),
    .io_northIn_bits  (io_north_9_bits),
    .io_eastOut_bits  (_pes_9_io_eastOut_bits),
    .io_southOut_bits (_pes_9_io_southOut_bits)
  );
  PE pes_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_9_io_eastOut_bits),
    .io_northIn_bits  (io_north_10_bits),
    .io_eastOut_bits  (_pes_10_io_eastOut_bits),
    .io_southOut_bits (_pes_10_io_southOut_bits)
  );
  PE pes_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_0_op),
    .io_westIn_bits   (_pes_10_io_eastOut_bits),
    .io_northIn_bits  (io_north_11_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_io_southOut_bits)
  );
  PE pes_0_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (io_west_1_data_bits),
    .io_northIn_bits  (_pes_0_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_1_io_eastOut_bits),
    .io_southOut_bits (_pes_0_1_io_southOut_bits)
  );
  PE pes_1_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_0_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_1_io_eastOut_bits),
    .io_southOut_bits (_pes_1_1_io_southOut_bits)
  );
  PE pes_2_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_1_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_1_io_eastOut_bits),
    .io_southOut_bits (_pes_2_1_io_southOut_bits)
  );
  PE pes_3_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_2_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_1_io_eastOut_bits),
    .io_southOut_bits (_pes_3_1_io_southOut_bits)
  );
  PE pes_4_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_3_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_1_io_eastOut_bits),
    .io_southOut_bits (_pes_4_1_io_southOut_bits)
  );
  PE pes_5_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_4_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_1_io_eastOut_bits),
    .io_southOut_bits (_pes_5_1_io_southOut_bits)
  );
  PE pes_6_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_5_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_1_io_eastOut_bits),
    .io_southOut_bits (_pes_6_1_io_southOut_bits)
  );
  PE pes_7_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_6_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_1_io_eastOut_bits),
    .io_southOut_bits (_pes_7_1_io_southOut_bits)
  );
  PE pes_8_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_7_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_1_io_eastOut_bits),
    .io_southOut_bits (_pes_8_1_io_southOut_bits)
  );
  PE pes_9_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_8_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_1_io_eastOut_bits),
    .io_southOut_bits (_pes_9_1_io_southOut_bits)
  );
  PE pes_10_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_9_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_1_io_eastOut_bits),
    .io_southOut_bits (_pes_10_1_io_southOut_bits)
  );
  PE pes_11_1 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_1_op),
    .io_westIn_bits   (_pes_10_1_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_1_io_southOut_bits)
  );
  PE pes_0_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (io_west_2_data_bits),
    .io_northIn_bits  (_pes_0_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_2_io_eastOut_bits),
    .io_southOut_bits (_pes_0_2_io_southOut_bits)
  );
  PE pes_1_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_0_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_2_io_eastOut_bits),
    .io_southOut_bits (_pes_1_2_io_southOut_bits)
  );
  PE pes_2_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_1_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_2_io_eastOut_bits),
    .io_southOut_bits (_pes_2_2_io_southOut_bits)
  );
  PE pes_3_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_2_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_2_io_eastOut_bits),
    .io_southOut_bits (_pes_3_2_io_southOut_bits)
  );
  PE pes_4_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_3_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_2_io_eastOut_bits),
    .io_southOut_bits (_pes_4_2_io_southOut_bits)
  );
  PE pes_5_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_4_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_2_io_eastOut_bits),
    .io_southOut_bits (_pes_5_2_io_southOut_bits)
  );
  PE pes_6_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_5_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_2_io_eastOut_bits),
    .io_southOut_bits (_pes_6_2_io_southOut_bits)
  );
  PE pes_7_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_6_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_2_io_eastOut_bits),
    .io_southOut_bits (_pes_7_2_io_southOut_bits)
  );
  PE pes_8_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_7_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_2_io_eastOut_bits),
    .io_southOut_bits (_pes_8_2_io_southOut_bits)
  );
  PE pes_9_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_8_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_2_io_eastOut_bits),
    .io_southOut_bits (_pes_9_2_io_southOut_bits)
  );
  PE pes_10_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_9_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_1_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_2_io_eastOut_bits),
    .io_southOut_bits (_pes_10_2_io_southOut_bits)
  );
  PE pes_11_2 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_2_op),
    .io_westIn_bits   (_pes_10_2_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_1_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_2_io_southOut_bits)
  );
  PE pes_0_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (io_west_3_data_bits),
    .io_northIn_bits  (_pes_0_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_3_io_eastOut_bits),
    .io_southOut_bits (_pes_0_3_io_southOut_bits)
  );
  PE pes_1_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_0_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_3_io_eastOut_bits),
    .io_southOut_bits (_pes_1_3_io_southOut_bits)
  );
  PE pes_2_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_1_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_3_io_eastOut_bits),
    .io_southOut_bits (_pes_2_3_io_southOut_bits)
  );
  PE pes_3_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_2_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_3_io_eastOut_bits),
    .io_southOut_bits (_pes_3_3_io_southOut_bits)
  );
  PE pes_4_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_3_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_3_io_eastOut_bits),
    .io_southOut_bits (_pes_4_3_io_southOut_bits)
  );
  PE pes_5_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_4_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_3_io_eastOut_bits),
    .io_southOut_bits (_pes_5_3_io_southOut_bits)
  );
  PE pes_6_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_5_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_3_io_eastOut_bits),
    .io_southOut_bits (_pes_6_3_io_southOut_bits)
  );
  PE pes_7_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_6_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_3_io_eastOut_bits),
    .io_southOut_bits (_pes_7_3_io_southOut_bits)
  );
  PE pes_8_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_7_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_3_io_eastOut_bits),
    .io_southOut_bits (_pes_8_3_io_southOut_bits)
  );
  PE pes_9_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_8_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_3_io_eastOut_bits),
    .io_southOut_bits (_pes_9_3_io_southOut_bits)
  );
  PE pes_10_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_9_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_2_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_3_io_eastOut_bits),
    .io_southOut_bits (_pes_10_3_io_southOut_bits)
  );
  PE pes_11_3 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_3_op),
    .io_westIn_bits   (_pes_10_3_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_2_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_3_io_southOut_bits)
  );
  PE pes_0_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (io_west_4_data_bits),
    .io_northIn_bits  (_pes_0_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_4_io_eastOut_bits),
    .io_southOut_bits (_pes_0_4_io_southOut_bits)
  );
  PE pes_1_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_0_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_4_io_eastOut_bits),
    .io_southOut_bits (_pes_1_4_io_southOut_bits)
  );
  PE pes_2_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_1_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_4_io_eastOut_bits),
    .io_southOut_bits (_pes_2_4_io_southOut_bits)
  );
  PE pes_3_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_2_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_4_io_eastOut_bits),
    .io_southOut_bits (_pes_3_4_io_southOut_bits)
  );
  PE pes_4_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_3_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_4_io_eastOut_bits),
    .io_southOut_bits (_pes_4_4_io_southOut_bits)
  );
  PE pes_5_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_4_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_4_io_eastOut_bits),
    .io_southOut_bits (_pes_5_4_io_southOut_bits)
  );
  PE pes_6_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_5_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_4_io_eastOut_bits),
    .io_southOut_bits (_pes_6_4_io_southOut_bits)
  );
  PE pes_7_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_6_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_4_io_eastOut_bits),
    .io_southOut_bits (_pes_7_4_io_southOut_bits)
  );
  PE pes_8_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_7_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_4_io_eastOut_bits),
    .io_southOut_bits (_pes_8_4_io_southOut_bits)
  );
  PE pes_9_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_8_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_4_io_eastOut_bits),
    .io_southOut_bits (_pes_9_4_io_southOut_bits)
  );
  PE pes_10_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_9_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_3_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_4_io_eastOut_bits),
    .io_southOut_bits (_pes_10_4_io_southOut_bits)
  );
  PE pes_11_4 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_4_op),
    .io_westIn_bits   (_pes_10_4_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_3_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_4_io_southOut_bits)
  );
  PE pes_0_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (io_west_5_data_bits),
    .io_northIn_bits  (_pes_0_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_5_io_eastOut_bits),
    .io_southOut_bits (_pes_0_5_io_southOut_bits)
  );
  PE pes_1_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_0_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_5_io_eastOut_bits),
    .io_southOut_bits (_pes_1_5_io_southOut_bits)
  );
  PE pes_2_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_1_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_5_io_eastOut_bits),
    .io_southOut_bits (_pes_2_5_io_southOut_bits)
  );
  PE pes_3_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_2_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_5_io_eastOut_bits),
    .io_southOut_bits (_pes_3_5_io_southOut_bits)
  );
  PE pes_4_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_3_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_5_io_eastOut_bits),
    .io_southOut_bits (_pes_4_5_io_southOut_bits)
  );
  PE pes_5_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_4_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_5_io_eastOut_bits),
    .io_southOut_bits (_pes_5_5_io_southOut_bits)
  );
  PE pes_6_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_5_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_5_io_eastOut_bits),
    .io_southOut_bits (_pes_6_5_io_southOut_bits)
  );
  PE pes_7_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_6_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_5_io_eastOut_bits),
    .io_southOut_bits (_pes_7_5_io_southOut_bits)
  );
  PE pes_8_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_7_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_5_io_eastOut_bits),
    .io_southOut_bits (_pes_8_5_io_southOut_bits)
  );
  PE pes_9_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_8_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_5_io_eastOut_bits),
    .io_southOut_bits (_pes_9_5_io_southOut_bits)
  );
  PE pes_10_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_9_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_4_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_5_io_eastOut_bits),
    .io_southOut_bits (_pes_10_5_io_southOut_bits)
  );
  PE pes_11_5 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_5_op),
    .io_westIn_bits   (_pes_10_5_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_4_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_5_io_southOut_bits)
  );
  PE pes_0_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (io_west_6_data_bits),
    .io_northIn_bits  (_pes_0_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_6_io_eastOut_bits),
    .io_southOut_bits (_pes_0_6_io_southOut_bits)
  );
  PE pes_1_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_0_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_6_io_eastOut_bits),
    .io_southOut_bits (_pes_1_6_io_southOut_bits)
  );
  PE pes_2_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_1_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_6_io_eastOut_bits),
    .io_southOut_bits (_pes_2_6_io_southOut_bits)
  );
  PE pes_3_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_2_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_6_io_eastOut_bits),
    .io_southOut_bits (_pes_3_6_io_southOut_bits)
  );
  PE pes_4_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_3_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_6_io_eastOut_bits),
    .io_southOut_bits (_pes_4_6_io_southOut_bits)
  );
  PE pes_5_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_4_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_6_io_eastOut_bits),
    .io_southOut_bits (_pes_5_6_io_southOut_bits)
  );
  PE pes_6_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_5_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_6_io_eastOut_bits),
    .io_southOut_bits (_pes_6_6_io_southOut_bits)
  );
  PE pes_7_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_6_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_6_io_eastOut_bits),
    .io_southOut_bits (_pes_7_6_io_southOut_bits)
  );
  PE pes_8_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_7_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_6_io_eastOut_bits),
    .io_southOut_bits (_pes_8_6_io_southOut_bits)
  );
  PE pes_9_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_8_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_6_io_eastOut_bits),
    .io_southOut_bits (_pes_9_6_io_southOut_bits)
  );
  PE pes_10_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_9_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_5_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_6_io_eastOut_bits),
    .io_southOut_bits (_pes_10_6_io_southOut_bits)
  );
  PE pes_11_6 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_6_op),
    .io_westIn_bits   (_pes_10_6_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_5_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_6_io_southOut_bits)
  );
  PE pes_0_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (io_west_7_data_bits),
    .io_northIn_bits  (_pes_0_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_7_io_eastOut_bits),
    .io_southOut_bits (_pes_0_7_io_southOut_bits)
  );
  PE pes_1_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_0_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_7_io_eastOut_bits),
    .io_southOut_bits (_pes_1_7_io_southOut_bits)
  );
  PE pes_2_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_1_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_7_io_eastOut_bits),
    .io_southOut_bits (_pes_2_7_io_southOut_bits)
  );
  PE pes_3_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_2_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_7_io_eastOut_bits),
    .io_southOut_bits (_pes_3_7_io_southOut_bits)
  );
  PE pes_4_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_3_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_7_io_eastOut_bits),
    .io_southOut_bits (_pes_4_7_io_southOut_bits)
  );
  PE pes_5_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_4_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_7_io_eastOut_bits),
    .io_southOut_bits (_pes_5_7_io_southOut_bits)
  );
  PE pes_6_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_5_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_7_io_eastOut_bits),
    .io_southOut_bits (_pes_6_7_io_southOut_bits)
  );
  PE pes_7_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_6_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_7_io_eastOut_bits),
    .io_southOut_bits (_pes_7_7_io_southOut_bits)
  );
  PE pes_8_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_7_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_7_io_eastOut_bits),
    .io_southOut_bits (_pes_8_7_io_southOut_bits)
  );
  PE pes_9_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_8_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_7_io_eastOut_bits),
    .io_southOut_bits (_pes_9_7_io_southOut_bits)
  );
  PE pes_10_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_9_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_6_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_7_io_eastOut_bits),
    .io_southOut_bits (_pes_10_7_io_southOut_bits)
  );
  PE pes_11_7 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_7_op),
    .io_westIn_bits   (_pes_10_7_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_6_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_7_io_southOut_bits)
  );
  PE pes_0_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (io_west_8_data_bits),
    .io_northIn_bits  (_pes_0_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_8_io_eastOut_bits),
    .io_southOut_bits (_pes_0_8_io_southOut_bits)
  );
  PE pes_1_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_0_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_8_io_eastOut_bits),
    .io_southOut_bits (_pes_1_8_io_southOut_bits)
  );
  PE pes_2_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_1_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_8_io_eastOut_bits),
    .io_southOut_bits (_pes_2_8_io_southOut_bits)
  );
  PE pes_3_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_2_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_8_io_eastOut_bits),
    .io_southOut_bits (_pes_3_8_io_southOut_bits)
  );
  PE pes_4_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_3_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_8_io_eastOut_bits),
    .io_southOut_bits (_pes_4_8_io_southOut_bits)
  );
  PE pes_5_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_4_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_8_io_eastOut_bits),
    .io_southOut_bits (_pes_5_8_io_southOut_bits)
  );
  PE pes_6_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_5_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_8_io_eastOut_bits),
    .io_southOut_bits (_pes_6_8_io_southOut_bits)
  );
  PE pes_7_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_6_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_8_io_eastOut_bits),
    .io_southOut_bits (_pes_7_8_io_southOut_bits)
  );
  PE pes_8_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_7_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_8_io_eastOut_bits),
    .io_southOut_bits (_pes_8_8_io_southOut_bits)
  );
  PE pes_9_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_8_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_8_io_eastOut_bits),
    .io_southOut_bits (_pes_9_8_io_southOut_bits)
  );
  PE pes_10_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_9_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_7_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_8_io_eastOut_bits),
    .io_southOut_bits (_pes_10_8_io_southOut_bits)
  );
  PE pes_11_8 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_8_op),
    .io_westIn_bits   (_pes_10_8_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_7_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_8_io_southOut_bits)
  );
  PE pes_0_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (io_west_9_data_bits),
    .io_northIn_bits  (_pes_0_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_9_io_eastOut_bits),
    .io_southOut_bits (_pes_0_9_io_southOut_bits)
  );
  PE pes_1_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_0_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_9_io_eastOut_bits),
    .io_southOut_bits (_pes_1_9_io_southOut_bits)
  );
  PE pes_2_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_1_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_9_io_eastOut_bits),
    .io_southOut_bits (_pes_2_9_io_southOut_bits)
  );
  PE pes_3_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_2_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_9_io_eastOut_bits),
    .io_southOut_bits (_pes_3_9_io_southOut_bits)
  );
  PE pes_4_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_3_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_9_io_eastOut_bits),
    .io_southOut_bits (_pes_4_9_io_southOut_bits)
  );
  PE pes_5_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_4_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_9_io_eastOut_bits),
    .io_southOut_bits (_pes_5_9_io_southOut_bits)
  );
  PE pes_6_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_5_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_9_io_eastOut_bits),
    .io_southOut_bits (_pes_6_9_io_southOut_bits)
  );
  PE pes_7_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_6_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_9_io_eastOut_bits),
    .io_southOut_bits (_pes_7_9_io_southOut_bits)
  );
  PE pes_8_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_7_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_9_io_eastOut_bits),
    .io_southOut_bits (_pes_8_9_io_southOut_bits)
  );
  PE pes_9_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_8_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_9_io_eastOut_bits),
    .io_southOut_bits (_pes_9_9_io_southOut_bits)
  );
  PE pes_10_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_9_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_8_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_9_io_eastOut_bits),
    .io_southOut_bits (_pes_10_9_io_southOut_bits)
  );
  PE pes_11_9 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_9_op),
    .io_westIn_bits   (_pes_10_9_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_8_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_9_io_southOut_bits)
  );
  PE pes_0_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (io_west_10_data_bits),
    .io_northIn_bits  (_pes_0_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_10_io_eastOut_bits),
    .io_southOut_bits (_pes_0_10_io_southOut_bits)
  );
  PE pes_1_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_0_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_10_io_eastOut_bits),
    .io_southOut_bits (_pes_1_10_io_southOut_bits)
  );
  PE pes_2_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_1_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_10_io_eastOut_bits),
    .io_southOut_bits (_pes_2_10_io_southOut_bits)
  );
  PE pes_3_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_2_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_10_io_eastOut_bits),
    .io_southOut_bits (_pes_3_10_io_southOut_bits)
  );
  PE pes_4_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_3_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_10_io_eastOut_bits),
    .io_southOut_bits (_pes_4_10_io_southOut_bits)
  );
  PE pes_5_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_4_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_10_io_eastOut_bits),
    .io_southOut_bits (_pes_5_10_io_southOut_bits)
  );
  PE pes_6_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_5_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_10_io_eastOut_bits),
    .io_southOut_bits (_pes_6_10_io_southOut_bits)
  );
  PE pes_7_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_6_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_10_io_eastOut_bits),
    .io_southOut_bits (_pes_7_10_io_southOut_bits)
  );
  PE pes_8_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_7_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_10_io_eastOut_bits),
    .io_southOut_bits (_pes_8_10_io_southOut_bits)
  );
  PE pes_9_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_8_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_10_io_eastOut_bits),
    .io_southOut_bits (_pes_9_10_io_southOut_bits)
  );
  PE pes_10_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_9_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_9_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_10_io_eastOut_bits),
    .io_southOut_bits (_pes_10_10_io_southOut_bits)
  );
  PE pes_11_10 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_10_op),
    .io_westIn_bits   (_pes_10_10_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_9_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (_pes_11_10_io_southOut_bits)
  );
  PE pes_0_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (io_west_11_data_bits),
    .io_northIn_bits  (_pes_0_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_0_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_0_bits)
  );
  PE pes_1_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_0_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_1_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_1_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_1_bits)
  );
  PE pes_2_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_1_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_2_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_2_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_2_bits)
  );
  PE pes_3_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_2_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_3_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_3_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_3_bits)
  );
  PE pes_4_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_3_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_4_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_4_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_4_bits)
  );
  PE pes_5_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_4_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_5_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_5_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_5_bits)
  );
  PE pes_6_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_5_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_6_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_6_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_6_bits)
  );
  PE pes_7_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_6_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_7_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_7_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_7_bits)
  );
  PE pes_8_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_7_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_8_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_8_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_8_bits)
  );
  PE pes_9_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_8_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_9_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_9_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_9_bits)
  );
  PE pes_10_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_9_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_10_10_io_southOut_bits),
    .io_eastOut_bits  (_pes_10_11_io_eastOut_bits),
    .io_southOut_bits (io_southRaw_10_bits)
  );
  PE pes_11_11 (
    .clock            (clock),
    .reset            (reset),
    .io_westOpIn      (io_west_11_op),
    .io_westIn_bits   (_pes_10_11_io_eastOut_bits),
    .io_northIn_bits  (_pes_11_10_io_southOut_bits),
    .io_eastOut_bits  (/* unused */),
    .io_southOut_bits (io_southRaw_11_bits)
  );
endmodule

