// Generated by CIRCT firtool-1.140.0
module PE(
  input         clock,
                reset,
  input  [2:0]  io_op,
  input  [7:0]  io_lInput_bits,
  input  [15:0] io_uInput_bits,
                io_dInput_bits,
  output [7:0]  io_rOutput_bits,
  output [15:0] io_dOutput_bits,
                io_uOutput_bits
);

  wire [15:0] _regVal_adder_z;
  wire [15:0] _expUnit_io_out_bits;
  reg  [15:0] regVal_bits;
  wire [15:0] lInputAcc_bits = {io_lInput_bits, 8'h0};
  wire        expUnit_io_coeffEncoded = io_op == 3'h5;
  wire        _GEN = io_op == 3'h1;
  wire        _GEN_0 = io_op == 3'h2;
  wire        _GEN_1 = io_op == 3'h3;
  always @(posedge clock) begin
    if (reset)
      regVal_bits <= 16'h0;
    else begin
      automatic logic [7:0][15:0] _GEN_2 =
        {{regVal_bits},
         {_regVal_adder_z},
         {_expUnit_io_out_bits},
         {regVal_bits},
         {regVal_bits},
         {io_uInput_bits},
         {lInputAcc_bits},
         {regVal_bits}};
      regVal_bits <= _GEN_2[io_op];
    end
  end // always @(posedge)
  SystolicAttentionScale expUnit (
    .io_cmd          ({1'h1, expUnit_io_coeffEncoded}),
    .io_x_bits       (expUnit_io_coeffEncoded ? regVal_bits : lInputAcc_bits),
    .io_w_bits       (expUnit_io_coeffEncoded ? lInputAcc_bits : regVal_bits),
    .io_b_bits       (io_op == 3'h3 ? io_dInput_bits : io_uInput_bits),
    .io_coeffEncoded (expUnit_io_coeffEncoded),
    .io_out_bits     (_expUnit_io_out_bits)
  );
  DW_fp_add #(
    .exp_width(5),
    .ieee_compliance(0),
    .sig_width(10)
  ) regVal_adder (
    .a      (regVal_bits),
    .b      ({~(io_uInput_bits[15]), io_uInput_bits[14:0]}),
    .rnd    (3'h0),
    .z      (_regVal_adder_z),
    .status (/* unused */)
  );
  assign io_rOutput_bits = io_lInput_bits;
  assign io_dOutput_bits =
    _GEN | _GEN_0 | _GEN_1 | io_op != 3'h4 ? io_uInput_bits : _expUnit_io_out_bits;
  assign io_uOutput_bits =
    _GEN | _GEN_0 | ~_GEN_1 ? io_dInput_bits : _expUnit_io_out_bits;
endmodule

