// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [2:0]  io_peOp_0_0,
                io_peOp_0_1,
                io_peOp_0_2,
                io_peOp_0_3,
                io_peOp_1_0,
                io_peOp_1_1,
                io_peOp_1_2,
                io_peOp_1_3,
                io_peOp_2_0,
                io_peOp_2_1,
                io_peOp_2_2,
                io_peOp_2_3,
                io_peOp_3_0,
                io_peOp_3_1,
                io_peOp_3_2,
                io_peOp_3_3,
  input  [7:0]  io_leftIn_0_bits,
                io_leftIn_1_bits,
                io_leftIn_2_bits,
                io_leftIn_3_bits,
                io_bottomIn_0_bits,
                io_bottomIn_1_bits,
                io_bottomIn_2_bits,
                io_bottomIn_3_bits,
  input  [2:0]  io_cmpOp_0,
                io_cmpOp_1,
                io_cmpOp_2,
                io_cmpOp_3,
  input  [15:0] io_cmpSeedOldMax_0_bits,
                io_cmpSeedOldMax_1_bits,
                io_cmpSeedOldMax_2_bits,
                io_cmpSeedOldMax_3_bits,
                io_cmpIntercept_0_bits,
                io_cmpIntercept_1_bits,
                io_cmpIntercept_2_bits,
                io_cmpIntercept_3_bits,
  output [15:0] io_accOut_0_bits,
                io_accOut_1_bits,
                io_accOut_2_bits,
                io_accOut_3_bits,
                io_rowMax_0_bits,
                io_rowMax_1_bits,
                io_rowMax_2_bits,
                io_rowMax_3_bits,
                io_rowDiff_0_bits,
                io_rowDiff_1_bits,
                io_rowDiff_2_bits,
                io_rowDiff_3_bits
);

  wire [15:0] _mesh_3_3_io_dOutput_bits;
  wire [15:0] _mesh_3_3_io_uOutput_bits;
  wire [7:0]  _mesh_3_2_io_rOutput_bits;
  wire [15:0] _mesh_3_2_io_dOutput_bits;
  wire [15:0] _mesh_3_2_io_uOutput_bits;
  wire [7:0]  _mesh_3_1_io_rOutput_bits;
  wire [15:0] _mesh_3_1_io_dOutput_bits;
  wire [15:0] _mesh_3_1_io_uOutput_bits;
  wire [7:0]  _mesh_3_0_io_rOutput_bits;
  wire [15:0] _mesh_3_0_io_dOutput_bits;
  wire [15:0] _mesh_3_0_io_uOutput_bits;
  wire [15:0] _mesh_2_3_io_dOutput_bits;
  wire [15:0] _mesh_2_3_io_uOutput_bits;
  wire [7:0]  _mesh_2_2_io_rOutput_bits;
  wire [15:0] _mesh_2_2_io_dOutput_bits;
  wire [15:0] _mesh_2_2_io_uOutput_bits;
  wire [7:0]  _mesh_2_1_io_rOutput_bits;
  wire [15:0] _mesh_2_1_io_dOutput_bits;
  wire [15:0] _mesh_2_1_io_uOutput_bits;
  wire [7:0]  _mesh_2_0_io_rOutput_bits;
  wire [15:0] _mesh_2_0_io_dOutput_bits;
  wire [15:0] _mesh_2_0_io_uOutput_bits;
  wire [15:0] _mesh_1_3_io_dOutput_bits;
  wire [15:0] _mesh_1_3_io_uOutput_bits;
  wire [7:0]  _mesh_1_2_io_rOutput_bits;
  wire [15:0] _mesh_1_2_io_dOutput_bits;
  wire [15:0] _mesh_1_2_io_uOutput_bits;
  wire [7:0]  _mesh_1_1_io_rOutput_bits;
  wire [15:0] _mesh_1_1_io_dOutput_bits;
  wire [15:0] _mesh_1_1_io_uOutput_bits;
  wire [7:0]  _mesh_1_0_io_rOutput_bits;
  wire [15:0] _mesh_1_0_io_dOutput_bits;
  wire [15:0] _mesh_1_0_io_uOutput_bits;
  wire [15:0] _mesh_0_3_io_dOutput_bits;
  wire [15:0] _mesh_0_3_io_uOutput_bits;
  wire [7:0]  _mesh_0_2_io_rOutput_bits;
  wire [15:0] _mesh_0_2_io_dOutput_bits;
  wire [15:0] _mesh_0_2_io_uOutput_bits;
  wire [7:0]  _mesh_0_1_io_rOutput_bits;
  wire [15:0] _mesh_0_1_io_dOutput_bits;
  wire [15:0] _mesh_0_1_io_uOutput_bits;
  wire [7:0]  _mesh_0_0_io_rOutput_bits;
  wire [15:0] _mesh_0_0_io_dOutput_bits;
  wire [15:0] _mesh_0_0_io_uOutput_bits;
  wire [15:0] _cmpArray_3_io_dOutput_bits;
  wire [15:0] _cmpArray_2_io_dOutput_bits;
  wire [15:0] _cmpArray_1_io_dOutput_bits;
  wire [15:0] _cmpArray_0_io_dOutput_bits;
  reg  [15:0] dIn_bits;
  reg  [7:0]  lIn_bits;
  reg  [15:0] dIn_1_bits;
  reg  [7:0]  lIn_1_bits;
  reg  [15:0] dIn_2_bits;
  reg  [7:0]  lIn_2_bits;
  reg  [15:0] dIn_3_bits;
  reg  [15:0] uIn_bits;
  reg  [15:0] dIn_4_bits;
  reg  [7:0]  lIn_3_bits;
  reg  [15:0] uIn_1_bits;
  reg  [15:0] dIn_5_bits;
  reg  [7:0]  lIn_4_bits;
  reg  [15:0] uIn_2_bits;
  reg  [15:0] dIn_6_bits;
  reg  [7:0]  lIn_5_bits;
  reg  [15:0] uIn_3_bits;
  reg  [15:0] dIn_7_bits;
  reg  [15:0] uIn_4_bits;
  reg  [15:0] dIn_8_bits;
  reg  [7:0]  lIn_6_bits;
  reg  [15:0] uIn_5_bits;
  reg  [15:0] dIn_9_bits;
  reg  [7:0]  lIn_7_bits;
  reg  [15:0] uIn_6_bits;
  reg  [15:0] dIn_10_bits;
  reg  [7:0]  lIn_8_bits;
  reg  [15:0] uIn_7_bits;
  reg  [15:0] dIn_11_bits;
  reg  [15:0] uIn_8_bits;
  reg  [7:0]  lIn_9_bits;
  reg  [15:0] uIn_9_bits;
  reg  [7:0]  lIn_10_bits;
  reg  [15:0] uIn_10_bits;
  reg  [7:0]  lIn_11_bits;
  reg  [15:0] uIn_11_bits;
  reg  [15:0] cmpIn_bits;
  reg  [15:0] io_accOut_0_REG_bits;
  reg  [15:0] cmpIn_1_bits;
  reg  [15:0] io_accOut_1_REG_bits;
  reg  [15:0] cmpIn_2_bits;
  reg  [15:0] io_accOut_2_REG_bits;
  reg  [15:0] cmpIn_3_bits;
  reg  [15:0] io_accOut_3_REG_bits;
  always @(posedge clock) begin
    dIn_bits <= _mesh_1_0_io_uOutput_bits;
    lIn_bits <= _mesh_0_0_io_rOutput_bits;
    dIn_1_bits <= _mesh_1_1_io_uOutput_bits;
    lIn_1_bits <= _mesh_0_1_io_rOutput_bits;
    dIn_2_bits <= _mesh_1_2_io_uOutput_bits;
    lIn_2_bits <= _mesh_0_2_io_rOutput_bits;
    dIn_3_bits <= _mesh_1_3_io_uOutput_bits;
    uIn_bits <= _mesh_0_0_io_dOutput_bits;
    dIn_4_bits <= _mesh_2_0_io_uOutput_bits;
    lIn_3_bits <= _mesh_1_0_io_rOutput_bits;
    uIn_1_bits <= _mesh_0_1_io_dOutput_bits;
    dIn_5_bits <= _mesh_2_1_io_uOutput_bits;
    lIn_4_bits <= _mesh_1_1_io_rOutput_bits;
    uIn_2_bits <= _mesh_0_2_io_dOutput_bits;
    dIn_6_bits <= _mesh_2_2_io_uOutput_bits;
    lIn_5_bits <= _mesh_1_2_io_rOutput_bits;
    uIn_3_bits <= _mesh_0_3_io_dOutput_bits;
    dIn_7_bits <= _mesh_2_3_io_uOutput_bits;
    uIn_4_bits <= _mesh_1_0_io_dOutput_bits;
    dIn_8_bits <= _mesh_3_0_io_uOutput_bits;
    lIn_6_bits <= _mesh_2_0_io_rOutput_bits;
    uIn_5_bits <= _mesh_1_1_io_dOutput_bits;
    dIn_9_bits <= _mesh_3_1_io_uOutput_bits;
    lIn_7_bits <= _mesh_2_1_io_rOutput_bits;
    uIn_6_bits <= _mesh_1_2_io_dOutput_bits;
    dIn_10_bits <= _mesh_3_2_io_uOutput_bits;
    lIn_8_bits <= _mesh_2_2_io_rOutput_bits;
    uIn_7_bits <= _mesh_1_3_io_dOutput_bits;
    dIn_11_bits <= _mesh_3_3_io_uOutput_bits;
    uIn_8_bits <= _mesh_2_0_io_dOutput_bits;
    lIn_9_bits <= _mesh_3_0_io_rOutput_bits;
    uIn_9_bits <= _mesh_2_1_io_dOutput_bits;
    lIn_10_bits <= _mesh_3_1_io_rOutput_bits;
    uIn_10_bits <= _mesh_2_2_io_dOutput_bits;
    lIn_11_bits <= _mesh_3_2_io_rOutput_bits;
    uIn_11_bits <= _mesh_2_3_io_dOutput_bits;
    cmpIn_bits <= _mesh_0_0_io_uOutput_bits;
    io_accOut_0_REG_bits <= _mesh_3_0_io_dOutput_bits;
    cmpIn_1_bits <= _mesh_0_1_io_uOutput_bits;
    io_accOut_1_REG_bits <= _mesh_3_1_io_dOutput_bits;
    cmpIn_2_bits <= _mesh_0_2_io_uOutput_bits;
    io_accOut_2_REG_bits <= _mesh_3_2_io_dOutput_bits;
    cmpIn_3_bits <= _mesh_0_3_io_uOutput_bits;
    io_accOut_3_REG_bits <= _mesh_3_3_io_dOutput_bits;
  end // always @(posedge)
  CMP cmpArray_0 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_0),
    .io_dInput_bits     (cmpIn_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_0_bits),
    .io_intercept_bits  (io_cmpIntercept_0_bits),
    .io_dOutput_bits    (_cmpArray_0_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_0_bits),
    .io_diffOut_bits    (io_rowDiff_0_bits)
  );
  CMP cmpArray_1 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_1),
    .io_dInput_bits     (cmpIn_1_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_1_bits),
    .io_intercept_bits  (io_cmpIntercept_1_bits),
    .io_dOutput_bits    (_cmpArray_1_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_1_bits),
    .io_diffOut_bits    (io_rowDiff_1_bits)
  );
  CMP cmpArray_2 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_2),
    .io_dInput_bits     (cmpIn_2_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_2_bits),
    .io_intercept_bits  (io_cmpIntercept_2_bits),
    .io_dOutput_bits    (_cmpArray_2_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_2_bits),
    .io_diffOut_bits    (io_rowDiff_2_bits)
  );
  CMP cmpArray_3 (
    .clock              (clock),
    .reset              (reset),
    .io_op              (io_cmpOp_3),
    .io_dInput_bits     (cmpIn_3_bits),
    .io_seedOldMax_bits (io_cmpSeedOldMax_3_bits),
    .io_intercept_bits  (io_cmpIntercept_3_bits),
    .io_dOutput_bits    (_cmpArray_3_io_dOutput_bits),
    .io_newMaxOut_bits  (io_rowMax_3_bits),
    .io_diffOut_bits    (io_rowDiff_3_bits)
  );
  PE mesh_0_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_0),
    .io_lInput_bits  (io_leftIn_0_bits),
    .io_uInput_bits  (_cmpArray_0_io_dOutput_bits),
    .io_dInput_bits  (dIn_bits),
    .io_rOutput_bits (_mesh_0_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_0_io_uOutput_bits)
  );
  PE mesh_0_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_1),
    .io_lInput_bits  (lIn_bits),
    .io_uInput_bits  (_cmpArray_1_io_dOutput_bits),
    .io_dInput_bits  (dIn_1_bits),
    .io_rOutput_bits (_mesh_0_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_1_io_uOutput_bits)
  );
  PE mesh_0_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_2),
    .io_lInput_bits  (lIn_1_bits),
    .io_uInput_bits  (_cmpArray_2_io_dOutput_bits),
    .io_dInput_bits  (dIn_2_bits),
    .io_rOutput_bits (_mesh_0_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_0_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_2_io_uOutput_bits)
  );
  PE mesh_0_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_0_3),
    .io_lInput_bits  (lIn_2_bits),
    .io_uInput_bits  (_cmpArray_3_io_dOutput_bits),
    .io_dInput_bits  (dIn_3_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_0_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_0_3_io_uOutput_bits)
  );
  PE mesh_1_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_0),
    .io_lInput_bits  (io_leftIn_1_bits),
    .io_uInput_bits  (uIn_bits),
    .io_dInput_bits  (dIn_4_bits),
    .io_rOutput_bits (_mesh_1_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_0_io_uOutput_bits)
  );
  PE mesh_1_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_1),
    .io_lInput_bits  (lIn_3_bits),
    .io_uInput_bits  (uIn_1_bits),
    .io_dInput_bits  (dIn_5_bits),
    .io_rOutput_bits (_mesh_1_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_1_io_uOutput_bits)
  );
  PE mesh_1_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_2),
    .io_lInput_bits  (lIn_4_bits),
    .io_uInput_bits  (uIn_2_bits),
    .io_dInput_bits  (dIn_6_bits),
    .io_rOutput_bits (_mesh_1_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_1_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_2_io_uOutput_bits)
  );
  PE mesh_1_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_1_3),
    .io_lInput_bits  (lIn_5_bits),
    .io_uInput_bits  (uIn_3_bits),
    .io_dInput_bits  (dIn_7_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_1_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_1_3_io_uOutput_bits)
  );
  PE mesh_2_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_0),
    .io_lInput_bits  (io_leftIn_2_bits),
    .io_uInput_bits  (uIn_4_bits),
    .io_dInput_bits  (dIn_8_bits),
    .io_rOutput_bits (_mesh_2_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_0_io_uOutput_bits)
  );
  PE mesh_2_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_1),
    .io_lInput_bits  (lIn_6_bits),
    .io_uInput_bits  (uIn_5_bits),
    .io_dInput_bits  (dIn_9_bits),
    .io_rOutput_bits (_mesh_2_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_1_io_uOutput_bits)
  );
  PE mesh_2_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_2),
    .io_lInput_bits  (lIn_7_bits),
    .io_uInput_bits  (uIn_6_bits),
    .io_dInput_bits  (dIn_10_bits),
    .io_rOutput_bits (_mesh_2_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_2_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_2_io_uOutput_bits)
  );
  PE mesh_2_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_2_3),
    .io_lInput_bits  (lIn_8_bits),
    .io_uInput_bits  (uIn_7_bits),
    .io_dInput_bits  (dIn_11_bits),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_2_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_2_3_io_uOutput_bits)
  );
  PE mesh_3_0 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_0),
    .io_lInput_bits  (io_leftIn_3_bits),
    .io_uInput_bits  (uIn_8_bits),
    .io_dInput_bits  ({io_bottomIn_0_bits, 8'h0}),
    .io_rOutput_bits (_mesh_3_0_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_0_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_0_io_uOutput_bits)
  );
  PE mesh_3_1 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_1),
    .io_lInput_bits  (lIn_9_bits),
    .io_uInput_bits  (uIn_9_bits),
    .io_dInput_bits  ({io_bottomIn_1_bits, 8'h0}),
    .io_rOutput_bits (_mesh_3_1_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_1_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_1_io_uOutput_bits)
  );
  PE mesh_3_2 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_2),
    .io_lInput_bits  (lIn_10_bits),
    .io_uInput_bits  (uIn_10_bits),
    .io_dInput_bits  ({io_bottomIn_2_bits, 8'h0}),
    .io_rOutput_bits (_mesh_3_2_io_rOutput_bits),
    .io_dOutput_bits (_mesh_3_2_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_2_io_uOutput_bits)
  );
  PE mesh_3_3 (
    .clock           (clock),
    .reset           (reset),
    .io_op           (io_peOp_3_3),
    .io_lInput_bits  (lIn_11_bits),
    .io_uInput_bits  (uIn_11_bits),
    .io_dInput_bits  ({io_bottomIn_3_bits, 8'h0}),
    .io_rOutput_bits (/* unused */),
    .io_dOutput_bits (_mesh_3_3_io_dOutput_bits),
    .io_uOutput_bits (_mesh_3_3_io_uOutput_bits)
  );
  assign io_accOut_0_bits = io_accOut_0_REG_bits;
  assign io_accOut_1_bits = io_accOut_1_REG_bits;
  assign io_accOut_2_bits = io_accOut_2_REG_bits;
  assign io_accOut_3_bits = io_accOut_3_REG_bits;
endmodule

