// Generated by CIRCT firtool-1.140.0
module SystolicArray(
  input         clock,
                reset,
  input  [1:0]  io_west_0_op,
  input  [15:0] io_west_0_data,
  input  [1:0]  io_west_1_op,
  input  [15:0] io_west_1_data,
  input  [1:0]  io_west_2_op,
  input  [15:0] io_west_2_data,
  input  [1:0]  io_west_3_op,
  input  [15:0] io_west_3_data,
  input         io_stripNorth_0_0_op,
  input  [31:0] io_stripNorth_0_0_data,
  input         io_stripNorth_0_1_op,
  input  [31:0] io_stripNorth_0_1_data,
  input         io_stripNorth_1_0_op,
  input  [31:0] io_stripNorth_1_0_data,
  input         io_stripNorth_1_1_op,
  input  [31:0] io_stripNorth_1_1_data,
  input         io_stripNorth_2_0_op,
  input  [31:0] io_stripNorth_2_0_data,
  input         io_stripNorth_2_1_op,
  input  [31:0] io_stripNorth_2_1_data,
  input         io_stripNorth_3_0_op,
  input  [31:0] io_stripNorth_3_0_data,
  input         io_stripNorth_3_1_op,
  input  [31:0] io_stripNorth_3_1_data,
  output [31:0] io_gemmSouthRaw_0,
                io_gemmSouthRaw_1,
                io_gemmSouthRaw_2,
                io_gemmSouthRaw_3,
                io_pinnSouthRaw_0,
                io_pinnSouthRaw_1,
                io_pinnSouthRaw_2,
                io_pinnSouthRaw_3
);

  wire [31:0] _pairs_1_3_io_southOut_1;
  wire [15:0] _pairs_0_3_io_eastOut;
  wire [31:0] _pairs_0_3_io_southOut_1;
  wire [31:0] _pairs_1_2_io_southOut_0;
  wire [31:0] _pairs_1_2_io_southOut_1;
  wire [15:0] _pairs_0_2_io_eastOut;
  wire [31:0] _pairs_0_2_io_southOut_0;
  wire [31:0] _pairs_0_2_io_southOut_1;
  wire [31:0] _pairs_1_1_io_southOut_0;
  wire [31:0] _pairs_1_1_io_southOut_1;
  wire [15:0] _pairs_0_1_io_eastOut;
  wire [31:0] _pairs_0_1_io_southOut_0;
  wire [31:0] _pairs_0_1_io_southOut_1;
  wire [31:0] _pairs_1_io_southOut_0;
  wire [31:0] _pairs_1_io_southOut_1;
  wire [15:0] _pairs_0_io_eastOut;
  wire [31:0] _pairs_0_io_southOut_0;
  wire [31:0] _pairs_0_io_southOut_1;
  StripPair pairs_0 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_0_op),
    .io_westIn     (io_west_0_data),
    .io_northOpIn  (io_stripNorth_0_0_op),
    .io_northIn_0  (io_stripNorth_0_0_op ? io_stripNorth_0_0_data : 32'h0),
    .io_northIn_1  (32'h0),
    .io_eastOut    (_pairs_0_io_eastOut),
    .io_southOut_0 (_pairs_0_io_southOut_0),
    .io_southOut_1 (_pairs_0_io_southOut_1)
  );
  StripPair pairs_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_0_op),
    .io_westIn     (_pairs_0_io_eastOut),
    .io_northOpIn  (io_stripNorth_0_1_op),
    .io_northIn_0  (io_stripNorth_0_1_op ? io_stripNorth_0_1_data : 32'h0),
    .io_northIn_1  (32'h0),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_1_io_southOut_0),
    .io_southOut_1 (_pairs_1_io_southOut_1)
  );
  StripPair pairs_0_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_1_op),
    .io_westIn     (io_west_1_data),
    .io_northOpIn  (io_stripNorth_1_0_op),
    .io_northIn_0  (_pairs_0_io_southOut_0),
    .io_northIn_1  (_pairs_0_io_southOut_1),
    .io_eastOut    (_pairs_0_1_io_eastOut),
    .io_southOut_0 (_pairs_0_1_io_southOut_0),
    .io_southOut_1 (_pairs_0_1_io_southOut_1)
  );
  StripPair pairs_1_1 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_1_op),
    .io_westIn     (_pairs_0_1_io_eastOut),
    .io_northOpIn  (io_stripNorth_1_1_op),
    .io_northIn_0  (_pairs_1_io_southOut_0),
    .io_northIn_1  (_pairs_1_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_1_1_io_southOut_0),
    .io_southOut_1 (_pairs_1_1_io_southOut_1)
  );
  StripPair pairs_0_2 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_2_op),
    .io_westIn     (io_west_2_data),
    .io_northOpIn  (io_stripNorth_2_0_op),
    .io_northIn_0
      (io_stripNorth_2_0_op ? io_stripNorth_2_0_data : _pairs_0_1_io_southOut_0),
    .io_northIn_1  (io_stripNorth_2_0_op ? 32'h0 : _pairs_0_1_io_southOut_1),
    .io_eastOut    (_pairs_0_2_io_eastOut),
    .io_southOut_0 (_pairs_0_2_io_southOut_0),
    .io_southOut_1 (_pairs_0_2_io_southOut_1)
  );
  StripPair pairs_1_2 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_2_op),
    .io_westIn     (_pairs_0_2_io_eastOut),
    .io_northOpIn  (io_stripNorth_2_1_op),
    .io_northIn_0
      (io_stripNorth_2_1_op ? io_stripNorth_2_1_data : _pairs_1_1_io_southOut_0),
    .io_northIn_1  (io_stripNorth_2_1_op ? 32'h0 : _pairs_1_1_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (_pairs_1_2_io_southOut_0),
    .io_southOut_1 (_pairs_1_2_io_southOut_1)
  );
  StripPair pairs_0_3 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_3_op),
    .io_westIn     (io_west_3_data),
    .io_northOpIn  (io_stripNorth_3_0_op),
    .io_northIn_0  (_pairs_0_2_io_southOut_0),
    .io_northIn_1  (_pairs_0_2_io_southOut_1),
    .io_eastOut    (_pairs_0_3_io_eastOut),
    .io_southOut_0 (io_gemmSouthRaw_0),
    .io_southOut_1 (_pairs_0_3_io_southOut_1)
  );
  StripPair pairs_1_3 (
    .clock         (clock),
    .reset         (reset),
    .io_westOpIn   (io_west_3_op),
    .io_westIn     (_pairs_0_3_io_eastOut),
    .io_northOpIn  (io_stripNorth_3_1_op),
    .io_northIn_0  (_pairs_1_2_io_southOut_0),
    .io_northIn_1  (_pairs_1_2_io_southOut_1),
    .io_eastOut    (/* unused */),
    .io_southOut_0 (io_gemmSouthRaw_2),
    .io_southOut_1 (_pairs_1_3_io_southOut_1)
  );
  assign io_gemmSouthRaw_1 = _pairs_0_3_io_southOut_1;
  assign io_gemmSouthRaw_3 = _pairs_1_3_io_southOut_1;
  assign io_pinnSouthRaw_0 = _pairs_0_1_io_southOut_1;
  assign io_pinnSouthRaw_1 = _pairs_1_1_io_southOut_1;
  assign io_pinnSouthRaw_2 = _pairs_0_3_io_southOut_1;
  assign io_pinnSouthRaw_3 = _pairs_1_3_io_southOut_1;
endmodule

