// Generated by CIRCT firtool-1.140.0
module FuseMax2DPE(
  input         clock,
                reset,
                io_cmd_en,
  input  [3:0]  io_cmd_op,
  input  [2:0]  io_cmd_aSel,
  input  [3:0]  io_cmd_aIdx,
  input  [2:0]  io_cmd_bSel,
  input  [3:0]  io_cmd_bIdx,
  input  [2:0]  io_cmd_cSel,
  input  [3:0]  io_cmd_cIdx,
                io_cmd_dstIdx,
  input         io_cmd_writeDst,
                io_cmd_southFromFu,
  input  [15:0] io_in_w,
                io_in_n,
  input  [31:0] io_in_scalar,
  output [15:0] io_out_e,
                io_out_s
);

  reg  [15:0]       pipeReg;
  reg  [15:0]       northReg;
  reg  [31:0]       rf_0;
  reg  [31:0]       rf_1;
  reg  [31:0]       rf_2;
  reg  [31:0]       rf_3;
  reg  [31:0]       rf_4;
  reg  [31:0]       rf_5;
  reg  [31:0]       rf_6;
  reg  [31:0]       rf_7;
  reg  [31:0]       rf_8;
  reg  [31:0]       rf_9;
  wire [15:0][31:0] _GEN =
    {{rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_0},
     {rf_9},
     {rf_8},
     {rf_7},
     {rf_6},
     {rf_5},
     {rf_4},
     {rf_3},
     {rf_2},
     {rf_1},
     {rf_0}};
  wire [7:0][31:0]  _GEN_0 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {_GEN[io_cmd_aIdx]},
     {io_in_scalar},
     {{{16{northReg[15]}}, northReg}},
     {{{16{pipeReg[15]}}, pipeReg}},
     {32'h0}};
  wire [7:0][31:0]  _GEN_1 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {_GEN[io_cmd_bIdx]},
     {io_in_scalar},
     {{{16{northReg[15]}}, northReg}},
     {{{16{pipeReg[15]}}, pipeReg}},
     {32'h0}};
  wire [7:0][31:0]  _GEN_2 =
    {{32'h0},
     {32'h0},
     {32'h0},
     {_GEN[io_cmd_cIdx]},
     {io_in_scalar},
     {{{16{northReg[15]}}, northReg}},
     {{{16{pipeReg[15]}}, pipeReg}},
     {32'h0}};
  wire              _GEN_3 = io_cmd_op == 4'h2;
  wire              _GEN_4 = io_cmd_op == 4'h3;
  wire              _GEN_5 = io_cmd_op == 4'h4;
  wire              _GEN_6 = io_cmd_op == 4'h5;
  wire              _GEN_7 = _GEN_5 | _GEN_6;
  wire [31:0]       _sharedMacOut_T_1 =
    (_GEN_3 ? 32'h1 : _GEN_4 ? 32'hFFFFFFFF : _GEN_7 ? _GEN_0[io_cmd_aSel] : 32'h0)
    * (_GEN_3 | _GEN_4 | _GEN_7 ? _GEN_1[io_cmd_bSel] : 32'h1)
    + (_GEN_3 | _GEN_4
         ? _GEN_0[io_cmd_aSel]
         : _GEN_5 | ~_GEN_6 ? 32'h0 : _GEN_2[io_cmd_cSel]);
  wire              _GEN_8 = io_cmd_op == 4'h0;
  wire              _GEN_9 = io_cmd_op == 4'h1;
  wire              _GEN_10 = io_cmd_op == 4'h6;
  wire              _fuOut_T =
    $signed(_GEN_1[io_cmd_bSel]) > $signed(_GEN_0[io_cmd_aSel]);
  wire              _GEN_11 = _GEN_3 | _GEN_4 | _GEN_5 | _GEN_6;
  wire [31:0]       fuOut =
    _GEN_8
      ? 32'h0
      : _GEN_9
          ? _GEN_0[io_cmd_aSel]
          : _GEN_11
              ? _sharedMacOut_T_1
              : _GEN_10 ? (_fuOut_T ? _GEN_1[io_cmd_bSel] : _GEN_0[io_cmd_aSel]) : 32'h0;
  always @(posedge clock) begin
    if (reset) begin
      pipeReg <= 16'h0;
      northReg <= 16'h0;
      rf_0 <= 32'h0;
      rf_1 <= 32'h0;
      rf_2 <= 32'h0;
      rf_3 <= 32'h0;
      rf_4 <= 32'h0;
      rf_5 <= 32'h0;
      rf_6 <= 32'h0;
      rf_7 <= 32'h0;
      rf_8 <= 32'h0;
      rf_9 <= 32'h0;
    end
    else begin
      automatic logic _GEN_12 = io_cmd_en & io_cmd_writeDst;
      pipeReg <= io_in_w;
      northReg <= io_in_n;
      if (_GEN_12 & io_cmd_dstIdx == 4'h0) begin
        if (_GEN_8)
          rf_0 <= 32'h0;
        else if (_GEN_9)
          rf_0 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_0 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_0 <= _GEN_1[io_cmd_bSel];
          else
            rf_0 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_0 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h1) begin
        if (_GEN_8)
          rf_1 <= 32'h0;
        else if (_GEN_9)
          rf_1 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_1 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_1 <= _GEN_1[io_cmd_bSel];
          else
            rf_1 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_1 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h2) begin
        if (_GEN_8)
          rf_2 <= 32'h0;
        else if (_GEN_9)
          rf_2 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_2 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_2 <= _GEN_1[io_cmd_bSel];
          else
            rf_2 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_2 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h3) begin
        if (_GEN_8)
          rf_3 <= 32'h0;
        else if (_GEN_9)
          rf_3 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_3 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_3 <= _GEN_1[io_cmd_bSel];
          else
            rf_3 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_3 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h4) begin
        if (_GEN_8)
          rf_4 <= 32'h0;
        else if (_GEN_9)
          rf_4 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_4 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_4 <= _GEN_1[io_cmd_bSel];
          else
            rf_4 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_4 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h5) begin
        if (_GEN_8)
          rf_5 <= 32'h0;
        else if (_GEN_9)
          rf_5 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_5 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_5 <= _GEN_1[io_cmd_bSel];
          else
            rf_5 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_5 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h6) begin
        if (_GEN_8)
          rf_6 <= 32'h0;
        else if (_GEN_9)
          rf_6 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_6 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_6 <= _GEN_1[io_cmd_bSel];
          else
            rf_6 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_6 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h7) begin
        if (_GEN_8)
          rf_7 <= 32'h0;
        else if (_GEN_9)
          rf_7 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_7 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_7 <= _GEN_1[io_cmd_bSel];
          else
            rf_7 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_7 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h8) begin
        if (_GEN_8)
          rf_8 <= 32'h0;
        else if (_GEN_9)
          rf_8 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_8 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_8 <= _GEN_1[io_cmd_bSel];
          else
            rf_8 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_8 <= 32'h0;
      end
      if (_GEN_12 & io_cmd_dstIdx == 4'h9) begin
        if (_GEN_8)
          rf_9 <= 32'h0;
        else if (_GEN_9)
          rf_9 <= _GEN_0[io_cmd_aSel];
        else if (_GEN_11)
          rf_9 <= _sharedMacOut_T_1;
        else if (_GEN_10) begin
          if (_fuOut_T)
            rf_9 <= _GEN_1[io_cmd_bSel];
          else
            rf_9 <= _GEN_0[io_cmd_aSel];
        end
        else
          rf_9 <= 32'h0;
      end
    end
  end // always @(posedge)
  assign io_out_e = pipeReg;
  assign io_out_s =
    io_cmd_en & io_cmd_southFromFu
      ? ($signed(fuOut) > 32'sh7FFF
           ? 16'h7FFF
           : $signed(fuOut) < -32'sh8000 ? 16'h8000 : fuOut[15:0])
      : northReg;
endmodule

